# SPDX-License-Identifier: GPL-3.0-only
# Commercial licensing available under separate agreement; see LICENSING.md.
"""
ESPectre - Reference High-Accuracy Motion Detector

Neural network-based motion detector implementing the IDetector interface.
Uses pre-trained weights from ml_weights.py (auto-generated by training script).

Usage:
    from high_accuracy_detector import HighAccuracyDetector
    
    detector = HighAccuracyDetector()
    detector.process_packet(csi_data, subcarriers)
    metrics = detector.update_state()

Author: Francesco Pace <francesco.pace@gmail.com>
"""
import math
import struct
import sys

from micro_espectre.config import DEFAULT_SUBCARRIERS
from micro_espectre.detector_interface import IDetector, MotionState

try:
    from . import ml_weights as _ml_weights
    from .csi_features import (
        AGGREGATED_TURBULENCE_FEATURES,
        CHANNEL_SHAPE_TRAJECTORY_FEATURES,
        L1_DELTA_LAG,
        L1_TRACKER_FEATURES,
        TURB_IQR_AGGREGATION_WIDTH,
        L1DeltaTracker,
        extract_features_by_name,
    )
    from .ml_feature_trackers import ChannelShapeTrajectoryTracker
    from .segmentation import SegmentationContext
except ImportError:
    import ml_weights as _ml_weights
    from csi_features import (
        AGGREGATED_TURBULENCE_FEATURES,
        CHANNEL_SHAPE_TRAJECTORY_FEATURES,
        L1_DELTA_LAG,
        L1_TRACKER_FEATURES,
        TURB_IQR_AGGREGATION_WIDTH,
        L1DeltaTracker,
        extract_features_by_name,
    )
    from ml_feature_trackers import ChannelShapeTrajectoryTracker
    from segmentation import SegmentationContext

FEATURE_MEAN = _ml_weights.FEATURE_MEAN
FEATURE_SCALE = _ml_weights.FEATURE_SCALE
BIASES = _ml_weights.BIASES
FEATURE_NAMES = _ml_weights.FEATURE_NAMES

# Re-export for convenience
__all__ = [
    'ProductionFeatureExtractor',
    'HighAccuracyDetector',
    'predict',
    'is_motion',
    'DEFAULT_SUBCARRIERS',
    'FEATURE_NAMES',
]

# High-Accuracy profile constants (direct 0-1 probability scale)
HIGH_ACCURACY_DEFAULT_THRESHOLD = 0.5
HIGH_ACCURACY_MIN_THRESHOLD = 0.0
HIGH_ACCURACY_MAX_THRESHOLD = 1.0
HIGH_ACCURACY_METRIC_SCALE = 1.0

# Firmware inference accumulates IEEE-754 binary32. CPython follows that
# rounding so report replay can match the host C++ detector.
_USE_IEEE_FLOAT32 = sys.implementation.name != "micropython"


def _f32(value):
    """Return ``value`` rounded the way firmware ``float`` arithmetic rounds."""
    if not _USE_IEEE_FLOAT32:
        return float(value)
    return struct.unpack("f", struct.pack("f", float(value)))[0]

# New exports are already [output][input]. Retain a compatibility path for
# older deployed weight modules so over-the-air module updates remain safe.
_WEIGHTS_T = getattr(_ml_weights, "WEIGHTS_T", None)
if _WEIGHTS_T is None:
    _legacy_weights = _ml_weights.WEIGHTS
    _WEIGHTS_T = []
    for _lw in _legacy_weights:
        _n_in = len(_lw)
        _n_out = len(_lw[0])
        _WEIGHTS_T.append(
            [[_lw[i][j] for i in range(_n_in)] for j in range(_n_out)]
        )
    del _legacy_weights, _lw, _n_in, _n_out
del _ml_weights

# ============================================================================
# Neural Network Inference Functions
# ============================================================================

def relu(x):
    """ReLU activation function."""
    return x if x > 0 else 0.0


def sigmoid(x):
    """Sigmoid activation function with overflow protection."""
    value = _f32(x)
    if value < -20:
        return 0.0
    if value > 20:
        return 1.0
    return _f32(1.0 / _f32(1.0 + math.exp(-value)))


def predict(features):
    """
    Predict motion probability from the exported feature vector.
    
    Args:
        features: Ordered feature vector expected by the exported model
    
    Returns:
        float: Motion probability (0.0 to 1.0)
    """
    workspace_size = max(
        len(FEATURE_MEAN),
        max(len(layer_biases) for layer_biases in BIASES),
    )
    return _predict_with_workspace(
        features,
        [0.0] * workspace_size,
        [0.0] * workspace_size,
    )


def _predict_with_workspace(features, activation_a, activation_b):
    """Run inference using two reusable activation buffers."""
    n_feat = len(features)
    if len(activation_a) < n_feat or len(activation_b) < n_feat:
        raise ValueError("Activation workspace is too small")
    for i in range(n_feat):
        activation_a[i] = _f32(
            _f32(features[i] - FEATURE_MEAN[i]) / FEATURE_SCALE[i]
        )

    activations = activation_a
    next_activations = activation_b
    n_active = n_feat
    n_layers = len(_WEIGHTS_T)
    for layer_idx in range(n_layers):
        weights_t = _WEIGHTS_T[layer_idx]
        biases = BIASES[layer_idx]
        n_out = len(biases)
        if len(next_activations) < n_out:
            raise ValueError("Activation workspace is too small")
        is_last = layer_idx == n_layers - 1
        for j in range(n_out):
            val = _f32(biases[j])
            w_row = weights_t[j]
            for i in range(n_active):
                val = _f32(val + _f32(_f32(activations[i]) * _f32(w_row[i])))
            next_activations[j] = val if is_last else (val if val > 0 else 0.0)
        activations, next_activations = next_activations, activations
        n_active = n_out

    return sigmoid(_f32(activations[0])) * HIGH_ACCURACY_METRIC_SCALE


def is_motion(features, threshold=HIGH_ACCURACY_DEFAULT_THRESHOLD):
    """
    Detect motion from features.
    
    Args:
        features: Ordered feature vector expected by the exported model
        threshold: Detection threshold (default: 0.5)
    
    Returns:
        bool: True if motion detected
    """
    return predict(features) > threshold


class ProductionFeatureExtractor:
    """Pure-Python owner of the production ML feature stream."""

    def __init__(self, feature_names, window_size=100,
                 enable_lowpass=False, lowpass_cutoff=11.0,
                 enable_hampel=True, hampel_window=7, hampel_threshold=5.0,
                 force_aggregated=False, force_l1_tracker=False):
        self.feature_names = tuple(feature_names)
        self.context = SegmentationContext(
            window_size=window_size,
            enable_lowpass=enable_lowpass,
            lowpass_cutoff=lowpass_cutoff,
            enable_hampel=enable_hampel,
            hampel_window=hampel_window,
            hampel_threshold=hampel_threshold,
        )
        self.uses_l1_tracker = force_l1_tracker or any(
            name in L1_TRACKER_FEATURES for name in self.feature_names
        )
        self.uses_shape_trajectory = any(
            name in CHANNEL_SHAPE_TRAJECTORY_FEATURES
            for name in self.feature_names
        )
        self.uses_aggregated_turbulence = force_aggregated or any(
            name in AGGREGATED_TURBULENCE_FEATURES
            for name in self.feature_names
        )
        self.aggregated_context = (
            SegmentationContext(
                window_size=window_size,
                enable_lowpass=enable_lowpass,
                lowpass_cutoff=lowpass_cutoff,
                enable_hampel=enable_hampel,
                hampel_window=hampel_window,
                hampel_threshold=hampel_threshold,
                adjacent_aggregation_width=TURB_IQR_AGGREGATION_WIDTH,
            )
            if self.uses_aggregated_turbulence else None
        )
        delta_window = max(2, window_size - L1_DELTA_LAG)
        self.l1_tracker = (
            L1DeltaTracker(
                window_size=delta_window,
                lag=L1_DELTA_LAG,
                allocate_amplitude_buffer=False,
                enable_hampel=enable_hampel,
                hampel_window=hampel_window,
                hampel_threshold=hampel_threshold,
            )
            if self.uses_l1_tracker else None
        )
        self.shape_trajectory_tracker = (
            ChannelShapeTrajectoryTracker()
            if self.uses_shape_trajectory else None
        )
        self._ordered_turbulence = [0.0] * window_size
        self._ordered_validity = [False] * window_size
        self._ordered_aggregated_turbulence = (
            [0.0] * window_size if self.uses_aggregated_turbulence else None
        )
        self._ordered_aggregated_validity = (
            [False] * window_size if self.uses_aggregated_turbulence else None
        )
        self._sort_scratch = (
            self._ordered_aggregated_turbulence
            if self._ordered_aggregated_turbulence is not None
            else ([0.0] * window_size if "turb_zcr" in self.feature_names else None)
        )
        self._feature_buffer = [0.0] * len(self.feature_names)
        # Packet extraction and chronological ordering do not overlap.
        self._packet_subcarrier_values = (
            self._ordered_turbulence if window_size >= 64 else [0.0] * 64
        )

    @property
    def packet_amplitudes(self):
        """Return the current selected-subcarrier amplitude scratch and count."""
        return self.context._amplitude_buffer, self.context._amplitude_count

    @property
    def aggregated_amplitudes(self):
        """Return the current aggregated amplitude scratch and count, if enabled."""
        if self.aggregated_context is None:
            return None, 0
        return (
            self.aggregated_context._amplitude_buffer,
            self.aggregated_context._amplitude_count,
        )

    def process_packet(self, csi_data, selected_subcarriers=None, timestamp_us=None):
        """Update every production feature tracker from one CSI packet."""
        if selected_subcarriers is None:
            selected_subcarriers = DEFAULT_SUBCARRIERS
        packet_values = self._packet_subcarrier_values
        packet_count = SegmentationContext.fill_subcarrier_energy_buffer(
            csi_data,
            packet_values,
        )
        if self.shape_trajectory_tracker is not None:
            self.shape_trajectory_tracker.process_packet(
                csi_data,
                timestamp_us,
                packet_values,
                packet_count,
            )
        SegmentationContext.energies_to_amplitudes_in_place(
            packet_values,
            packet_count,
        )
        turbulence = self.context.calculate_spatial_turbulence_from_subcarrier_amplitudes(
            packet_values,
            packet_count,
            selected_subcarriers,
        )
        if self.l1_tracker is not None:
            self.l1_tracker.process_amplitudes(
                self.context._amplitude_buffer,
                self.context._amplitude_count,
                self.context._amplitude_mean,
            )
        self.context.add_turbulence(turbulence)
        if self.aggregated_context is not None:
            aggregated = (
                self.aggregated_context.calculate_spatial_turbulence_from_subcarrier_amplitudes(
                    packet_values,
                    packet_count,
                    selected_subcarriers,
                )
            )
            self.aggregated_context.add_turbulence(aggregated)

    def advance_missing_slots(self, count):
        """Preserve absent slots in every production packet-indexed stream."""
        missing = max(0, int(count))
        for _ in range(missing):
            self.context.add_missing_slot()
            if self.aggregated_context is not None:
                self.aggregated_context.add_missing_slot()
        if self.l1_tracker is not None:
            self.l1_tracker.advance_missing_slots(missing)

    def is_ready(self, minimum_valid_samples=None):
        """Return whether all requested production features own a valid window."""
        minimum = (
            self.context.window_size
            if minimum_valid_samples is None
            else max(1, min(int(minimum_valid_samples), self.context.window_size))
        )
        if self.context.buffer_count < self.context.window_size:
            return False
        if self.context.valid_count < minimum:
            return False
        if (
            self.l1_tracker is not None
            and self.context.window_size > L1_DELTA_LAG
            and self.l1_tracker.count == 0
        ):
            return False
        if self.aggregated_context is not None:
            if self.aggregated_context.buffer_count < self.aggregated_context.window_size:
                return False
            if self.aggregated_context.valid_count < minimum:
                return False
        return True

    def ordered_series(self, aggregated=False):
        """Return reusable chronological values, validity, and active count."""
        if aggregated:
            if self.aggregated_context is None:
                return None, None, 0
            count = self.aggregated_context.copy_chronological_into(
                self._ordered_aggregated_turbulence,
                self._ordered_aggregated_validity,
            )
            return (
                self._ordered_aggregated_turbulence,
                self._ordered_aggregated_validity,
                count,
            )
        count = self.context.copy_chronological_into(
            self._ordered_turbulence,
            self._ordered_validity,
        )
        return self._ordered_turbulence, self._ordered_validity, count

    def extract_features(self):
        """Extract the configured production vector from the current window."""
        turbulence, validity, count = self.ordered_series()
        aggregated, aggregated_validity, aggregated_count = self.ordered_series(
            aggregated=True
        )
        trajectory_innovation = None
        trajectory_excess = None
        trajectory_spread = None
        trajectory_kendall = None
        if self.shape_trajectory_tracker is not None:
            trajectory_innovation, trajectory_excess, trajectory_spread = (
                self.shape_trajectory_tracker.trajectory_features_with_spread()
            )
            trajectory_kendall = (
                self.shape_trajectory_tracker.subband_kendall_lag_excess()
            )
        return extract_features_by_name(
            turbulence,
            count,
            feature_names=self.feature_names,
            aggregated_turbulence_buffer=aggregated,
            aggregated_turbulence_count=aggregated_count,
            sort_scratch=self._sort_scratch,
            l1_delta_lag_ratio=(
                self.l1_tracker.delta_lag_ratio()
                if self.l1_tracker is not None
                and "l1_delta_lag_ratio" in self.feature_names
                else None
            ),
            chan_shape_spread_subband=(
                trajectory_spread
                if "chan_shape_spread_subband" in self.feature_names else None
            ),
            chan_shape_coherent_innovation_energy=(
                trajectory_innovation
                if "chan_shape_coherent_innovation_energy" in self.feature_names
                else None
            ),
            chan_shape_excess_path=(
                trajectory_excess
                if "chan_shape_excess_path" in self.feature_names else None
            ),
            chan_shape_subband_kendall_lag_excess=(
                trajectory_kendall
                if "chan_shape_subband_kendall_lag_excess" in self.feature_names
                else None
            ),
            out=self._feature_buffer,
            reuse_aggregated_turbulence_buffer=True,
            turbulence_validity=validity,
            aggregated_turbulence_validity=aggregated_validity,
        )

    def reset(self):
        """Clear all production feature state."""
        self.context.reset(full=True)
        if self.l1_tracker is not None:
            self.l1_tracker.reset()
        if self.shape_trajectory_tracker is not None:
            self.shape_trajectory_tracker.reset()
        if self.aggregated_context is not None:
            self.aggregated_context.reset(full=True)


# ============================================================================
# HighAccuracyDetector Class
# ============================================================================


class HighAccuracyDetector(IDetector):
    """
    Neural Network-based motion detector.
    
    Uses a pre-trained MLP exported by the training pipeline to classify
    motion based on turbulence features extracted from CSI data.
    
    Algorithm:
    1. Calculate gain-invariant spatial turbulence (std/mean)
    2. Store in circular buffer (window_size packets)
    3. Extract the configured ML feature vector from buffer
    4. Run neural network inference
    5. Compare probability to threshold for state decision
    """
    ALGORITHM = "high_accuracy"
    
    def __init__(self, window_size=100, threshold=HIGH_ACCURACY_DEFAULT_THRESHOLD,
                 enable_lowpass=False, lowpass_cutoff=11.0,
                 enable_hampel=True, hampel_window=7, hampel_threshold=5.0):
        """
        Initialize the High-Accuracy detector.
        
        Args:
            window_size: Feature extraction window size (default: 100, matches C++ DETECTOR_DEFAULT_WINDOW_SIZE)
            threshold: Motion detection threshold (default: 0.5, range 0.0-1.0)
            enable_lowpass: Enable low-pass filter (default: False)
            lowpass_cutoff: Low-pass cutoff frequency Hz (default: 11.0)
            enable_hampel: Enable Hampel filter (default: True)
            hampel_window: Hampel window size (default: 7)
            hampel_threshold: Hampel threshold in MAD (default: 5.0)
        """
        self._feature_extractor = ProductionFeatureExtractor(
            FEATURE_NAMES,
            window_size=window_size,
            enable_lowpass=enable_lowpass,
            lowpass_cutoff=lowpass_cutoff,
            enable_hampel=enable_hampel,
            hampel_window=hampel_window,
            hampel_threshold=hampel_threshold,
        )
        # Retain these internal aliases for device diagnostics and tests.
        self._context = self._feature_extractor.context
        self._aggregated_context = self._feature_extractor.aggregated_context
        self._l1_tracker = self._feature_extractor.l1_tracker
        self._shape_trajectory_tracker = (
            self._feature_extractor.shape_trajectory_tracker
        )
        self._threshold = threshold
        self._packet_count = 0
        self._motion_count = 0
        self._state = MotionState.IDLE
        self._current_probability = 0.0
        self._minimum_valid_samples = window_size
        workspace_size = max(
            len(FEATURE_MEAN),
            max(len(layer_biases) for layer_biases in BIASES),
        )
        self._activation_a = [0.0] * workspace_size
        self._activation_b = [0.0] * workspace_size
        
        # For tracking (optional)
        self.probability_history = []
        self.state_history = []
        self.track_data = False
    
    def process_packet(self, csi_data, selected_subcarriers=None, rssi_dbm=None,
                       timestamp_us=None):
        """
        Process a CSI packet.
        
        Args:
            csi_data: Raw CSI data (int8 I/Q pairs)
            selected_subcarriers: Subcarrier indices to use
            rssi_dbm: Optional per-packet RSSI metadata (ignored by ML)
            timestamp_us: Optional monotonic packet timestamp in microseconds
        """
        self._packet_count += 1
        self._feature_extractor.process_packet(
            csi_data,
            selected_subcarriers,
            timestamp_us,
        )

    def advance_missing_slots(self, count):
        """Preserve absent slots in every packet-indexed feature stream."""
        self._feature_extractor.advance_missing_slots(count)

    def set_minimum_valid_samples(self, count):
        self._minimum_valid_samples = max(1, min(int(count), self._context.window_size))
    
    def update_state(self):
        """
        Run inference and update state.
        
        Returns:
            dict: Current metrics including state and probability
        """
        if not self.is_ready():
            return {
                'state': self._state,
                'motion_metric': 0.0,
                'probability': 0.0,
                'threshold': self._threshold
            }
        
        # Extract features from turbulence buffer
        features = self._extract_features()
        
        # Run neural network
        self._current_probability = _predict_with_workspace(
            features,
            self._activation_a,
            self._activation_b,
        )
        
        # Update state
        if self._current_probability > self._threshold:
            self._state = MotionState.MOTION
        else:
            self._state = MotionState.IDLE
        
        if self.track_data:
            self.probability_history.append(self._current_probability)
            state_str = 'MOTION' if self._state == MotionState.MOTION else 'IDLE'
            self.state_history.append(state_str)
            if self._state == MotionState.MOTION:
                self._motion_count += 1
        
        return {
            'state': self._state,
            'motion_metric': self._current_probability,
            'probability': self._current_probability,
            'threshold': self._threshold
        }
    
    def _extract_features(self):
        """Extract the configured production feature vector."""
        return self._feature_extractor.extract_features()
    
    def get_state(self):
        """Get current motion state."""
        return self._state
    
    def get_motion_metric(self):
        """Get current motion probability."""
        return self._current_probability
    
    def get_threshold(self):
        """Get current probability threshold."""
        return self._threshold
    
    def set_threshold(self, threshold):
        """Set threshold (range 0.0-1.0 on the ML probability scale)."""
        if HIGH_ACCURACY_MIN_THRESHOLD <= threshold <= HIGH_ACCURACY_MAX_THRESHOLD:
            self._threshold = threshold
            return True
        return False

    def is_ready(self):
        """Check if buffer is full."""
        return self._feature_extractor.is_ready(self._minimum_valid_samples)
    
    def reset(self):
        """Reset detector state."""
        self._feature_extractor.reset()
        self._packet_count = 0
        self._state = MotionState.IDLE
        self._current_probability = 0.0
        self._motion_count = 0
        self.probability_history = []
        self.state_history = []
    
    def get_name(self):
        """Get detector name."""
        return "High Accuracy"

    def get_window_size(self):
        """Return the resolved detector window in samples."""
        return self._context.window_size
    
    @property
    def total_packets(self):
        """Total packets processed."""
        return self._packet_count
    
    def get_motion_count(self):
        """Get number of motion detections (for tracking)."""
        return self._motion_count
