name: 'QEMU Smoke Test'
description: 'Run ESP32 firmware smoke test in QEMU emulator'

inputs:
  chip:
    description: 'ESP32 chip variant (esp32, esp32s3, esp32c3, esp32c6)'
    required: true
  arch:
    description: 'CPU architecture (xtensa, riscv32)'
    required: true
  machine:
    description: 'QEMU machine type (esp32, esp32s3, esp32c3, esp32c6)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Free disk space
      shell: bash
      run: |
        # Remove unnecessary tools to free space for Docker image (~13GB freed)
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        df -h /

    - name: Find firmware
      id: firmware
      shell: bash
      run: |
        FIRMWARE=$(find examples -name "firmware.factory.bin" -type f | head -1)
        if [ -z "$FIRMWARE" ]; then
          echo "Error: firmware.factory.bin not found"
          exit 1
        fi
        echo "path=$FIRMWARE" >> $GITHUB_OUTPUT
        echo "Found firmware: $FIRMWARE"

    - name: Prepare flash image
      shell: bash
      run: |
        pip install esptool
        python -m esptool --chip ${{ inputs.chip }} merge-bin --pad-to-size 4MB -o /tmp/flash_qemu.bin 0x0 "${{ steps.firmware.outputs.path }}"
        ls -lh /tmp/flash_qemu.bin

    - name: Pull Docker image
      shell: bash
      run: docker pull espressif/idf:release-v5.5

    - name: Run QEMU
      shell: bash
      run: |
        # Select QEMU binary based on architecture
        if [ "${{ inputs.arch }}" = "xtensa" ]; then
          QEMU_PATH="/opt/esp/tools/qemu-xtensa/esp_develop_9.2.2_20250817/qemu/bin/qemu-system-xtensa"
        else
          QEMU_PATH="/opt/esp/tools/qemu-riscv32/esp_develop_9.2.2_20250817/qemu/bin/qemu-system-riscv32"
        fi
        
        docker run --rm \
          -v /tmp/flash_qemu.bin:/flash.bin \
          espressif/idf:release-v5.5 bash -c "
            timeout 60 $QEMU_PATH \
              -nographic \
              -machine ${{ inputs.machine }} \
              -drive file=/flash.bin,if=mtd,format=raw \
              -global driver=timer.${{ inputs.machine }}.timg,property=wdt_disable,value=true \
              -no-reboot 2>&1
          " | tee qemu_output.log || true

    - name: Check boot success
      shell: bash
      run: |
        echo "=== QEMU Output (${{ inputs.chip }}) ==="
        cat qemu_output.log
        echo "========================================"
        
        # Check for crashes
        if grep -qiE "panic|abort|Guru Meditation|assert failed|stack smashing" qemu_output.log; then
          echo ""
          echo "SMOKE TEST FAILED - CRASH DETECTED!"
          grep -iE "panic|abort|Guru Meditation|assert failed|stack smashing" qemu_output.log
          
          # Decode stack trace if backtrace is present
          BACKTRACE=$(grep -oE "Backtrace: [0-9a-fx: ]+" qemu_output.log | head -1 | sed 's/Backtrace: //')
          if [ -n "$BACKTRACE" ]; then
            echo ""
            echo "=== Stack Trace Analysis ==="
            FIRMWARE_ELF=$(find examples -name "firmware.elf" -type f | head -1)
            if [ -n "$FIRMWARE_ELF" ]; then
              # Extract addresses and decode with addr2line
              ADDRS=$(echo "$BACKTRACE" | grep -oE "0x[0-9a-f]+" | tr '\n' ' ')
              
              # Select addr2line based on architecture
              if [ "${{ inputs.arch }}" = "xtensa" ]; then
                ADDR2LINE=$(find ~/.platformio/tools -name "xtensa-*-elf-addr2line" 2>/dev/null | head -1)
              else
                ADDR2LINE=$(find ~/.platformio/tools -name "riscv32-*-elf-addr2line" 2>/dev/null | head -1)
              fi
              
              if [ -n "$ADDR2LINE" ]; then
                echo "Using: $ADDR2LINE"
                echo "ELF: $FIRMWARE_ELF"
                echo ""
                $ADDR2LINE -pfiaC -e "$FIRMWARE_ELF" $ADDRS
              else
                echo "addr2line not found, showing raw addresses:"
                echo "$BACKTRACE"
              fi
            else
              echo "ELF file not found, showing raw backtrace:"
              echo "$BACKTRACE"
            fi
          fi
          
          exit 1
        fi
        
        # Track boot progress
        echo ""
        echo "=== Boot Progress Checks ==="
        CHECKS_PASSED=0
        
        if grep -qE "ESP-IDF.*bootloader|boot:" qemu_output.log; then
          echo "[OK] Bootloader started"
          CHECKS_PASSED=$((CHECKS_PASSED + 1))
        fi
        
        if grep -qE "Partition Table|End of partition table" qemu_output.log; then
          echo "[OK] Partition table loaded"
          CHECKS_PASSED=$((CHECKS_PASSED + 1))
        fi
        
        if grep -qE "esp_image: segment|Loaded app from partition" qemu_output.log; then
          echo "[OK] Application image loaded"
          CHECKS_PASSED=$((CHECKS_PASSED + 1))
        fi
        
        if grep -qE "Disabling RNG early entropy source" qemu_output.log; then
          echo "[OK] Bootloader completed, app starting"
          CHECKS_PASSED=$((CHECKS_PASSED + 1))
        fi
        
        echo ""
        echo "Checks passed: $CHECKS_PASSED/4"
        
        if [ $CHECKS_PASSED -ge 3 ]; then
          echo "SMOKE TEST PASSED - Firmware boots without crashes"
        else
          echo "WARNING: Boot may have stalled - only $CHECKS_PASSED/4 checks passed"
        fi
