#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Commercial licensing available under separate agreement; see LICENSING.md.
"""Generate ESPHome validation constants from the public SDK sensing schema."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
from pprint import pformat
import re

REPO_ROOT = Path(__file__).resolve().parents[2]
CPP_ROOT = REPO_ROOT / "src" / "cpp"
OUTPUT = CPP_ROOT / "frontend" / "esphome" / "components" / "espectre" / "sensing_schema.py"
SCHEMA_HEADERS = (
    "core/detector_types.h",
    "core/filter_config.h",
    "runtime/runtime_sensing_schema.h",
)
CONST_PATTERN = re.compile(
    r"constexpr\s+(?:const char \*const|bool|float|size_t|uint8_t|uint16_t|uint32_t)\s+"
    r"([A-Z][A-Z0-9_]+)\s*=\s*([^;]+);"
)


def parse_literal(raw: str, constants: dict):
    value = raw.strip()
    if value in constants:
        return constants[value]
    if value in ("true", "false"):
        return value == "true"
    if value.startswith('"') and value.endswith('"'):
        return value[1:-1]
    value = value.removesuffix("f").removesuffix("F").removesuffix("u").removesuffix("U")
    return float(value) if "." in value or "e" in value.lower() else int(value)


def render_schema(cpp_root: Path = CPP_ROOT) -> str:
    constants = {"UINT16_MAX": 65535}
    digests = []
    for relative in SCHEMA_HEADERS:
        source = (cpp_root / relative).read_bytes()
        digests.append(hashlib.sha256(source).hexdigest())
        for match in CONST_PATTERN.finditer(source.decode("utf-8")):
            constants[match[1]] = parse_literal(match[2], constants)
    fingerprint = hashlib.sha256("".join(digests).encode("ascii")).hexdigest()
    schema = {name: value for name, value in constants.items() if name.startswith("RUNTIME_")}
    return (
        "# SPDX-License-Identifier: GPL-3.0-only\n"
        "# Commercial licensing available under separate agreement; see LICENSING.md.\n"
        "# Generated by .github/scripts/generate_esphome_schema.py; do not edit.\n"
        f'SDK_SCHEMA_SHA256 = "{fingerprint}"\n\n'
        f"RUNTIME_SCHEMA = {pformat(schema, sort_dicts=True, width=100)}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when the checked-in schema is stale.")
    args = parser.parse_args()
    expected = render_schema()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            parser.exit(1, "ESPHome sensing schema is stale; run .github/scripts/generate_esphome_schema.py\n")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
