include("${CMAKE_CURRENT_LIST_DIR}/../../../espectre_sources.cmake")

idf_component_register(
    SRCS
        ${ESPECTRE_FRONTEND_BLE_SOURCES}
        ${ESPECTRE_CORE_SOURCES}
        ${ESPECTRE_RUNTIME_ESP_IDF_SOURCES}
        ${ESPECTRE_RUNTIME_ESP_IDF_BLE_PROVISIONING_SOURCES}
        ${ESPECTRE_RUNTIME_ESP_IDF_MQTT_SOURCES}
    INCLUDE_DIRS
        "."
        ${ESPECTRE_SHARED_INCLUDE_DIRS}
    REQUIRES
        esp_wifi
        esp_event
        esp_netif
        esp_timer
        bt
        mqtt
        nvs_flash
        lwip
        driver
        freertos
        heap
        log
)
