/*
 * ESPectre - Gesture LogReg Weights
 *
 * Auto-generated logistic regression weights for gesture classification.
 * Architecture: 12 -> 3 (softmax)
 * Classes: 3
 * Trained: 2026-03-03 23:58:14
 * Seed: 1917586999
 *
 * This file is auto-generated by 11_train_gesture_model.py.
 * DO NOT EDIT - your changes will be overwritten!
 *
 * Author: Francesco Pace <francesco.pace@gmail.com>
 * License: GPLv3
 */

#pragma once

namespace esphome {
namespace espectre {

constexpr int GESTURE_NUM_CLASSES = 3;

constexpr float GESTURE_FEATURE_MEAN[12] = {1.097500f, 0.453553f, 1.534071f, -0.092895f, 1.027901f, 1.914167f, 0.066745f, 1.022496f, 3.206552f, 1.145237f, 1.544903f, 0.216352f};
constexpr float GESTURE_FEATURE_SCALE[12] = {0.103652f, 0.278116f, 0.341206f, 0.556232f, 0.270671f, 1.912298f, 0.132426f, 0.939867f, 3.300558f, 0.730325f, 0.282965f, 0.165910f};

constexpr const char* GESTURE_CLASS_LABELS[3] = {
    "wave",
    "circle_cw",
    "no_gesture",
};

constexpr float GESTURE_W1[12][3] = {
    {1.317486f, 0.949319f, -2.266806f},
    {-0.300656f, 0.203831f, 0.096825f},
    {-0.816334f, 0.901441f, -0.085107f},
    {-0.300656f, 0.203831f, 0.096825f},
    {0.020436f, 0.029963f, -0.050399f},
    {-1.075285f, 1.320863f, -0.245578f},
    {0.065980f, -0.121140f, 0.055160f},
    {-0.496184f, 0.357534f, 0.138649f},
    {-0.393282f, -0.005184f, 0.398466f},
    {-0.101682f, -0.360097f, 0.461778f},
    {-0.073356f, 0.205634f, -0.132278f},
    {0.092267f, -0.458826f, 0.366559f},
};
constexpr float GESTURE_B1[3] = {-0.589033f, -0.758690f, 1.347723f};

}  // namespace espectre
}  // namespace esphome
