/*
 * ESPectre - Gesture Detector
 *
 * Event-driven gesture classifier. Maintains a circular look-back ring buffer
 * that is always updated with each CSI packet.
 *
 * Architecture:
 *   - Ring buffer (GESTURE_RING_SIZE packets) always active
 *   - start_detection(): snapshots ring buffer as pre-roll into event buffer
 *   - process_packet(): feeds turbulence into ring; when active, also appends
 *     to event buffer
 *   - process_packet(): once fixed window is ready during MOTION, performs
 *     periodic live inference on a sliding window and stores pending predictions
 *   - finalize_detection(): finalizes event and optionally emits a final prediction
 *
 * Inference requires gesture_weights.h (auto-generated by 12_train_gesture_model.py).
 * When weights are not yet available (GESTURE_NUM_CLASSES == 0), finalize_detection()
 * returns nullptr.
 *
 * Author: Francesco Pace <francesco.pace@gmail.com>
 * License: GPLv3
 */

#pragma once

#include <cstdint>
#include <cstddef>
#include <cstring>

// gesture_weights.h is auto-generated and required at compile time.
#include "gesture_weights.h"

#include "gesture_features.h"

namespace esphome {
namespace espectre {

static_assert(GESTURE_NUM_FEATURES <= GESTURE_TOTAL_AVAILABLE_FEATURES,
              "gesture model requests more features than extractor provides");

// Ring buffer: 3 seconds at 100 pps
constexpr uint16_t GESTURE_RING_SIZE = 300;

// Fixed classification window: 2 seconds at 100 pps
constexpr uint16_t GESTURE_WINDOW_LEN = 200;

// Pre-roll copied at motion start: 0.75 seconds at 100 pps
constexpr uint16_t GESTURE_PREROLL_LEN = 75;

// Live inference cadence while MOTION is active (in packets)
constexpr uint16_t GESTURE_LIVE_STRIDE = 25;

// Event buffer capacity (kept separate for clarity)
constexpr uint16_t GESTURE_MAX_EVENT_LEN = GESTURE_WINDOW_LEN;

// Number of subcarriers used for phase storage (same as ML_SUBCARRIERS)
constexpr uint8_t GESTURE_PHASE_SC = 12;

// Runtime gating to reduce false positives on live stream.
constexpr float GESTURE_CONFIDENCE_FLOOR = 0.00f;
constexpr float GESTURE_MARGIN_FLOOR = 0.00f;
constexpr uint8_t GESTURE_MIN_CONSECUTIVE_FLOOR = 2;

constexpr float GESTURE_MIN_CONFIDENCE =
    (GESTURE_REJECT_CONFIDENCE > GESTURE_CONFIDENCE_FLOOR)
        ? GESTURE_REJECT_CONFIDENCE
        : GESTURE_CONFIDENCE_FLOOR;
constexpr float GESTURE_MIN_MARGIN =
    (GESTURE_REJECT_MARGIN > GESTURE_MARGIN_FLOOR)
        ? GESTURE_REJECT_MARGIN
        : GESTURE_MARGIN_FLOOR;
constexpr uint8_t GESTURE_MIN_CONSECUTIVE = GESTURE_MIN_CONSECUTIVE_FLOOR;

/**
 * Gesture Detector
 *
 * Does NOT inherit from BaseDetector — it is a separate component that
 * runs in parallel to the motion detector.
 */
class GestureDetector {
public:
    GestureDetector();
    ~GestureDetector() = default;

    // Disable copy
    GestureDetector(const GestureDetector&) = delete;
    GestureDetector& operator=(const GestureDetector&) = delete;

    /**
     * Process a CSI packet.
     *
     * Always updates the ring buffer. When active (after start_detection()),
     * also appends to the event buffer.
     *
     * @param csi_data  Raw CSI data (I/Q interleaved int8)
     * @param csi_len   Length of CSI data in bytes
     * @param subcarriers Selected subcarrier indices (nullptr = use defaults)
     * @param num_sc    Number of subcarriers
     */
    void process_packet(const int8_t* csi_data, size_t csi_len,
                        const uint8_t* subcarriers = nullptr, uint8_t num_sc = 0);

    /**
     * Snapshots the ring buffer as pre-roll for the event buffer, so that
     * the beginning of the gesture is
     * included in the classification window.
     */
    void start_detection();

    /**
     * Classifies the accumulated event.
     *
     * @return Gesture name (e.g. "wave") or nullptr if:
     *         - Event is too short (< 10 packets)
     */
    const char* finalize_detection();

    /**
     * Consume pending live prediction produced during MOTION.
     *
     * @return Predicted gesture label if available, otherwise nullptr.
     *         Returned value is consumed (one-shot).
     */
    const char* consume_live_prediction();

    /**
     * Clear the ring buffer (call on WiFi channel change).
     */
    void clear_ring();

    /**
     * Reset event state (ring buffer preserved).
     */
    void reset();

    bool is_active() const { return active_; }
    uint16_t event_len() const { return event_len_; }
    bool weights_available() const { return true; }
    const char* last_gesture() const { return last_gesture_; }
    void set_cv_normalization(bool enabled) { use_cv_normalization_ = enabled; }

private:
    /**
     * Run model inference on extracted features.
     *
     * @param features Feature vector (GESTURE_NUM_FEATURES floats)
     * @return Predicted class label
     */
    const char* predict(const float* features, float* out_confidence = nullptr, float* out_margin = nullptr);

    // -------------------------------------------------------------------------
    // Ring buffer (circular, always active)
    // -------------------------------------------------------------------------

    // Turbulence values stored in ring buffer
    float ring_turb_[GESTURE_RING_SIZE];
    // Phase arrays stored in ring buffer (flat: ring[i] = ring_phases_[i * GESTURE_PHASE_SC])
    float ring_phases_[GESTURE_RING_SIZE * GESTURE_PHASE_SC];
    uint16_t ring_head_;   // Index of oldest element (when full)
    uint16_t ring_count_;  // Number of valid elements in ring

    // -------------------------------------------------------------------------
    // Event buffer (accumulated during an active event)
    // -------------------------------------------------------------------------

    float event_turb_[GESTURE_MAX_EVENT_LEN];
    float event_phases_[GESTURE_MAX_EVENT_LEN * GESTURE_PHASE_SC];
    uint16_t event_len_;

    bool active_;
    const char* last_gesture_;
    const char* pending_live_gesture_;
    const char* last_live_gesture_;
    const char* candidate_live_gesture_;
    uint8_t candidate_live_count_;
    uint16_t live_packets_since_start_;
    bool use_cv_normalization_;
};

}  // namespace espectre
}  // namespace esphome
