/*
 * ESPectre - Gesture LogReg Weights
 *
 * Auto-generated logistic regression weights for gesture classification.
 * Architecture: LogReg (9 -> 3)
 * Trained: 2026-03-15 14:03:40
 * Seed: 805649460
 *
 * This file is auto-generated by 12_train_gesture_model.py.
 * DO NOT EDIT - your changes will be overwritten!
 *
 * Author: Francesco Pace <francesco.pace@gmail.com>
 * License: GPLv3
 */

#pragma once

#include <cstdint>

namespace esphome {
namespace espectre {

constexpr int GESTURE_NUM_CLASSES = 3;
constexpr int GESTURE_NUM_FEATURES = 9;
constexpr float GESTURE_REJECT_CONFIDENCE = 0.20000000f;
constexpr float GESTURE_REJECT_MARGIN = 0.12000000f;

constexpr const char* GESTURE_CLASS_LABELS[3] = {
    "wave",
    "circle_cw",
    "no_gesture",
};
constexpr uint8_t GESTURE_FEATURE_IDS[9] = {14, 8, 0, 12, 9, 13, 16, 17, 18};

constexpr float GESTURE_FEATURE_MEAN[9] = {1.94136853f, 4.53780955f, 0.99125000f, 2.62004295f, 11.59110024f, 0.43994861f, 0.99185435f, 11.73437758f, 17.87484521f};
constexpr float GESTURE_FEATURE_SCALE[9] = {0.03574773f, 2.86859148f, 0.02825664f, 1.14462678f, 1.18470308f, 0.11987759f, 0.00272810f, 2.13594472f, 9.89275089f};

constexpr float GESTURE_LOGREG_COEFS[27] = {0.81680858f, -0.33563226f, 0.49421686f, -0.08004459f, 0.43787879f, 0.51113933f, -0.75912726f, -0.77271628f, -0.50285667f, 0.19678301f, 1.25197899f, 0.21821442f, 0.48135719f, -0.41722095f, -0.05569398f, -1.03612220f, 0.11377960f, 1.12331378f, -1.01359165f, -0.91634679f, -0.71243125f, -0.40131262f, -0.02065782f, -0.45544535f, 1.79524946f, 0.65893668f, -0.62045711f};
constexpr float GESTURE_LOGREG_INTERCEPTS[3] = {0.61247689f, -0.75919163f, 0.14671473f};

}  // namespace espectre
}  // namespace esphome
