/*
 * ESPectre - ML Detector
 *
 * Neural network-based motion detection algorithm.
 *
 * Algorithm:
 * 1. Calculate spatial turbulence per packet using CV normalization
 *    (`std/mean`)
 * 2. Apply optional Hampel filtering to turbulence and L1-delta streams
 * 3. Apply optional low-pass filter for noise reduction
 * 4. Extract statistical features from turbulence buffer
 * 5. Run MLP inference using exported architecture metadata
 * 6. Compare probability to threshold for motion detection
 *
 * Author: Francesco Pace <francesco.pace@gmail.com>
 * License: GPLv3
 */
#pragma once

#include "base_detector.h"
#include "csi_format.h"
#include "csi_features.h"
#include "l1_delta_tracker.h"
#include "ml_feature_trackers.h"
#include <cstdint>
#include <cstddef>

namespace espectre {

// ML-specific constants
constexpr float ML_DEFAULT_THRESHOLD = 0.5f;
constexpr float ML_MIN_THRESHOLD = 0.0f;
constexpr float ML_MAX_THRESHOLD = 1.0f;
constexpr float ML_METRIC_SCALE = 1.0f;

/**
 * Neural motion detector, using the MLP weights exported by training.
 *
 * Unlike `ClassicDetector` it does not calibrate to the room: it ships a fixed
 * threshold learned at training time, so it performs best in environments the
 * training corpus represents. Check the per-chip figures in
 * `docs/performance/README.md` before choosing it over Classic.
 *
 * Same usage as `ClassicDetector` on the core-only path, and the same
 * threading rules. `core/ml_weights.h` is generated by the training script and
 * must not be edited by hand; retraining is documented in
 * `docs/ML_TRAINING.md`.
 */
class MLDetector : public BaseDetector {
public:
    /**
     * Constructor
     * 
     * @param window_size Feature extraction window size (10-200 packets)
     * @param threshold Motion detection threshold (0.0-1.0 on the ML probability scale)
     */
    /**
     * @param lag Profile-displacement distance in packets. Production uses the
     *        nominal-rate default. Alternate values are for replay experiments
     *        and require retraining before deployment.
     */
    MLDetector(uint16_t window_size = DETECTOR_DEFAULT_WINDOW_SIZE,
               float threshold = ML_DEFAULT_THRESHOLD,
               uint16_t lag = L1_DELTA_LAG);
    
    ~MLDetector() override;
    
    // Move semantics inherited from BaseDetector
    MLDetector(MLDetector&& other) noexcept;
    MLDetector& operator=(MLDetector&& other) noexcept;
    
    // Disable copy
    MLDetector(const MLDetector&) = delete;
    MLDetector& operator=(const MLDetector&) = delete;
    
    // ========================================================================
    // BaseDetector interface implementation
    // ========================================================================

    void process_packet(const int8_t* csi_data, size_t csi_len,
                        const uint8_t* selected_subcarriers = nullptr,
                        uint8_t num_subcarriers = 0,
                        int8_t rssi_dbm = INT8_MIN) override;
    void update_state() override;
    void clear_buffer() override;
    bool is_ready() const override;
    bool set_threshold(float threshold) override;
    float get_threshold() const override { return threshold_; }
    const char* get_name() const override { return "ML"; }
    void configure_hampel(
        bool enabled,
        uint8_t window_size = HAMPEL_TURBULENCE_WINDOW_DEFAULT,
        float threshold = HAMPEL_TURBULENCE_THRESHOLD_DEFAULT) override;
    void configure_lowpass(
        bool enabled,
        float cutoff_hz = LOWPASS_CUTOFF_DEFAULT) override;

private:
    /**
     * Extract ML features from the turbulence buffer and tracker state
     */
    void extract_features(float* features_out);

    /**
     * L1-delta ring capacity for this window: window_size - lag (0 if window
     * is not larger than the lag). Sized so the series matches Python
     * features.l1_delta_series (window_size profiles -> window_size - lag deltas).
     */
    uint16_t l1_delta_capacity_() const;

    /**
     * Total size of the single feature-scratch block, in floats.
     */
    uint16_t feature_scratch_size_() const;

    /**
     * Slice of the scratch block holding the rebuilt L1-delta series, or
     * nullptr when the model has no L1 features or allocation failed.
     */
    float* delta_series_() const;

    /**
     * Sort and absolute-deviation views onto the scratch block. Empty (and
     * therefore inert) when allocation failed.
     */
    MLSeriesScratch series_scratch_() const;

    void add_aggregated_turbulence_(float turbulence);
    const float* ordered_aggregated_turbulence_(uint16_t& count) const;

    /**
     * Run MLP inference on features.
     *
     * The hidden-layer layout is defined by the auto-generated
     * `ml_weights.h` metadata rather than hardcoded in this class.
     *
     * @param features Feature vector expected by the exported model
     * @return Motion probability (0.0-1.0)
     */
    float predict(const float* features);

    float threshold_;

    // L1-delta profile-displacement state, maintained only when the exported
    // model actually uses L1-delta features (checked against ML_FEATURE_IDS).
    // Mirrors the shared L1-delta tracker rings; keep aligned with the Python
    // features.l1_delta_series reference. The two flags differ for the lag
    // ratio, which needs the rings running but not the rebuilt series.
    bool uses_l1_tracker_;
    bool uses_l1_series_;
    bool uses_shape_tracker_;
    bool uses_coherence_tracker_;
    bool uses_aggregated_turbulence_;
    uint16_t lag_;
    L1DeltaTracker l1_tracker_;
    ChannelShapeTracker shape_tracker_;
    ChannelCoherenceTracker coherence_tracker_;

    // Single heap block backing every feature-path working array, so nothing
    // window-sized lands on the CSI callback stack. Carved by the accessors
    // above; see feature_scratch_size_() for the layout.
    float* feature_scratch_;
    float* aggregated_turbulence_buffer_;
    mutable float* aggregated_turbulence_ordered_;
    uint16_t aggregated_turbulence_index_;
    uint16_t aggregated_turbulence_count_;
    hampel_filter_state_t aggregated_hampel_state_;
    lowpass_filter_state_t aggregated_lowpass_state_;
};

}  // namespace espectre
