#!/usr/bin/env python3
"""
Generate test_app_main.c with symbolic test names
"""

import re
import os
from pathlib import Path

def find_all_tests(test_dir):
    """Find all TEST_CASE_ESP declarations"""
    tests = []
    
    for filename in sorted(os.listdir(test_dir)):
        if filename.startswith('test_') and filename.endswith('.c'):
            filepath = os.path.join(test_dir, filename)
            with open(filepath, 'r') as f:
                content = f.read()
            
            # Find all TEST_CASE_ESP with symbolic names (supports multiple tags)
            pattern = r'TEST_CASE_ESP\(([a-z0-9_]+),\s*"(\[.+?\])"\)'
            
            for match in re.finditer(pattern, content):
                tests.append({
                    'name': match.group(1),
                    'tag': match.group(2),
                    'file': filename
                })
    
    return tests

def generate_main_file(tests):
    """Generate test_app_main.c"""
    
    # Group by file
    by_file = {}
    for test in tests:
        if test['file'] not in by_file:
            by_file[test['file']] = []
        by_file[test['file']].append(test)
    
    # Generate externs
    externs = []
    for filename in sorted(by_file.keys()):
        externs.append(f"// {filename}")
        for test in by_file[filename]:
            externs.append(f"extern test_desc_t test_desc_{test['name']};")
    
    # Generate registrations
    registrations = []
    for test in tests:
        registrations.append(f"    unity_testcase_register(&test_desc_{test['name']});")
    
    content = f'''/*
 * ESPectre - Unit Test Application Main
 * 
 * ⚠️  AUTO-GENERATED FILE
 * Generated by: convert_tests.py
 * 
 * To regenerate: python3 convert_tests.py
 * 
 * Author: Francesco Pace <francesco.pace@gmail.com>
 * License: GPLv3
 */

#include <stdio.h>
#include "unity.h"
#include "unity_test_runner.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

// Test descriptors (using symbolic names)
{chr(10).join(externs)}

void app_main(void)
{{
    printf("\\n");
    printf("╔═════════════════════════════════════╗\\n");
    printf("║       🛜  E S P e c t r e 👻         ║\\n");
    printf("║              Unit Tests             ║\\n");
    printf("╚═════════════════════════════════════╝\\n");
    printf("\\n");
    
    // Register all tests
{chr(10).join(registrations)}
    
    // Run all tests
    printf("Running all tests automatically...\\n\\n");
    unity_run_all_tests();
    
    // Check results
    if (Unity.TestFailures == 0) {{
        printf("\\n✅ All tests passed!\\n");
    }} else {{
        printf("\\n❌ Tests failed: %d failure(s)\\n", Unity.TestFailures);
    }}
    printf("Press Ctrl+] to exit monitor\\n");
    
    // Prevent reboot loop
    while(1) {{
        vTaskDelay(pdMS_TO_TICKS(1000));
    }}
}}
'''
    
    return content

def main():
    script_dir = Path(__file__).parent
    test_dir = script_dir / 'main'
    
    print("Finding all tests...")
    tests = find_all_tests(test_dir)
    print(f"Found {len(tests)} tests:")
    for test in tests:
        print(f"  - {test['name']} ({test['file']})")
    
    print("\nGenerating test_app_main.c...")
    content = generate_main_file(tests)
    
    main_file = test_dir / 'test_app_main.c'
    with open(main_file, 'w') as f:
        f.write(content)
    
    print(f"✅ Generated {main_file}")
    print(f"   Registered {len(tests)} tests")

if __name__ == '__main__':
    main()
