# ESPectre - ESP32 (Original/WROOM-32) Configuration
# WiFi CSI-based motion detection with Home Assistant integration
#
# Made for ESPHome - https://github.com/francescopace/espectre
#
# ⚠️ EXPERIMENTAL: This platform has NOT been tested yet.
# The ESP32 original has CSI support but with different API than S3/C6.
# Please report your results on GitHub Discussions!
#
# Compatible boards:
# - LOLIN D32, D32 Pro
# - ESP-WROOM-32
# - ESP32-DevKitC
# - NodeMCU-32S
# - Any ESP32 (non-S2/S3/C3/C6) board
#
# Provisioning:
# - Via BLE: Use the ESPHome app or Home Assistant companion app
# - Via USB: Use ESPHome web tools (https://web.esphome.io)
# - Via WiFi: Connect to "ESPectre Fallback" AP and configure

esphome:
  name: espectre
  friendly_name: ESPectre
  min_version: 2025.11.0
  # Uncomment the next line if you have multiple ESPectre devices (adds MAC suffix to name)
  # name_add_mac_suffix: true
  project:
    name: francescopace.espectre
    version: "2.2.0"

esp32:
  board: esp32dev
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

# Load ESPectre component from GitHub
external_components:
  - source:
      type: git
      url: https://github.com/francescopace/espectre
      ref: main
    components: [ espectre ]
    refresh: always

# ESPectre - WiFi CSI Motion Detection
espectre:
  id: espectre_csi

# Dashboard import for easy adoption
dashboard_import:
  package_import_url: github://francescopace/espectre/examples/espectre-esp32.yaml@main
  import_full_config: true

# WiFi with fallback AP for provisioning
wifi:
  ap:
    ssid: "ESPectre Fallback"

captive_portal:

# Improv provisioning via BLE
esp32_improv:
  authorizer: none

# Improv provisioning via USB
improv_serial:

# Logging
logger:

# Home Assistant API
api:

# OTA updates
ota:
  - platform: esphome
