# ESPectre - ESP32-S3 Configuration
# WiFi CSI-based motion detection with Home Assistant integration
#
# Made for ESPHome - https://github.com/francescopace/espectre
#
# Tested boards:
# - ESP32-S3-DevKitC-1 (WROOM-1-N16R8)
#
# Provisioning:
# - Via BLE: Use the ESPHome app or Home Assistant companion app
# - Via USB: Use ESPHome web tools (https://web.esphome.io)
# - Via WiFi: Connect to "ESPectre Fallback" AP and configure

esphome:
  name: espectre
  friendly_name: ESPectre
  min_version: 2025.11.0
  # Uncomment the next line if you have multiple ESPectre devices (adds MAC suffix to name)
  # name_add_mac_suffix: true
  project:
    name: francescopace.espectre
    version: "2.2.0"

esp32:
  variant: ESP32S3
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

# PSRAM support (8MB on most S3 boards)
psram:
  mode: octal
  speed: 80MHz

# ESPectre - WiFi CSI Motion Detection

# Dashboard import for easy adoption
dashboard_import:
  package_import_url: github://francescopace/espectre/examples/espectre-s3.yaml@main
  import_full_config: true

# WiFi with fallback AP for provisioning
wifi:
  ap:
    ssid: "ESPectre Fallback"

captive_portal:

# Improv provisioning via BLE
esp32_improv:
  authorizer: none

# Improv provisioning via USB
improv_serial:

# Logging
logger:

# Home Assistant API
api:

# OTA updates
ota:
  - platform: esphome
  
# Enable the web server for the dashboard
web_server:
  port: 80

## LED on Board

# Load ESPectre component from GitHub
external_components:
  - source:
      type: git
      url: https://github.com/francescopace/espectre
      ref: main
    components: [ espectre ]
    refresh: always

# Define the Onboard Light
light:
  - platform: esp32_rmt_led_strip
    id: onboard_led
    name: "Onboard Light"
    pin: GPIO48
    num_leds: 1
    rgb_order: GRB
    chipset: ws2812

# Configure the ESPectre Component
espectre:
  id: espectre_csi
  motion_sensor:
    name: "Motion Detected"
    # Triggers for the LED go HERE
    on_press:
      then:
        - light.turn_on:
            id: onboard_led
            brightness: 20%
            red: 100%
            green: 0%
            blue: 0%
    on_release:
      then:
        - light.turn_on:
            id: onboard_led
            brightness: 20%
            red: 0%
            green: 100%
            blue: 0%
  
  # This configures the movement score number
  movement_sensor:
    name: "Movement Score"
