# ESPectre - ESP32-C6 Configuration
# WiFi CSI-based motion detection with Home Assistant integration
#
# Made for ESPHome - https://github.com/francescopace/espectre
#
# Tested boards:
# - Waveshare ESP32-C6-DEV (WROOM-1-N8)
#
# Provisioning:
# - Via BLE: Use the ESPHome app or Home Assistant companion app
# - Via USB: Use ESPHome web tools (https://web.esphome.io)
# - Via WiFi: Connect to "ESPectre Fallback" AP and configure

substitutions:
  git_ref: main # branch, tag, or commit
  detection_algorithm: mvs # mvs (default) or ml

esphome:
  name: espectre
  friendly_name: ESPectre
  min_version: 2025.11.0
  # Uncomment the next line if you have multiple ESPectre devices (adds MAC suffix to name)
  # name_add_mac_suffix: true
  project:
    name: francescopace.espectre
    version: ${git_ref}

esp32:
  variant: ESP32C6
  framework:
    type: esp-idf

# Load ESPectre component from GitHub
external_components:
  - source:
      type: git
      url: https://github.com/francescopace/espectre
      ref: ${git_ref}
    components: [ espectre ]
    refresh: always

# ESPectre - WiFi CSI Motion Detection
espectre:
  id: espectre_csi
  detection_algorithm: ${detection_algorithm}

# Dashboard import for easy adoption
dashboard_import:
  package_import_url: github://francescopace/espectre/examples/espectre-c6.yaml@${git_ref}
  import_full_config: true

# WiFi with fallback AP for provisioning
wifi:
  ap:
    ssid: "ESPectre Fallback"

captive_portal:

# Improv provisioning via BLE
esp32_improv:
  authorizer: none

# Improv provisioning via USB
improv_serial:

# Logging
logger:

# Home Assistant API
api:

# OTA updates
ota:
  - platform: esphome
