# SPDX-License-Identifier: GPL-3.0-only
# Commercial licensing available under separate agreement; see LICENSING.md.
"""
Micro-ESPectre - High-Accuracy Motion Detector

Neural network-based motion detector implementing the IDetector interface.
Uses pre-trained weights from ml_weights.py (auto-generated by training script).

Usage:
    from high_accuracy_detector import HighAccuracyDetector
    
    detector = HighAccuracyDetector()
    detector.process_packet(csi_data, subcarriers)
    metrics = detector.update_state()

Author: Francesco Pace <francesco.pace@gmail.com>
"""
import math
import struct
import sys

try:
    from src.detector_interface import IDetector, MotionState
    from src.segmentation import SegmentationContext
    from src.csi_features import (
        CHANNEL_SHAPE_TRAJECTORY_FEATURES,
        AGGREGATED_TURBULENCE_FEATURES,
        L1_DELTA_LAG, L1_TRACKER_FEATURES,
        TURB_IQR_AGGREGATION_WIDTH, L1DeltaTracker, extract_features_by_name,
    )
    from src.ml_feature_trackers import ChannelShapeTrajectoryTracker
    from src.config import DEFAULT_SUBCARRIERS
except ImportError:
    from detector_interface import IDetector, MotionState
    from segmentation import SegmentationContext
    from csi_features import (
        CHANNEL_SHAPE_TRAJECTORY_FEATURES,
        AGGREGATED_TURBULENCE_FEATURES,
        L1_DELTA_LAG, L1_TRACKER_FEATURES,
        TURB_IQR_AGGREGATION_WIDTH, L1DeltaTracker, extract_features_by_name,
    )
    from ml_feature_trackers import ChannelShapeTrajectoryTracker
    from config import DEFAULT_SUBCARRIERS

try:
    from src import ml_weights as _ml_weights
except ImportError:
    import ml_weights as _ml_weights

FEATURE_MEAN = _ml_weights.FEATURE_MEAN
FEATURE_SCALE = _ml_weights.FEATURE_SCALE
BIASES = _ml_weights.BIASES
FEATURE_NAMES = _ml_weights.FEATURE_NAMES

# Re-export for convenience
__all__ = ['HighAccuracyDetector', 'predict', 'is_motion', 'DEFAULT_SUBCARRIERS', 'FEATURE_NAMES']

# High-Accuracy profile constants (direct 0-1 probability scale)
HIGH_ACCURACY_DEFAULT_THRESHOLD = 0.5
HIGH_ACCURACY_MIN_THRESHOLD = 0.0
HIGH_ACCURACY_MAX_THRESHOLD = 1.0
HIGH_ACCURACY_METRIC_SCALE = 1.0

# Firmware inference accumulates IEEE-754 binary32. CPython follows that
# rounding so report replay can match the host C++ detector. MicroPython keeps
# native floats; the device path is not the Python/C++ report gate.
_USE_IEEE_FLOAT32 = sys.implementation.name != "micropython"


def _f32(value):
    """Return ``value`` rounded the way firmware ``float`` arithmetic rounds."""
    if not _USE_IEEE_FLOAT32:
        return float(value)
    return struct.unpack("f", struct.pack("f", float(value)))[0]

# New exports are already [output][input]. Retain a compatibility path for
# older deployed weight modules so over-the-air module updates remain safe.
_WEIGHTS_T = getattr(_ml_weights, "WEIGHTS_T", None)
if _WEIGHTS_T is None:
    _legacy_weights = _ml_weights.WEIGHTS
    _WEIGHTS_T = []
    for _lw in _legacy_weights:
        _n_in = len(_lw)
        _n_out = len(_lw[0])
        _WEIGHTS_T.append(
            [[_lw[i][j] for i in range(_n_in)] for j in range(_n_out)]
        )
    del _legacy_weights, _lw, _n_in, _n_out
del _ml_weights

# ============================================================================
# Neural Network Inference Functions
# ============================================================================

def relu(x):
    """ReLU activation function."""
    return x if x > 0 else 0.0


def sigmoid(x):
    """Sigmoid activation function with overflow protection."""
    value = _f32(x)
    if value < -20:
        return 0.0
    if value > 20:
        return 1.0
    return _f32(1.0 / _f32(1.0 + math.exp(-value)))


def predict(features):
    """
    Predict motion probability from the exported feature vector.
    
    Args:
        features: Ordered feature vector expected by the exported model
    
    Returns:
        float: Motion probability (0.0 to 1.0)
    """
    workspace_size = max(
        len(FEATURE_MEAN),
        max(len(layer_biases) for layer_biases in BIASES),
    )
    return _predict_with_workspace(
        features,
        [0.0] * workspace_size,
        [0.0] * workspace_size,
    )


def _predict_with_workspace(features, activation_a, activation_b):
    """Run inference using two reusable activation buffers."""
    n_feat = len(features)
    if len(activation_a) < n_feat or len(activation_b) < n_feat:
        raise ValueError("Activation workspace is too small")
    for i in range(n_feat):
        activation_a[i] = _f32(
            _f32(features[i] - FEATURE_MEAN[i]) / FEATURE_SCALE[i]
        )

    activations = activation_a
    next_activations = activation_b
    n_active = n_feat
    n_layers = len(_WEIGHTS_T)
    for layer_idx in range(n_layers):
        weights_t = _WEIGHTS_T[layer_idx]
        biases = BIASES[layer_idx]
        n_out = len(biases)
        if len(next_activations) < n_out:
            raise ValueError("Activation workspace is too small")
        is_last = layer_idx == n_layers - 1
        for j in range(n_out):
            val = _f32(biases[j])
            w_row = weights_t[j]
            for i in range(n_active):
                val = _f32(val + _f32(_f32(activations[i]) * _f32(w_row[i])))
            next_activations[j] = val if is_last else (val if val > 0 else 0.0)
        activations, next_activations = next_activations, activations
        n_active = n_out

    return sigmoid(_f32(activations[0])) * HIGH_ACCURACY_METRIC_SCALE


def is_motion(features, threshold=HIGH_ACCURACY_DEFAULT_THRESHOLD):
    """
    Detect motion from features.
    
    Args:
        features: Ordered feature vector expected by the exported model
        threshold: Detection threshold (default: 0.5)
    
    Returns:
        bool: True if motion detected
    """
    return predict(features) > threshold


# ============================================================================
# HighAccuracyDetector Class
# ============================================================================


class HighAccuracyDetector(IDetector):
    """
    Neural Network-based motion detector.
    
    Uses a pre-trained MLP exported by the training pipeline to classify
    motion based on turbulence features extracted from CSI data.
    
    Algorithm:
    1. Calculate gain-invariant spatial turbulence (std/mean)
    2. Store in circular buffer (window_size packets)
    3. Extract the configured ML feature vector from buffer
    4. Run neural network inference
    5. Compare probability to threshold for state decision
    """
    ALGORITHM = "high_accuracy"
    
    def __init__(self, window_size=100, threshold=HIGH_ACCURACY_DEFAULT_THRESHOLD,
                 enable_lowpass=False, lowpass_cutoff=11.0,
                 enable_hampel=True, hampel_window=7, hampel_threshold=5.0,
                 **kwargs):
        """
        Initialize the High-Accuracy detector.
        
        Args:
            window_size: Feature extraction window size (default: 100, matches C++ DETECTOR_DEFAULT_WINDOW_SIZE)
            threshold: Motion detection threshold (default: 0.5, range 0.0-1.0)
            enable_lowpass: Enable low-pass filter (default: False)
            lowpass_cutoff: Low-pass cutoff frequency Hz (default: 11.0)
            enable_hampel: Enable Hampel filter (default: True)
            hampel_window: Hampel window size (default: 7)
            hampel_threshold: Hampel threshold in MAD (default: 5.0)
        """
        # Use SegmentationContext for turbulence calculation and filtering
        self._context = SegmentationContext(
            window_size=window_size,
            enable_lowpass=enable_lowpass,
            lowpass_cutoff=lowpass_cutoff,
            enable_hampel=enable_hampel,
            hampel_window=hampel_window,
            hampel_threshold=hampel_threshold
        )
        self._threshold = threshold
        self._packet_count = 0
        self._motion_count = 0
        self._state = MotionState.IDLE
        self._current_probability = 0.0
        # The lag ratio needs the profile rings, but no rebuilt delta series.
        self._use_amplitude_history = any(
            name in L1_TRACKER_FEATURES for name in FEATURE_NAMES
        )
        self._use_shape_trajectory_tracker = any(
            name in CHANNEL_SHAPE_TRAJECTORY_FEATURES for name in FEATURE_NAMES
        )
        self._use_aggregated_turbulence = any(
            name in AGGREGATED_TURBULENCE_FEATURES for name in FEATURE_NAMES
        )
        self._aggregated_context = (
            SegmentationContext(
                window_size=window_size,
                enable_lowpass=enable_lowpass,
                lowpass_cutoff=lowpass_cutoff,
                enable_hampel=enable_hampel,
                hampel_window=hampel_window,
                hampel_threshold=hampel_threshold,
                adjacent_aggregation_width=TURB_IQR_AGGREGATION_WIDTH,
            )
            if self._use_aggregated_turbulence else None
        )
        delta_window = max(2, window_size - L1_DELTA_LAG)
        if self._use_amplitude_history:
            self._l1_tracker = L1DeltaTracker(
                window_size=delta_window,
                lag=L1_DELTA_LAG,
                allocate_amplitude_buffer=False,
                enable_hampel=enable_hampel,
                hampel_window=hampel_window,
                hampel_threshold=hampel_threshold,
            )
        else:
            self._l1_tracker = None
        self._shape_trajectory_tracker = (
            ChannelShapeTrajectoryTracker()
            if self._use_shape_trajectory_tracker else None
        )
        self._ordered_turbulence = [0.0] * window_size
        self._ordered_turbulence_validity = [False] * window_size
        self._ordered_aggregated_turbulence = (
            [0.0] * window_size if self._use_aggregated_turbulence else None
        )
        self._ordered_aggregated_validity = (
            [False] * window_size if self._use_aggregated_turbulence else None
        )
        self._minimum_valid_samples = window_size
        self._series_sort_scratch = (
            self._ordered_aggregated_turbulence
            if self._ordered_aggregated_turbulence is not None
            else ([0.0] * window_size if "turb_zcr" in FEATURE_NAMES else None)
        )
        self._feature_buffer = [0.0] * len(FEATURE_NAMES)
        # Production windows already exceed one HT20 frame. Packet extraction
        # and chronological ordering never overlap, so they share that scratch.
        self._packet_subcarrier_values = (
            self._ordered_turbulence
            if window_size >= 64
            else [0.0] * 64
        )
        workspace_size = max(
            len(FEATURE_MEAN),
            max(len(layer_biases) for layer_biases in BIASES),
        )
        self._activation_a = [0.0] * workspace_size
        self._activation_b = [0.0] * workspace_size
        
        # For tracking (optional)
        self.probability_history = []
        self.state_history = []
        self.track_data = False
    
    def process_packet(self, csi_data, selected_subcarriers=None, rssi_dbm=None,
                       timestamp_us=None):
        """
        Process a CSI packet.
        
        Args:
            csi_data: Raw CSI data (int8 I/Q pairs)
            selected_subcarriers: Subcarrier indices to use
            rssi_dbm: Optional per-packet RSSI metadata (ignored by ML)
            timestamp_us: Optional monotonic packet timestamp in microseconds
        """
        self._packet_count += 1
        if selected_subcarriers is None:
            selected_subcarriers = DEFAULT_SUBCARRIERS

        packet_values = self._packet_subcarrier_values
        packet_value_count = SegmentationContext.fill_subcarrier_energy_buffer(
            csi_data,
            packet_values,
        )
        if self._shape_trajectory_tracker is not None:
            self._shape_trajectory_tracker.process_packet(
                csi_data,
                timestamp_us,
                packet_values,
                packet_value_count,
            )
        SegmentationContext.energies_to_amplitudes_in_place(
            packet_values,
            packet_value_count,
        )

        turbulence = (
            self._context.calculate_spatial_turbulence_from_subcarrier_amplitudes(
                packet_values,
                packet_value_count,
                selected_subcarriers,
            )
        )
        if self._use_amplitude_history:
            self._l1_tracker.process_amplitudes(
                self._context._amplitude_buffer,
                self._context._amplitude_count,
                self._context._amplitude_mean,
            )
        # Add to buffer
        self._context.add_turbulence(turbulence)
        if self._aggregated_context is not None:
            aggregated_turbulence = (
                self._aggregated_context.calculate_spatial_turbulence_from_subcarrier_amplitudes(
                    packet_values,
                    packet_value_count,
                    selected_subcarriers,
                )
            )
            self._aggregated_context.add_turbulence(aggregated_turbulence)

    def advance_missing_slots(self, count):
        """Preserve absent slots in every packet-indexed feature stream."""
        missing = max(0, int(count))
        for _ in range(missing):
            self._context.add_missing_slot()
            if self._aggregated_context is not None:
                self._aggregated_context.add_missing_slot()
        if self._l1_tracker is not None:
            self._l1_tracker.advance_missing_slots(missing)

    def set_minimum_valid_samples(self, count):
        self._minimum_valid_samples = max(1, min(int(count), self._context.window_size))
    
    def update_state(self):
        """
        Run inference and update state.
        
        Returns:
            dict: Current metrics including state and probability
        """
        if not self.is_ready():
            return {
                'state': self._state,
                'motion_metric': 0.0,
                'probability': 0.0,
                'threshold': self._threshold
            }
        
        # Extract features from turbulence buffer
        features = self._extract_features()
        
        # Run neural network
        self._current_probability = _predict_with_workspace(
            features,
            self._activation_a,
            self._activation_b,
        )
        
        # Update state
        if self._current_probability > self._threshold:
            self._state = MotionState.MOTION
        else:
            self._state = MotionState.IDLE
        
        if self.track_data:
            self.probability_history.append(self._current_probability)
            state_str = 'MOTION' if self._state == MotionState.MOTION else 'IDLE'
            self.state_history.append(state_str)
            if self._state == MotionState.MOTION:
                self._motion_count += 1
        
        return {
            'state': self._state,
            'motion_metric': self._current_probability,
            'probability': self._current_probability,
            'threshold': self._threshold
        }
    
    def _extract_features(self):
        """
        Extract the configured feature vector from turbulence buffer.
        
        IMPORTANT: The turbulence_buffer is a circular buffer. After wrap-around,
        a simple slice [:buffer_count] would NOT be in chronological order.
        Features like slope, delta, zcr, and autocorr depend on temporal order.
        
        We reconstruct the chronological order: [oldest ... newest]
        """
        ctx = self._context
        
        # Build chronological list from circular buffer
        turb_list = self._ordered_turbulence
        turb_validity = self._ordered_turbulence_validity
        count = ctx.buffer_count
        if count < ctx.window_size:
            for i in range(count):
                turb_list[i] = ctx.turbulence_buffer[i]
                turb_validity[i] = ctx.validity_buffer[i]
        else:
            idx = ctx.buffer_index
            tail = count - idx
            for i in range(tail):
                turb_list[i] = ctx.turbulence_buffer[idx + i]
                turb_validity[i] = ctx.validity_buffer[idx + i]
            for i in range(idx):
                turb_list[tail + i] = ctx.turbulence_buffer[i]
                turb_validity[tail + i] = ctx.validity_buffer[i]

        aggregated_count = 0
        aggregated_turbulence = None
        if self._aggregated_context is not None:
            aggregated_ctx = self._aggregated_context
            aggregated_turbulence = self._ordered_aggregated_turbulence
            aggregated_validity = self._ordered_aggregated_validity
            aggregated_count = aggregated_ctx.buffer_count
            if aggregated_count < aggregated_ctx.window_size:
                for i in range(aggregated_count):
                    aggregated_turbulence[i] = (
                        aggregated_ctx.turbulence_buffer[i]
                    )
                    aggregated_validity[i] = aggregated_ctx.validity_buffer[i]
            else:
                aggregated_idx = aggregated_ctx.buffer_index
                aggregated_tail = aggregated_count - aggregated_idx
                for i in range(aggregated_tail):
                    aggregated_turbulence[i] = (
                        aggregated_ctx.turbulence_buffer[aggregated_idx + i]
                    )
                    aggregated_validity[i] = (
                        aggregated_ctx.validity_buffer[aggregated_idx + i]
                    )
                for i in range(aggregated_idx):
                    aggregated_turbulence[aggregated_tail + i] = (
                        aggregated_ctx.turbulence_buffer[i]
                    )
                    aggregated_validity[aggregated_tail + i] = (
                        aggregated_ctx.validity_buffer[i]
                    )
        trajectory_innovation = None
        trajectory_excess = None
        trajectory_spread = None
        trajectory_kendall = None
        if self._shape_trajectory_tracker is not None:
            trajectory_innovation, trajectory_excess, trajectory_spread = (
                self._shape_trajectory_tracker.trajectory_features_with_spread()
            )
            trajectory_kendall = (
                self._shape_trajectory_tracker.subband_kendall_lag_excess()
            )
        return extract_features_by_name(
            turb_list, count,
            feature_names=FEATURE_NAMES,
            aggregated_turbulence_buffer=aggregated_turbulence,
            aggregated_turbulence_count=aggregated_count,
            sort_scratch=self._series_sort_scratch,
            l1_delta_lag_ratio=(
                self._l1_tracker.delta_lag_ratio()
                if (
                    self._l1_tracker is not None
                    and "l1_delta_lag_ratio" in FEATURE_NAMES
                )
                else None
            ),
            chan_shape_spread_subband=(
                trajectory_spread
                if "chan_shape_spread_subband" in FEATURE_NAMES
                else None
            ),
            chan_shape_coherent_innovation_energy=(
                trajectory_innovation
                if "chan_shape_coherent_innovation_energy" in FEATURE_NAMES
                else None
            ),
            chan_shape_excess_path=(
                trajectory_excess
                if "chan_shape_excess_path" in FEATURE_NAMES
                else None
            ),
            chan_shape_subband_kendall_lag_excess=(
                trajectory_kendall
                if "chan_shape_subband_kendall_lag_excess" in FEATURE_NAMES
                else None
            ),
            out=self._feature_buffer,
            reuse_aggregated_turbulence_buffer=True,
            turbulence_validity=turb_validity,
            aggregated_turbulence_validity=(
                aggregated_validity
                if self._aggregated_context is not None
                else None
            ),
        )
    
    def get_state(self):
        """Get current motion state."""
        return self._state
    
    def get_motion_metric(self):
        """Get current motion probability."""
        return self._current_probability
    
    def get_threshold(self):
        """Get current probability threshold."""
        return self._threshold
    
    def set_threshold(self, threshold):
        """Set threshold (range 0.0-1.0 on the ML probability scale)."""
        if HIGH_ACCURACY_MIN_THRESHOLD <= threshold <= HIGH_ACCURACY_MAX_THRESHOLD:
            self._threshold = threshold
            return True
        return False

    def is_ready(self):
        """Check if buffer is full."""
        if self._context.buffer_count < self._context.window_size:
            return False
        if self._context.valid_count < self._minimum_valid_samples:
            return False
        if (
            self._l1_tracker is not None
            and self._context.window_size > L1_DELTA_LAG
            and self._l1_tracker.count == 0
        ):
            return False
        if (
            self._aggregated_context is not None
            and self._aggregated_context.buffer_count
            < self._aggregated_context.window_size
        ):
            return False
        if (
            self._aggregated_context is not None
            and self._aggregated_context.valid_count < self._minimum_valid_samples
        ):
            return False
        return True
    
    def reset(self):
        """Reset detector state."""
        self._context.reset(full=True)
        self._packet_count = 0
        self._state = MotionState.IDLE
        self._current_probability = 0.0
        self._motion_count = 0
        if self._l1_tracker is not None:
            self._l1_tracker.reset()
        if self._shape_trajectory_tracker is not None:
            self._shape_trajectory_tracker.reset()
        if self._aggregated_context is not None:
            self._aggregated_context.reset(full=True)
        self.probability_history = []
        self.state_history = []
    
    def get_name(self):
        """Get detector name."""
        return "High Accuracy"

    def get_window_size(self):
        """Return the resolved detector window in samples."""
        return self._context.window_size
    
    @property
    def total_packets(self):
        """Total packets processed."""
        return self._packet_count
    
    def get_motion_count(self):
        """Get number of motion detections (for tracking)."""
        return self._motion_count
