"""
Micro-ESPectre - ML Motion Detector

Neural network-based motion detector implementing the IDetector interface.
Uses pre-trained weights from ml_weights.py (auto-generated by training script).

Usage:
    from ml_detector import MLDetector
    
    detector = MLDetector()
    detector.process_packet(csi_data, subcarriers)
    metrics = detector.update_state()

Author: Francesco Pace <francesco.pace@gmail.com>
License: GPLv3
"""
import math

try:
    from src.detector_interface import IDetector, MotionState
    from src.segmentation import SegmentationContext
    from src.csi_features import (
        CHANNEL_COHERENCE_FEATURES, CHANNEL_SHAPE_FEATURES,
        L1_DELTA_LAG, L1_SERIES_FEATURES, L1_TRACKER_FEATURES,
        L1DeltaTracker, extract_features_by_name,
    )
    from src.ml_feature_trackers import ChannelCoherenceTracker, ChannelShapeTracker
    from src.config import DEFAULT_SUBCARRIERS
except ImportError:
    from detector_interface import IDetector, MotionState
    from segmentation import SegmentationContext
    from csi_features import (
        CHANNEL_COHERENCE_FEATURES, CHANNEL_SHAPE_FEATURES,
        L1_DELTA_LAG, L1_SERIES_FEATURES, L1_TRACKER_FEATURES,
        L1DeltaTracker, extract_features_by_name,
    )
    from ml_feature_trackers import ChannelCoherenceTracker, ChannelShapeTracker
    from config import DEFAULT_SUBCARRIERS

try:
    from src.ml_weights import (
        FEATURE_MEAN, FEATURE_SCALE,
        WEIGHTS, BIASES, FEATURE_NAMES,
    )
except ImportError:
    from ml_weights import (
        FEATURE_MEAN, FEATURE_SCALE,
        WEIGHTS, BIASES, FEATURE_NAMES,
    )

# Re-export for convenience
__all__ = ['MLDetector', 'predict', 'is_motion', 'DEFAULT_SUBCARRIERS', 'FEATURE_NAMES']

# ML-specific constants (direct 0-1 probability scale)
ML_DEFAULT_THRESHOLD = 0.5
ML_MIN_THRESHOLD = 0.0
ML_MAX_THRESHOLD = 1.0
ML_METRIC_SCALE = 1.0

# Transpose weight matrices at load time: [input][output] → [output][input].
# This makes the inner multiply-add loop access weights[j] once per output
# neuron instead of weights[i][j] (2 lookups) per multiply-add.
_WEIGHTS_T = []
for _lw in WEIGHTS:
    _n_in = len(_lw)
    _n_out = len(_lw[0])
    _WEIGHTS_T.append([[_lw[i][j] for i in range(_n_in)] for j in range(_n_out)])
del _lw, _n_in, _n_out

# On MicroPython the generated source matrix is no longer needed after the
# transposed runtime layout has been built. Clearing it releases its nested
# list containers while keeping CPython analysis/test imports unchanged.
try:
    import sys
    if sys.implementation.name == "micropython":
        WEIGHTS.clear()
except (AttributeError, ImportError):
    pass
del WEIGHTS

# ============================================================================
# Neural Network Inference Functions
# ============================================================================

def relu(x):
    """ReLU activation function."""
    return x if x > 0 else 0.0


def sigmoid(x):
    """Sigmoid activation function with overflow protection."""
    if x < -20:
        return 0.0
    if x > 20:
        return 1.0
    return 1.0 / (1.0 + math.exp(-x))


def predict(features):
    """
    Predict motion probability from the exported feature vector.
    
    Args:
        features: Ordered feature vector expected by the exported model
    
    Returns:
        float: Motion probability (0.0 to 1.0)
    """
    workspace_size = max(
        len(FEATURE_MEAN),
        max(len(layer_biases) for layer_biases in BIASES),
    )
    return _predict_with_workspace(
        features,
        [0.0] * workspace_size,
        [0.0] * workspace_size,
    )


def _predict_with_workspace(features, activation_a, activation_b):
    """Run inference using two reusable activation buffers."""
    n_feat = len(features)
    if len(activation_a) < n_feat or len(activation_b) < n_feat:
        raise ValueError("Activation workspace is too small")
    for i in range(n_feat):
        activation_a[i] = (features[i] - FEATURE_MEAN[i]) / FEATURE_SCALE[i]

    activations = activation_a
    next_activations = activation_b
    n_active = n_feat
    n_layers = len(_WEIGHTS_T)
    for layer_idx in range(n_layers):
        weights_t = _WEIGHTS_T[layer_idx]
        biases = BIASES[layer_idx]
        n_out = len(biases)
        if len(next_activations) < n_out:
            raise ValueError("Activation workspace is too small")
        is_last = layer_idx == n_layers - 1
        for j in range(n_out):
            val = biases[j]
            w_row = weights_t[j]
            for i in range(n_active):
                val += activations[i] * w_row[i]
            next_activations[j] = val if is_last else (val if val > 0 else 0.0)
        activations, next_activations = next_activations, activations
        n_active = n_out

    return sigmoid(activations[0]) * ML_METRIC_SCALE


def is_motion(features, threshold=ML_DEFAULT_THRESHOLD):
    """
    Detect motion from features.
    
    Args:
        features: Ordered feature vector expected by the exported model
        threshold: Detection threshold (default: 0.5)
    
    Returns:
        bool: True if motion detected
    """
    return predict(features) > threshold


# ============================================================================
# MLDetector Class
# ============================================================================


class MLDetector(IDetector):
    """
    Neural Network-based motion detector.
    
    Uses a pre-trained MLP exported by the training pipeline to classify
    motion based on turbulence features extracted from CSI data.
    
    Algorithm:
    1. Calculate gain-invariant spatial turbulence (std/mean)
    2. Store in circular buffer (window_size packets)
    3. Extract the configured ML feature vector from buffer
    4. Run neural network inference
    5. Compare probability to threshold for state decision
    """
    ALGORITHM = "ml"
    
    def __init__(self, window_size=100, threshold=ML_DEFAULT_THRESHOLD,
                 enable_lowpass=False, lowpass_cutoff=11.0,
                 enable_hampel=True, hampel_window=7, hampel_threshold=5.0,
                 **kwargs):
        """
        Initialize ML detector.
        
        Args:
            window_size: Feature extraction window size (default: 100, matches C++ DETECTOR_DEFAULT_WINDOW_SIZE)
            threshold: Motion detection threshold (default: 0.5, range 0.0-1.0)
            enable_lowpass: Enable low-pass filter (default: False)
            lowpass_cutoff: Low-pass cutoff frequency Hz (default: 11.0)
            enable_hampel: Enable Hampel filter (default: True)
            hampel_window: Hampel window size (default: 7)
            hampel_threshold: Hampel threshold in MAD (default: 5.0)
        """
        # Use SegmentationContext for turbulence calculation and filtering
        self._context = SegmentationContext(
            window_size=window_size,
            enable_lowpass=enable_lowpass,
            lowpass_cutoff=lowpass_cutoff,
            enable_hampel=enable_hampel,
            hampel_window=hampel_window,
            hampel_threshold=hampel_threshold
        )
        self._threshold = threshold
        self._packet_count = 0
        self._motion_count = 0
        self._state = MotionState.IDLE
        self._current_probability = 0.0
        # The lag ratio needs the tracker but not the rebuilt series, so the
        # two questions are asked separately; mirrors MLDetector in C++.
        self._use_amplitude_history = any(
            name in L1_TRACKER_FEATURES for name in FEATURE_NAMES
        )
        self._use_l1_series = any(
            name in L1_SERIES_FEATURES for name in FEATURE_NAMES
        )
        self._use_shape_tracker = any(
            name in CHANNEL_SHAPE_FEATURES for name in FEATURE_NAMES
        )
        self._use_coherence_tracker = any(
            name in CHANNEL_COHERENCE_FEATURES for name in FEATURE_NAMES
        )
        delta_window = max(2, window_size - L1_DELTA_LAG)
        if self._use_amplitude_history:
            self._l1_tracker = L1DeltaTracker(
                window_size=delta_window,
                lag=L1_DELTA_LAG,
                allocate_amplitude_buffer=False,
                enable_hampel=enable_hampel,
                hampel_window=hampel_window,
                hampel_threshold=hampel_threshold,
            )
            self._l1_series_buffer = (
                [0.0] * delta_window if self._use_l1_series else None
            )
        else:
            self._l1_tracker = None
            self._l1_series_buffer = None
        self._shape_tracker = (
            ChannelShapeTracker(window_size=delta_window, lag=L1_DELTA_LAG)
            if self._use_shape_tracker else None
        )
        self._coherence_tracker = (
            ChannelCoherenceTracker(window_size=delta_window, lag=L1_DELTA_LAG)
            if self._use_coherence_tracker else None
        )
        self._ordered_turbulence = [0.0] * window_size
        self._feature_buffer = [0.0] * len(FEATURE_NAMES)
        workspace_size = max(
            len(FEATURE_MEAN),
            max(len(layer_biases) for layer_biases in BIASES),
        )
        self._activation_a = [0.0] * workspace_size
        self._activation_b = [0.0] * workspace_size
        
        # For tracking (optional)
        self.probability_history = []
        self.state_history = []
        self.track_data = False
    
    def process_packet(self, csi_data, selected_subcarriers=None, rssi_dbm=None):
        """
        Process a CSI packet.
        
        Args:
            csi_data: Raw CSI data (int8 I/Q pairs)
            selected_subcarriers: Subcarrier indices to use
            rssi_dbm: Optional per-packet RSSI metadata (ignored by ML)
        """
        self._packet_count += 1

        if self._use_amplitude_history:
            turbulence = self._context.calculate_spatial_turbulence(
                csi_data, selected_subcarriers
            )
            self._l1_tracker.process_amplitudes(
                self._context._amplitude_buffer,
                self._context._amplitude_count,
            )
        else:
            # Fast path for the default exported models: only the turbulence window is needed.
            turbulence = self._context.calculate_spatial_turbulence(
                csi_data, selected_subcarriers
            )
        if self._shape_tracker is not None:
            self._shape_tracker.process_packet(csi_data)
        if self._coherence_tracker is not None:
            self._coherence_tracker.process_packet(csi_data)

        # Add to buffer
        self._context.add_turbulence(turbulence)
    
    def update_state(self):
        """
        Run inference and update state.
        
        Returns:
            dict: Current metrics including state and probability
        """
        if not self.is_ready():
            return {
                'state': self._state,
                'motion_metric': 0.0,
                'probability': 0.0,
                'threshold': self._threshold
            }
        
        # Extract features from turbulence buffer
        features = self._extract_features()
        
        # Run neural network
        self._current_probability = _predict_with_workspace(
            features,
            self._activation_a,
            self._activation_b,
        )
        
        # Update state
        if self._current_probability > self._threshold:
            self._state = MotionState.MOTION
        else:
            self._state = MotionState.IDLE
        
        if self.track_data:
            self.probability_history.append(self._current_probability)
            state_str = 'MOTION' if self._state == MotionState.MOTION else 'IDLE'
            self.state_history.append(state_str)
            if self._state == MotionState.MOTION:
                self._motion_count += 1
        
        return {
            'state': self._state,
            'motion_metric': self._current_probability,
            'probability': self._current_probability,
            'threshold': self._threshold
        }
    
    def _extract_features(self):
        """
        Extract the configured feature vector from turbulence buffer.
        
        IMPORTANT: The turbulence_buffer is a circular buffer. After wrap-around,
        a simple slice [:buffer_count] would NOT be in chronological order.
        Features like slope, delta, zcr, and autocorr depend on temporal order.
        
        We reconstruct the chronological order: [oldest ... newest]
        """
        ctx = self._context
        
        # Build chronological list from circular buffer
        turb_list = self._ordered_turbulence
        count = ctx.buffer_count
        if count < ctx.window_size:
            for i in range(count):
                turb_list[i] = ctx.turbulence_buffer[i]
        else:
            idx = ctx.buffer_index
            for i in range(count):
                turb_list[i] = ctx.turbulence_buffer[(idx + i) % count]

        l1_count = 0
        if self._l1_series_buffer is not None:
            l1_count = self._l1_tracker.copy_deltas_into(self._l1_series_buffer)
        return extract_features_by_name(
            turb_list, count,
            feature_names=FEATURE_NAMES,
            l1_series=self._l1_series_buffer,
            l1_series_count=l1_count,
            l1_delta_lag_ratio=(
                self._l1_tracker.delta_lag_ratio()
                if (
                    self._l1_tracker is not None
                    and "l1_delta_lag_ratio" in FEATURE_NAMES
                )
                else None
            ),
            chan_shape_spread=(
                self._shape_tracker.shape_spread()
                if self._shape_tracker is not None
                and "chan_shape_spread" in FEATURE_NAMES
                else None
            ),
            chan_freq_coh_cv=(
                self._shape_tracker.frequency_coherence_cv()
                if self._shape_tracker is not None
                and "chan_freq_coh_cv" in FEATURE_NAMES
                else None
            ),
            chan_freq_coh_curve_std=(
                self._shape_tracker.frequency_coherence_curve_std()
                if self._shape_tracker is not None
                and "chan_freq_coh_curve_std" in FEATURE_NAMES
                else None
            ),
            chan_coh_gap=(
                self._coherence_tracker.coherence_gap()
                if self._coherence_tracker is not None
                and "chan_coh_gap" in FEATURE_NAMES
                else None
            ),
            chan_coh_subband_gap_median=(
                self._coherence_tracker.coherence_subband_gap_median()
                if self._coherence_tracker is not None
                and "chan_coh_subband_gap_median" in FEATURE_NAMES
                else None
            ),
            out=self._feature_buffer,
            reuse_turbulence_buffer=True,
        )
    
    def get_state(self):
        """Get current motion state."""
        return self._state
    
    def get_motion_metric(self):
        """Get current motion probability."""
        return self._current_probability
    
    def get_threshold(self):
        """Get current probability threshold."""
        return self._threshold
    
    def set_threshold(self, threshold):
        """Set threshold (range 0.0-1.0 on the ML probability scale)."""
        if ML_MIN_THRESHOLD <= threshold <= ML_MAX_THRESHOLD:
            self._threshold = threshold
            return True
        return False

    def is_ready(self):
        """Check if buffer is full."""
        if self._context.buffer_count < self._context.window_size:
            return False
        if self._l1_tracker is not None and self._l1_tracker.count < (self._context.window_size - L1_DELTA_LAG):
            return False
        if self._shape_tracker is not None and self._shape_tracker.count() < (self._context.window_size - L1_DELTA_LAG):
            return False
        if self._coherence_tracker is not None and self._coherence_tracker.count() < (self._context.window_size - L1_DELTA_LAG):
            return False
        return True
    
    def reset(self):
        """Reset detector state."""
        self._context.reset(full=True)
        self._packet_count = 0
        self._state = MotionState.IDLE
        self._current_probability = 0.0
        self._motion_count = 0
        if self._l1_tracker is not None:
            self._l1_tracker.reset()
        if self._shape_tracker is not None:
            self._shape_tracker.reset()
        if self._coherence_tracker is not None:
            self._coherence_tracker.reset()
        self.probability_history = []
        self.state_history = []
    
    def get_name(self):
        """Get detector name."""
        return "ML"
    
    @property
    def total_packets(self):
        """Total packets processed."""
        return self._packet_count
    
    def get_motion_count(self):
        """Get number of motion detections (for tracking)."""
        return self._motion_count
