/*
 * ESPectre - Website tool contracts
 *
 * Copyright 2026 Francesco Pace <francescopace@gmail.com>
 * SPDX-License-Identifier: GPL-3.0-only
 * Commercial licensing available under separate agreement; see LICENSING.md.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { runInNewContext } from 'node:vm';
import { app, browserSupportSource, directProtocol, GPL_HTML_HEADER, index, read, roadmapContent, routeManifest, routeRegistry, security, styles, toolContent, toolFragments, toolsContent } from './fixtures/site_test_helpers.mjs';

describe('website tool contracts', () => {
    it('keeps Flash guidance and actions aligned with the selected frontend', () => {
        const flashPage = toolContent.flash;
        assert.match(flashPage, /id="flash-frontend"[\s\S]*?href="\/guides\/setup\/"/);
        assert.match(flashPage, /<button slot="activate" class="btn-primary btn-sm">[\s\S]*?<\/button>[\s\S]*class="btn-secondary btn-sm js-matter-read" hidden>[\s\S]*?<\/button>[\s\S]*class="btn-secondary btn-sm js-firmware-releases" href="https:\/\/github\.com\/francescopace\/espectre\/releases"/);
        assert.match(app, /matterReadButton\.hidden = frontendKey !== 'matter'/);
        assert.match(app, /track\('firmware_releases_open', \{[\s\S]*frontend: params\.frontend,[\s\S]*channel: params\.channel,[\s\S]*entry_point: 'flash'/);
    });

    it('loads generated firmware and SDK output from the shared artifacts tree', () => {
        assert.match(app, /\/artifacts\/firmware\//);
        assert.match(toolContent.flash, /id="flash-channel"/);
        assert.match(toolContent.flash, /<option value="release"/);
        assert.match(toolContent.flash, /<option value="preview"/);
        assert.match(toolContent.flash, /<option value="develop"/);
        assert.match(app, /updateReleaseBadge[\s\S]*\/artifacts\/firmware\/release\/firmware-manifest-release\.json/);
        assert.match(app, /builds: artifacts\.map\(\(artifact\) => \(\{/);
        assert.match(app, /chipFamily: artifact\.chip_family/);
        assert.match(app, /const requestId = \+\+flash\.refreshRequest;/);
        assert.match(app, /const selectedChannel = channelSel\.value;/);
        assert.match(app, /const manifest = await flashLoadManifest\(selectedChannel\);/);
        assert.ok((app.match(/if \(requestId !== flash\.refreshRequest\) return;/g) || []).length >= 2);
        assert.match(app, /FLASH_CHIP_UNSUPPORTED_RE/);
        assert.match(app, /report\('unsupported'\)/);
        assert.match(app, /function flashSetFrontendActions/);
        assert.match(index, /class="modal-backdrop js-matter-modal" hidden>[\s\S]*class="modal-card matter-modal-card" role="dialog" aria-modal="true"/);
        assert.match(index, /id="matter-modal-title"/);
        assert.match(index, /class="matter-result js-matter-result" hidden>/);
        assert.match(app, /function matterOpen\(returnFocus\)/);
        assert.match(app, /matterOpen\(trigger\)/);
        assert.match(app, /if \(!\$\('\.js-matter-modal'\)\.hidden\) \{[\s\S]*?window\.matterClose\(\)/);
        assert.match(app, /track\('matter_qr_read'/);
        assert.match(app, /installButton\.toggleAttribute\('inert', !browserSupport\.flash\)/);
        const setupGuide = read('docs/web/content/guides/setup.html');
        assert.match(setupGuide, /flash-connect-usb-card\.avif/);
        assert.match(setupGuide, /href="\/guides\/hardware\/"/);
        assert.match(setupGuide, /href="\/guides\/home-assistant\/"/);
        assert.match(setupGuide, /\.\/espectre matter qr/);
        assert.match(setupGuide, /\.\/espectre mqtt/);
        for (const frontend of ['esphome', 'native', 'matter']) {
            assert.match(setupGuide, new RegExp(`\\.\\/espectre ${frontend} build`));
            assert.match(setupGuide, new RegExp(`\\.\\/espectre ${frontend} flash --chip c3`));
        }
        assert.match(setupGuide, /\.\/espectre esphome monitor/);
        assert.match(setupGuide, /<code>--config path\/to\/espectre\.yaml<\/code>/);
        assert.match(setupGuide, /\.\/espectre monitor --chip c3 --frontend native --reset/);
        assert.match(setupGuide, /\.\/espectre monitor --chip c3 --frontend matter --reset/);
        assert.match(setupGuide, /\.\/espectre devices --frontend native/);
        assert.equal((setupGuide.match(/class="code-tabs" data-code-tabs/g) || []).length, 2);
        assert.match(setupGuide, /role="tablist"/);
        const cliTabsSection = setupGuide.slice(setupGuide.indexOf('id="setup-cli"'), setupGuide.indexOf('id="setup-network"'));
        assert.equal((cliTabsSection.match(/role="tab"/g) || []).length, 3);
        assert.equal((cliTabsSection.match(/role="tabpanel"/g) || []).length, 3);
        assert.match(setupGuide, /id="setup-native-tab"[^>]*aria-selected="true"[\s\S]*?id="setup-esphome-tab"[^>]*aria-selected="false"/);
        assert.ok(setupGuide.indexOf('data-frontend="native"') < setupGuide.indexOf('data-frontend="esphome"'));
        for (const chip of ['c5', 'c6', 's3', 'esp32']) {
            assert.match(setupGuide, new RegExp(`<code>${chip}<\\/code>`));
        }
        for (const frontend of ['esphome', 'native', 'matter']) {
            const panel = setupGuide.match(new RegExp(`<div class="code-tab-panel"[^>]*data-frontend="${frontend}"[^>]*>([\\s\\S]*?)<\\/div>`));
            assert.ok(panel, `${frontend} CLI tab exists`);
            assert.match(panel[1], new RegExp(`\\.\\/espectre ${frontend} build --chip c3 --clean`));
            assert.match(panel[1], new RegExp(`\\.\\/espectre ${frontend} flash --chip c3`));
            assert.match(panel[1], frontend === 'esphome'
                ? /\.\/espectre esphome monitor --chip c3/
                : new RegExp(`\\.\\/espectre monitor --chip c3 --frontend ${frontend} --reset`));
        }
        const esphomePanel = setupGuide.match(/<div class="code-tab-panel"[^>]*data-frontend="esphome"[^>]*>([\s\S]*?)<\/div>/)[1];
        assert.match(esphomePanel, /--config path\/to\/espectre\.yaml/);
        const networkTabsSection = setupGuide.slice(setupGuide.indexOf('id="setup-network"'), setupGuide.indexOf('id="setup-test"'));
        assert.match(networkTabsSection, /role="tablist"/);
        assert.equal((networkTabsSection.match(/role="tab"/g) || []).length, 3);
        assert.equal((networkTabsSection.match(/role="tabpanel"/g) || []).length, 3);
        assert.match(networkTabsSection, /id="setup-network-native-tab"[^>]*aria-selected="true"[\s\S]*?id="setup-network-esphome-tab"[^>]*aria-selected="false"/);
        for (const frontend of ['native', 'esphome', 'matter']) {
            assert.match(networkTabsSection, new RegExp(`data-network-frontend="${frontend}"`));
        }
        const nativeNetworkPanel = networkTabsSection.match(/<div class="code-tab-panel"[^>]*data-network-frontend="native"[^>]*>([\s\S]*?)<\/div>/)[1];
        assert.match(nativeNetworkPanel, /\.\/espectre mqtt --broker 192\.168\.1\.20/);
        assert.match(nativeNetworkPanel, /espectre&gt; help/);
        assert.match(nativeNetworkPanel, /espectre&gt; set_threshold 0\.35/);
        assert.match(nativeNetworkPanel, /espectre&gt; recalibrate/);
        assert.match(styles, /\.code-tabs \{[\s\S]*?border: 1px solid var\(--border\);[\s\S]*?border-radius: 14px;[\s\S]*?background: var\(--surface\);/);
        assert.match(styles, /\.code-tabs-list \{[\s\S]*?display: flex;[\s\S]*?overflow-x: auto;/);
        assert.match(styles, /\.code-tab-panel \{ padding: 18px; \}/);
        assert.match(styles, /\.code-tab-subsection \{[\s\S]*?border-top: 1px solid var\(--border\);/);
        assert.match(styles, /\.code-tabs-list \[role="tab"\]\[aria-selected="true"\]/);
        const navigation = read('docs/web/assets/js/navigation.js');
        assert.match(navigation, /function initCodeTabs/);
        assert.match(navigation, /event\.key === 'ArrowRight'/);
        assert.match(navigation, /event\.key === 'ArrowLeft'/);
        assert.match(app, /window\.initCodeTabs\(container\)/);
        const sdkContent = read('docs/web/content/sdk.html');
        assert.match(sdkContent, /href="\/artifacts\/sdk\/release\/"/);
        assert.match(sdkContent, /<details class="sdk-download">[\s\S]*?<summary class="btn-primary">/);
        assert.match(sdkContent, /href="\/artifacts\/sdk\/preview\/"/);
        assert.match(sdkContent, /href="\/artifacts\/sdk\/develop\/"/);
        assert.match(sdkContent, /data-sdk-version="release"/);
        assert.match(sdkContent, /data-sdk-version="preview"/);
        assert.match(sdkContent, /data-sdk-version="develop"/);
        assert.match(read('docs/web/assets/js/navigation.js'), /sdk-manifest-\$\{channel\}\.json/);
        assert.match(read('docs/web/assets/js/navigation.js'), /details\.sdk-download\[open\][\s\S]*?!menu\.contains\(event\.target\)[\s\S]*?menu\.open = false/);
        assert.match(app, /window\.initSdkDownloadVersions\(container\)/);
        assert.match(read('docs/web/content/sdk/api.html'), /data-api-index="\/artifacts\/sdk\/api\/api-index\.json"/);
        assert.match(sdkContent, /href="\/sdk\/api\/" class="doc-link"/);
        assert.match(read('docs/web/.gitignore'), /^\/artifacts\/$/m);
    });

    it('maps Direct capabilities, runtime controls, and Wi-Fi access points safely', () => {
        const configure = toolContent.configure;
        const mqtt = toolContent.monitor;
        const game = toolContent.game;
        const connectionTemplate = index.match(/<template id="connection-picker-template">[\s\S]*?<\/template>/)?.[0] || '';
        const directTemplate = index.match(/<template id="direct-connect-template">[\s\S]*?<\/template>/)?.[0] || '';
        const configureBanner = configure.match(/class="device-banner-actions"[\s\S]*?<\/div>/)?.[0] || '';
        const mqttBanner = mqtt.match(/class="device-banner-actions"[\s\S]*?<\/div>/)?.[0] || '';
        assert.match(configure, /data-capability="supports_wifi_bssid"/);
        assert.match(configure, /data-capability-unavailable="supports_wifi_status"/);
        assert.match(configure, /data-capability-unavailable="supports_mqtt_config"/);
        assert.match(configure, /class="device-name-availability js-configure-name-unavailable" hidden/);
        assert.match(app, /const sections = new Set\(capabilities\.config_sections \|\| \[\]\)/);
        assert.match(app, /supports_wifi_status: sections\.has\('wifi'\)/);
        assert.match(app, /supports_wifi_bssid: methods\.has\('set_wifi_bssid'\)[\s\S]*?methods\.has\('clear_wifi_bssid'\)[\s\S]*?methods\.has\('scan_wifi_access_points'\)[\s\S]*?methods\.has\('wifi_access_points'\)/);
        assert.match(app, /supports_wifi_clear: methods\.has\('clear_wifi_config'\)/);
        assert.match(app, /DIRECT_FULL_DEVICE_ID\.test\(input\)[\s\S]*?DirectProtocolClient\.normalizeEndpoint\(`espectre-\$\{input\}\.local`\)[\s\S]*?deviceId: input[\s\S]*?discoveryFallback: true/);
        assert.match(app, /if \(target\.discoveryFallback\)[\s\S]*?resolveDiscoveredTarget\(\{[\s\S]*?deviceId: target\.deviceId[\s\S]*?search: target\.deviceId/);
        assert.match(app, /target\.deviceId\s*\? peer\.device_id === target\.deviceId/);
        assert.match(app, /supports_runtime_threshold: methods\.has\('set_threshold'\)/);
        assert.match(app, /supports_runtime_motion_hits: methods\.has\('set_motion_hits'\)/);
        assert.match(app, /supports_runtime_detector: methods\.has\('set_detector'\)/);
        assert.match(app, /supports_manual_recalibration: methods\.has\('recalibrate'\)/);
        assert.match(app, /edit\.hidden = false/);
        assert.match(app, /data\.device_label \|\| data\.device_name \|\| data\.name/);
        assert.match(app, /if \(!Object\.prototype\.hasOwnProperty\.call\(snapshot, capability\)\) return;/);
        assert.match(app, /\$\$\('\[data-capability-unavailable\]'\)[\s\S]*?element\.hidden = sysinfoBoolean\(snapshot\[capability\]\)/);
        assert.match(app, /if \(!capabilities\.some\(\(key\) => Object\.prototype\.hasOwnProperty\.call\(snapshot, key\)\)\) return;/);
        assert.match(configure, /<input type="text" id="cfg-ssid" readonly>/);
        assert.match(configure, /<input type="text" id="cfg-channel" readonly>/);
        assert.match(configure, /<input type="text" id="cfg-wifi-band" readonly>/);
        assert.match(configure, /<input type="text" id="cfg-wifi-phy" readonly>/);
        assert.match(configure, /<div class="field-row wifi-link-row">\s*<div class="field">[\s\S]*?id="cfg-channel"[\s\S]*?id="cfg-wifi-band"[\s\S]*?id="cfg-wifi-phy"/);
        assert.match(styles, /\.wifi-link-row \{ grid-template-columns: repeat\(3, minmax\(0, 1fr\)\); \}/);
        assert.match(configure, /<select id="cfg-bssid"[\s\S]*?<option value="">/);
        assert.match(configure, /id="cfg-bssid-help"[^>]*aria-live="polite"/);
        assert.doesNotMatch(configure, /id="cfg-wifi-pass"/);
        assert.match(app, /activeToolName\(\) === 'configure'[\s\S]*?directClient\.request\('diagnostics'\)/);
        assert.match(app, /snapshot\.wifi_channel[\s\S]*?set\('cfg-channel'/);
        assert.match(app, /snapshot\.csi_profile[\s\S]*?set\('cfg-wifi-phy'/);
        assert.match(app, /function monitorResizeChart\(\) \{[\s\S]*?const canvas = \$\('\.js-mon-chart'\);[\s\S]*?if \(!canvas\) return;/);
        assert.match(app, /const client = directClient[\s\S]*client\.request\('scan_wifi_access_points'\)/);
        assert.match(app, /client\.request\('wifi_access_points'\)/);
        assert.match(app, /WIFI_SCAN_TIMEOUT_MS = 30 \* 1000/);
        assert.match(app, /const deadline = Date\.now\(\) \+ WIFI_SCAN_TIMEOUT_MS;[\s\S]*?while \(Date\.now\(\) < deadline\)/);
        assert.match(app, /if \(!scanning && Array\.isArray\(snapshot\.access_points\)\)/);
        assert.match(app, /if \(conn\.mode === 'demo'\) \{\s*renderWifiAccessPoints\(\{ scanning: true \}\);\s*await new Promise[\s\S]*?renderWifiAccessPoints\(\{\s*scanning: false,[\s\S]*?access_points:/);
        assert.match(app, /if \(directClient !== client \|\| !client\.connected\) return;/);
        assert.match(app, /\.js-wifi-scan'\)\.addEventListener\('click', cfgRefreshWifiAccessPoints\)/);
        assert.doesNotMatch(app, /void cfgRefreshWifiAccessPoints\(\)/);
        assert.match(app, /const method = bssid \? 'set_wifi_bssid' : 'clear_wifi_bssid'/);
        assert.match(app, /new Option\(`\$\{bssid\} · \$\{rssi\} dBm`, bssid\)/);
        assert.match(app, /if \(!select \|\| !scanButton\) return;/);
        assert.match(index, /class="conn-dropdown-meta"/);
        assert.match(index, /js-menu-frontend[\s\S]*js-menu-chip[\s\S]*js-menu-device-id[\s\S]*js-menu-firmware/);
        assert.match(toolFragments, /class="mono-sub device-banner-identity"/);
        assert.match(mqtt, /js-device-banner-sub[\s\S]*js-firmware-update-notice/);
        assert.match(configure, /class="device-banner-name-editor js-configure-name-editor"[\s\S]*?js-configure-name-trigger[\s\S]*?js-configure-name-display[\s\S]*?class="device-banner-name-icon"[\s\S]*?aria-hidden="true"[\s\S]*?js-configure-name-input/);
        assert.match(mqtt, /class="device-banner-name-editor js-monitor-name-editor"[\s\S]*?js-monitor-name-trigger[\s\S]*?js-monitor-name-display[\s\S]*?class="device-banner-name-icon"[\s\S]*?aria-hidden="true"[\s\S]*?js-monitor-name-input/);
        assert.match(configure, /class="config-grid connectivity-grid js-connectivity-setup"/);
        assert.match(styles, /\.connectivity-grid \{ grid-template-columns: minmax\(320px, 1fr\) minmax\(0, 2fr\); \}/);
        assert.equal([...`${index}\n${toolFragments}`.matchAll(/class="device-firmware-update js-firmware-update-notice"/g)].length, 3);
        assert.match(index, /class="conn-dropdown-name js-device-name js-connection-device-name"/);
        assert.match(app, /function formatDeviceIdentityLine/);
        assert.match(app, /function renderConfigureDeviceNameEditor/);
        assert.match(app, /conn\.deviceLabel \|\| conn\.generatedName \|\| conn\.deviceId/);
        assert.match(app, /identity\.textContent = formatDeviceIdentityLine\(\s*conn\.frontend,\s*conn\.chip,\s*conn\.deviceId,\s*conn\.firmwareVersion/);
        assert.match(app, /const chip = snapshot\.chip \? String\(snapshot\.chip\)\.toUpperCase\(\) : conn\.chip/);
        assert.match(app, /const firmware = snapshot\.firmware_version \|\| snapshot\.firmware \|\| snapshot\.version \|\| conn\.firmwareVersion/);
        assert.match(app, /const canEdit = conn\.status === 'connected'[\s\S]*?conn\.mode === 'direct'[\s\S]*?conn\.mode === 'demo'/);
        assert.match(app, /function startConfigureDeviceNameEdit/);
        assert.match(app, /function saveConfigureDeviceNameOnBlur/);
        assert.match(app, /nameInput\.addEventListener\('blur',[\s\S]*?saveConfigureDeviceNameOnBlur/);
        assert.match(app, /function renderMonitorDeviceNameEditor/);
        assert.match(app, /function startMonitorDeviceNameEdit/);
        assert.match(app, /function saveMonitorDeviceNameOnBlur/);
        assert.match(app, /js-monitor-name-trigger'\)\.addEventListener\('click', startMonitorDeviceNameEdit\)/);
        assert.match(app, /nameInput\.addEventListener\('blur',[\s\S]*?saveMonitorDeviceNameOnBlur/);
        assert.match(app, /function cfgSaveDeviceLabel\(label\)[\s\S]*?'set_device_label'/);
        assert.match(styles, /\.device-banner-name-trigger \{[\s\S]*?display: inline-flex;[\s\S]*?cursor: pointer;[\s\S]*?\.device-banner-name-icon[\s\S]*?\.device-banner-name-input/);
        assert.match(app, /conn\.deviceBannerSub = conn\.mode === 'direct'[\s\S]*?\? deviceIdentity/);
        assert.match(app, /write\('\.js-menu-frontend', formatFrontendLabel\(identity\.frontend\)\)/);
        assert.match(app, /write\('\.js-menu-chip', identity\.chip\)/);
        assert.match(app, /write\('\.js-menu-device-id', identity\.deviceId\)/);
        assert.match(app, /write\('\.js-menu-firmware', identity\.firmwareVersion\)/);
        assert.match(index, /js-transport-tag[^>]*hidden/);
        assert.match(index, /js-menu-frontend-row/);
        assert.match(app, /frontendRow\.hidden = usbConnected/);
        assert.match(index, /js-menu-device-id-label/);
        assert.match(index, /js-menu-firmware-label/);
        assert.match(index, /js-usb-port-note[^>]*hidden/);
        assert.match(app, /const displayedMode = usbConnected \? 'usb' : conn\.mode/);
        assert.match(index, /energy-title/);
        assert.match(styles, /\.conn-dropdown \{[^}]*color: var\(--text\);/);
        assert.match(styles, /\.conn-dropdown-name \{[^}]*color: var\(--text\);/);
        assert.match(mqtt, /data-device-view="live"/);
        assert.match(configure, /data-device-view="connectivity"/);
        assert.match(mqtt, /live-calibration" data-device-command="recalibrate"/);
        assert.match(app, /statusFn: toast/);
        assert.match(app, /deviceCommand === 'recalibrate' && detector !== 'lightweight'/);
        assert.match(app, /function beginCalibration/);
        assert.match(mqtt, /js-sense-recalibrate/);
        assert.match(mqtt, /<details class="device-live-diagnostics">/);
        assert.doesNotMatch(mqtt, /<details class="device-live-diagnostics" open/);
        assert.match(app, /const showLiveEnergy = live/);
        assert.match(app, /js-device-edit-connectivity'\)\.addEventListener\('click', monitorEditOrCancel\)/);
        assert.match(app, /targetRoute = view === 'connectivity' \? 'tool-configure' : 'tool-monitor'/);
        assert.match(app, /window\.navigateToRoute\(targetRoute\)/);
        assert.match(app, /device: 'tool-configure'/);
        assert.match(app, /const directSetup = connected && conn\.mode === 'direct'/);
        assert.match(app, /const directConnecting = conn\.status === 'connecting'/);
        assert.match(styles, /\.field input\[aria-invalid="true"\]/);
        assert.match(styles, /@keyframes espFieldErrorBlink/);
        assert.match(app, /function syncThresholdControl\(/);
        assert.match(app, /function bindThresholdControls/);
        assert.match(app, /function commitThreshold/);
        assert.match(app, /sense !== document\.activeElement/);
        assert.match(app, /conn\.threshold = threshold;[\s\S]*syncThresholdControl\(threshold\)/);
        assert.match(app, /const GAME_THRESHOLD_DEFAULT = 0\.5/);
        assert.match(app, /function gameThreshold/);
        assert.match(app, /function resetGameThreshold/);
        assert.match(app, /gameThresholdOverride = GAME_THRESHOLD_DEFAULT/);
        assert.match(app, /if \(target === 'tool-game' && previousRoute !== 'tool-game'\) resetGameThreshold\(\)/);
        assert.match(app, /gameThresholdOverride = threshold/);
        assert.match(app, /js-game-fullscreen-threshold/);
        assert.match(app, /const applyFullscreenPointerThreshold = \(event\) =>/);
        assert.match(app, /\(bounds\.bottom - event\.clientY\) \/ bounds\.height/);
        assert.match(app, /getElementById\('game-threshold'\)/);
        assert.match(game, /id="game-threshold"/);
        assert.match(game, /<div class="game-screen">[\s\S]*<div class="game-status"[\s\S]*js-game-score[\s\S]*js-game-best[\s\S]*js-game-fullscreen/);
        assert.equal((game.match(/class="js-game-score"/g) || []).length, 1);
        assert.match(app, /function gameToggleFullscreen/);
        assert.match(app, /requestFullscreen \|\| screen\.webkitRequestFullscreen/);
        assert.match(app, /document\.addEventListener\('fullscreenchange', gameOnFullscreenChange\)/);
        assert.match(styles, /\.game-screen:fullscreen/);
        assert.match(styles, /\.game-screen:fullscreen \.game-canvas/);
        assert.match(styles, /\.game-screen:fullscreen \.game-motion-gauge/);
        assert.match(game, /class="game-motion-threshold-input js-game-fullscreen-threshold"/);
        assert.match(styles, /\.game-motion-threshold-input \{[\s\S]*?cursor: ns-resize;/);
        assert.match(styles, /\.game-status \{[\s\S]*?right: 14px;/);
        assert.match(styles, /\.game-motion-gauge \{[\s\S]*?top: 0;[\s\S]*?bottom: 0;/);
        assert.match(styles, /\.game-screen\[data-phase="done"\] \.game-status \{[\s\S]*?top: 50%;[\s\S]*?left: 50%;[\s\S]*?transform: translate\(-50%, -50%\);/);
        assert.match(styles, /\.game-screen\[data-phase="done"\] \.game-score strong \{[\s\S]*?font-size: clamp\(52px, 10vw, 78px\);/);
        assert.match(app, /getElementById\('sense-detector'\)\.addEventListener\('change'/);
        assert.match(app, /getElementById\('sense-motion-on'\)\.addEventListener\('change'/);
        assert.match(app, /getElementById\('sense-motion-off'\)\.addEventListener\('change'/);
        assert.match(app, /getElementById\('sense-csi-mode'\)\.addEventListener\('change'/);
        assert.match(mqtt, /<select id="sense-csi-mode">[\s\S]*?<option value="internal"[\s\S]*?<option value="external"[\s\S]*?<\/select>/);
        assert.match(app, /getElementById\('sense-generator-mode'\)\.addEventListener\('change'/);
        assert.match(configure, /class="js-configure-onboarding"/);
        assert.match(mqtt, /class="js-monitor-onboarding"/);
        assert.match(index, /data-transport="direct"/);
        assert.equal((toolFragments.match(/<espectre-connection-picker /g) || []).length, 5);
        assert.equal((connectionTemplate.match(/<espectre-direct-connect /g) || []).length, 1);
        for (const surface of ['configure', 'monitor', 'raw-csi', 'theremin', 'game']) {
            assert.match(toolFragments, new RegExp(`<espectre-connection-picker[^>]*data-surface="${surface}"`));
        }
        assert.match(connectionTemplate, /data-connection-mode="direct"[\s\S]*data-connection-mode="demo"[\s\S]*data-connection-mode="relay"/);
        assert.match(connectionTemplate, /data-connection-panel="direct"[\s\S]*data-connection-panel="demo"[\s\S]*data-connection-panel="relay"/);
        assert.match(styles, /\.transport-choice \{[\s\S]*?grid-template-columns: repeat\(3, minmax\(0, 1fr\)\);/);
        assert.ok(directTemplate.indexOf('js-direct-discover') < directTemplate.indexOf('js-direct-endpoint'));
        assert.ok(directTemplate.indexOf('js-direct-endpoint') < directTemplate.indexOf('js-connect-direct'));
        assert.match(directTemplate, /class="direct-connect-recovery"[\s\S]*?<a href="\/tools\/flash\/">/);
        assert.match(directTemplate, /class="device-connect-card connection-card direct-connect-card empty-state"/);
        assert.match(app, /class DirectConnectElement extends HTMLElement/);
        assert.match(app, /customElements\.define\('espectre-direct-connect', DirectConnectElement\)/);
        assert.match(app, /class ConnectionPickerElement extends HTMLElement/);
        assert.match(app, /customElements\.define\('espectre-connection-picker', ConnectionPickerElement\)/);
        assert.match(app, /const inputId = `\$\{surface\}-direct-endpoint`/);
        assert.match(configureBanner, /js-start-detection/);
        assert.match(mqttBanner, /js-device-edit-connectivity/);
        assert.match(app, /function connectDirect/);
        assert.match(app, /const view = openView \|\| \(route === 'tool-monitor' \? 'live' : 'connectivity'\)/);
        assert.match(app, /function directConnectionErrorMessage\(error, endpoint, permissionState/);
        assert.match(app, /function directPageOriginKind\(\)/);
        assert.match(app, /function directBrowserGuidance\(\)/);
        assert.match(app, /browserSupport\.hostedDirect === 'targeted'/);
        assert.match(app, /function renderDirectBrowserGuidance\(\)/);
        assert.match(app, /note\.hidden = !message/);
        assert.match(app, /renderDirectBrowserGuidance\(\);/);
        assert.match(app, /permissionState === 'denied'/);
        assert.match(app, /error\?\.code === 'local_network_denied'/);
        assert.match(app, /browserSupport\.hostedDirect === 'unsupported'/);
        assert.match(app, /function setDirectConnectionHelp\(message = ''\)/);
        assert.match(app, /await localNetworkAccessState\(\)/);
        assert.match(directTemplate, /class="direct-connection-help js-direct-help" role="alert" hidden/);
        assert.match(directTemplate, /class="tool-note direct-connection-status js-direct-status" role="status" aria-live="polite" hidden/);
        assert.match(app, /directEndpointInput\(\)\?\.closest\('\.device-connect-card'\)\?\.querySelector\('\.js-direct-help'\)/);
        assert.match(app, /function setDirectConnectionStatus\(message = ''\)/);
        assert.match(app, /function resolveDiscoveredTarget[\s\S]*?setDirectConnectionHelp\(\);[\s\S]*?setDirectConnectionStatus\([\s\S]*?finally \{\s*setDirectConnectionStatus\(\);/);
        assert.equal((index.match(/class="tool-note js-direct-browser-note" role="status"/g) || []).length, 1);
        assert.match(app, /error\.code \|\| error\.name/);
        assert.match(app, /await client\.handshake\(\)/);
        assert.match(app, /const info = await directClient\.request\('info'\);[\s\S]*const status = await directClient\.request\('status'\);[\s\S]*const config = await directClient\.request\('config'\);/);
        assert.match(app, /DIRECT_RECONNECT_DELAYS_MS = Object\.freeze\(\[500, 1500, 3000\]\)/);
        assert.match(app, /function scheduleDirectReconnect\(client\)/);
        assert.match(app, /await client\.connect\(\{ timeoutMs: 5000 \}\)/);
        assert.match(app, /if \(pendingConfigVerification\) requestConfigVerification\(\)/);
        assert.match(index, /list="direct-remembered-endpoints"/);
        assert.match(index, /id="direct-remembered-endpoints"/);
        assert.match(app, /DIRECT_ENDPOINT_STORAGE_KEY = 'espectre\.direct\.endpoints\.v1'/);
        assert.match(app, /function rememberDirectEndpoint\(endpoint\)/);
        assert.match(app, /function consumeDirectHandoff\(\)/);
        assert.match(app, /const directTarget = params\.get\('target'\) \|\| ''/);
        assert.match(app, /parseDirectTarget\(directTarget\)/);
        assert.match(app, /const DIRECT_FULL_DEVICE_ID = \/\^\[0-9a-f\]\{16\}\$\//);
        assert.match(app, /const DIRECT_SHORT_DEVICE_ID = \/\^\[0-9a-f\]\{6\}\$\//);
        assert.match(app, /if \(matches\.length > 1\)/);
        assert.match(app, /button\.dataset\.deviceId = deviceId/);
        assert.match(app, /deviceId: peer\.device_id/);
        assert.match(app, /DirectProtocolClient\.createDiscoveryEndpoint\(\)/);
        const localPeerQuery = app.match(/async function queryLocalPeers[\s\S]*?async function discoverLocalPeers/)?.[0] || '';
        assert.match(localPeerQuery, /return await client\.discoverPeersBootstrap\(\)/);
        assert.doesNotMatch(localPeerQuery, /client\.connect|client\.handshake/);
        assert.match(directProtocol, /const PEER_DISCOVERY_TIMEOUT_MS = 10000;/);
        assert.doesNotMatch(directProtocol, /Math\.random/);
        assert.match(app, /error\?\.code === 'unsupported_crypto'/);
        assert.doesNotMatch(directTemplate, /ws:\/\/|\.local/);
        assert.match(app, /await client\.request\('set_sensing', \{ enabled: true \}\)/);
        assert.match(index, /class="modal-card" role="dialog" aria-modal="true"/);
        assert.match(index, /class="btn-primary js-ota-start" disabled/);
        assert.match(index, /id="cfg-ota-message"/);
        assert.match(app, /function applyOtaStatus/);
        assert.match(app, /function flashDialogText\(root\)/);
        assert.match(app, /function activateUsbConnection\(dialog\)/);
        assert.match(app, /dialog\.port && typeof dialog\.port\.getInfo === 'function'/);
        assert.match(app, /activateUsbConnection\(dialog\);/);
        assert.match(app, /dialog\.addEventListener\('closed', \(\) => scheduleUsbConnectionRelease\(dialog\)/);
        assert.match(app, /scheduleUsbConnectionRelease\(dialog\);[\s\S]*if \(started && !reported\) report\('cancelled'\)/);
        assert.match(app, /if \(element\.shadowRoot\) text \+= ' ' \+ flashDialogText\(element\.shadowRoot\)/);
        assert.match(app, /const observedRoots = new WeakSet\(\)/);
        assert.match(app, /observeRoot\(dialog\.shadowRoot\);[\s\S]*flashDialogText\(dialog\.shadowRoot\)/);
        assert.equal(
            routeManifest.routes.find((route) => route.name === 'tool-configure')?.staticPath,
            '/tools/device-settings/'
        );
        assert.match(index, /href="\/tools\/device-settings\/" class="home-tool-card"/);
        assert.doesNotMatch(index, /href="\/tools\/configure\/"/);
        assert.match(index, /data-page="tool-configure"/);
        assert.match(app, /const configureUrl = new URL\('\/', location\.origin\)[\s\S]*configureUrl\.search = returnedUrl\.search[\s\S]*configureUrl\.hash = 'tool-configure'/);
        const staticPageBuilder = read('.github/scripts/build_static_pages.py');
        assert.match(staticPageBuilder, /source = content_path\(route\)/);
        assert.match(staticPageBuilder, /output = output_path\(route\)/);
        assert.doesNotMatch(staticPageBuilder, /location\.replace\(destination\)/);
        assert.match(app, /if \(item\.href !== destination\) item\.href = destination[\s\S]*if \(item\.target !== '_self'\) item\.target = '_self'/);
        assert.match(app, /const method = bssid \? 'set_wifi_bssid' : 'clear_wifi_bssid'/);
        assert.match(app, /const params = bssid \? \{ bssid \} : \{\}/);
        assert.match(app, /String\(snapshot\.wifi_bssid \|\| ''\)\.toUpperCase\(\) === bssid/);
        assert.match(app, /directClient\.request\('clear_wifi_config', \{\}, \{ timeoutMs: 3000 \}\)/);
        assert.match(app, /teardownConnection\('wifi_cleared'\)/);
        assert.match(app, /track\('firmware_installer_open', flashParams\(\)\)/);
        assert.match(app, /dialog\._installConfirmed === true[\s\S]*markStarted\(\)/);
        assert.match(app, /track\('firmware_install_start', flashParams\(\)\)/);
        assert.match(app, /installState === 'finished'[\s\S]*report\('success'\)/);
        assert.match(app, /inspectTimer = setInterval\(inspect, 250\)/);
        assert.match(app, /clearInterval\(inspectTimer\)/);
        assert.match(styles, /ewt-install-dialog \{[\s\S]*--md-dialog-container-shape: 16px/);
        assert.match(styles, /ewt-install-dialog \{[\s\S]*--md-dialog-headline-font: var\(--font-display\)/);
        assert.match(styles, /ewt-install-dialog \{[\s\S]*--md-sys-color-primary: var\(--accent\)/);
        assert.match(styles, /ewt-install-dialog \{[\s\S]*--md-circular-progress-active-indicator-color: var\(--accent\)/);
        assert.match(app, /function startSilentOtaCheck/);
        assert.match(app, /function maybeStartSilentOtaCheck/);
        assert.match(app, /function currentOtaCheckTransport/);
        assert.match(app, /supportsOta \? await directClient\.request\('ota_status'\) : null/);
        assert.match(app, /if \(otaStatus\) applyOtaStatus\(otaStatus\)/);
        assert.match(app, /if \(conn\.mode === 'demo'\) return;/);
        assert.match(app, /if \(conn\.mode === 'direct' && directClient\?\.connected\) return 'direct'/);
        assert.match(app, /if \(!transport\) return;/);
        assert.match(app, /if \(!manual && transport && otaCheckTransport === transport\) return;/);
        assert.match(app, /if \(!otaDefaultChannel \|\| otaBusy\) return;/);
        assert.match(app, /maybeStartSilentOtaCheck\(\);/);
        const demoConnection = app.match(/function connectDemo\(openView = ''\)[\s\S]*?function demoTrackMouse/)?.[0] || '';
        assert.match(demoConnection, /otaSupported = false;[\s\S]*?syncFirmwareUpdateNotice\(\)/);
        assert.match(demoConnection, /supports_ota: 'false'/);
        assert.doesNotMatch(demoConnection, /'ota_status'|'ota_check'|ota_state:|ota_update_available:/);
        assert.match(app, /otaTransportReady = conn\.mode === 'direct'/);
        assert.match(app, /el\.hidden = conn\.mode === 'demo' \|\| Boolean\(flash\.usbDialog\) \|\| otaSupported === false/);
        assert.match(app, /function renderConnection\(\) \{[\s\S]*?syncFirmwareUpdateNotice\(\);/);
        assert.match(app, /if \(!currentOtaCheckTransport\(\)\) return;/);
        assert.match(app, /monitorPublishCommand\(otaCommandFields\('ota_start'\)/);
        assert.match(app, /OTA_TRACKING_TIMEOUT_MS/);
        assert.match(app, /normalizedState === 'reboot_scheduled'[\s\S]*otaAwaitingReconnect = true/);
        assert.match(app, /if \(otaTargetVersion && version !== otaTargetVersion\)/);
        assert.match(app, /finishOtaTracking\('success', null, 'reconnected'\)/);
        assert.match(app, /otaAwaitingReconnect &&[\s\S]*normalizedState === 'idle'[\s\S]*completeOtaReconnect\(\)/);
        assert.match(index, /js-menu-firmware[\s\S]*js-firmware-update-notice[\s\S]*js-disconnect/);
        assert.match(index, /class="conn-firmware-row"/);
        assert.match(app, /function sharedToolControlsInit\(\)/);
        assert.match(app, /const firmwareButton = event\.target\.closest\('\.js-firmware-update-notice'\);[\s\S]*?if \(firmwareButton\) \{[\s\S]*?window\.otaOpen\(firmwareButton\)/);
        assert.match(app, /status = 'error'/);
        assert.match(app, /function otaOpen\(returnFocus\) \{\s*if \(conn\.mode === 'demo'\) return;/);
        assert.match(index, /id="ota-channel"/);
        assert.match(index, /<option value="release" selected/);
        assert.match(app, /function selectedOtaChannel/);
        assert.match(app, /function applyOtaDefaultChannel/);
        assert.match(app, /applyOtaDefaultChannel\(status\.default_channel/);
        assert.match(app, /otaChannelChanged = true/);
        assert.match(app, /return channel \? \{ command, channel \} : \{ command \}/);
        assert.match(app, /if \(conn\.mode === 'demo'\) return;/);
        assert.match(configure, /class="config-status js-wifi-status" role="status"[\s\S]*?js-wifi-status-text/);
        assert.match(configure, /class="config-status js-mqtt-status" role="status"[\s\S]*?js-mqtt-status-text/);
        assert.match(app, /setConfigurationStatus\('wifi', snapshot\.wifi_connected, snapshot\.wifi_configured\)/);
        assert.match(app, /setConfigurationStatus\('mqtt', snapshot\.mqtt_connected, snapshot\.mqtt_configured\)/);
        assert.match(styles, /\.dot-error \{ background: var\(--danger\); \}/);
    });

    it('keeps Direct HTTP diagnostics and presents Relay as unavailable', () => {
        const mqttPage = toolContent.monitor;
        const connectionTemplate = index.match(/<template id="connection-picker-template">[\s\S]*?<\/template>/)?.[0] || '';
        const broker = connectionTemplate.match(/<section class="device-connect-card[^"]*"[^>]*data-connection-panel="relay"[^>]*>[\s\S]*?<\/section>/)?.[0] || '';
        const diagnostics = mqttPage.match(/<details class="device-live-diagnostics">[\s\S]*?<\/details>/)?.[0] || '';
        assert.match(broker, /class="device-connect-card connection-card relay-connect-card empty-state"/);
        assert.match(broker, /class="btn-primary" disabled/);
        assert.doesNotMatch(broker, /<input|js-connect/);
        assert.match(diagnostics, /js-mon-diag-status/);
        assert.match(diagnostics, /js-mon-admitted/);
        assert.match(diagnostics, /js-mon-filtered[\s\S]*js-mon-admitted/);
        assert.match(diagnostics, /class="diag-grid mon-stats-tiles"/);
        assert.match(app, /function syncDiagnosticsPolling/);
        assert.match(app, /setInterval\(monitorRequestStats, interval\)/);
        assert.match(app, /function stopDiagnosticsPolling/);
        assert.match(app, /command: 'diagnostics'/);
        assert.match(app, /const data = direct \? response : response\?\.data;[\s\S]*markMonitorReady\('diagnostics'\);[\s\S]*monitorStats\(data\)/);
        assert.match(app, /return conn\.mode === 'direct' && monitor\.diagRequestPending/);
        assert.match(app, /data\.csi_admitted_pps/);
        assert.match(app, /data\.csi_filtered_pps/);
        assert.match(app, /function applyDirectConfig\(config\) \{[\s\S]*?const device = config\.device \|\| \{\};[\s\S]*?device_label: config\.device_label \?\? device\.device_label[\s\S]*?applySensingSnapshot\(runtime\);/);
        assert.match(app, /function applyRuntimeStatus\(status\) \{[\s\S]*?setCalibrationBusy\(calibrating\);/);
        assert.match(app, /if \(name === 'status'\) applyRuntimeStatus\(data\);/);
        assert.match(app, /const mqttPresetSelect = document\.getElementById\('cfg-mqtt-preset'\);[\s\S]*?if \(mqttPresetSelect\) \{/);
        assert.match(app, /if \(conn\.mode === 'demo' && demoSysinfoSnapshot\) \{[\s\S]*?applySysinfo\(demoSysinfoSnapshot\);/);
        assert.match(app, /if \(detector && detectorSelect\) \{[\s\S]*?syncSensingControls\(\);/);
        assert.match(app, /if \(stateEl\) \{[\s\S]*?stateEl\.classList\.toggle\('motion', motion\);/);
        assert.match(app, /function directConfigSnapshot\(config\) \{[\s\S]*?device_label: config\.device_label \?\? device\.device_label \?\? ''/);
        assert.match(app, /MONITOR_CHART_WINDOW_MS = 60 \* 1000/);
        assert.match(app, /function monitorResetChart/);
        assert.match(app, /function resetMonitorLiveView/);
        assert.match(app, /function monitorSetStat\(selector, value, digits, suffix\) \{[\s\S]*?if \(element\) element\.textContent/);
        assert.match(app, /function adoptDeviceId/);
        assert.match(app, /if \(ctx\) ctx\.clearRect\(0, 0, canvas\.width, canvas\.height\)/);
        assert.match(app, /function monitorOpenConnectivity/);
        assert.match(app, /if \(conn\.mode === 'direct' && directClient\?\.connected\)/);
    });

    it('keeps MQTT configuration in Device settings while browser tools use HTTP', () => {
        const configurePage = toolContent.configure;
        const mqttPage = toolContent.monitor;
        assert.match(configurePage, /id="cfg-mqtt-preset"[\s\S]*?value="home_assistant" selected[\s\S]*?value="lan_broker"[\s\S]*?value="emqx_cloud"[\s\S]*?value="hivemq_cloud"[\s\S]*?value="flespi"[\s\S]*?value="cloud_broker"/);
        assert.match(configurePage, /class="field-row mqtt-host-port-row">[\s\S]*?id="cfg-mqtt-host"[\s\S]*?id="cfg-mqtt-port"/);
        assert.match(configurePage, /id="cfg-mqtt-host"[^>]*value="homeassistant.local"/);
        assert.match(configurePage, /id="cfg-mqtt-port"[^>]*value="1883"/);
        assert.doesNotMatch(configurePage, /id="cfg-mqtt-user"[^>]*value=/);
        assert.doesNotMatch(configurePage, /id="cfg-mqtt-pass"[^>]*value=/);
        assert.match(configurePage, /id="cfg-topic-prefix"[^>]*value="espectre\/v1\/devices"/);
        const onboardingHtml = mqttPage.match(/class="js-monitor-onboarding"[\s\S]*?<div class="js-monitor-workspace"/)?.[0] || '';
        const connectionTemplate = index.match(/<template id="connection-picker-template">[\s\S]*?<\/template>/)?.[0] || '';
        const broker = connectionTemplate.match(/<section class="device-connect-card[^"]*"[^>]*data-connection-panel="relay"[^>]*>[\s\S]*?<\/section>/)?.[0] || '';
        const demo = connectionTemplate.match(/<section class="device-connect-card[^"]*"[^>]*data-connection-panel="demo"[^>]*>[\s\S]*?<\/section>/)?.[0] || '';
        assert.match(onboardingHtml, /<espectre-connection-picker data-surface="monitor" data-open-view="live">/);
        assert.match(broker, /class="device-connect-card connection-card relay-connect-card empty-state"/);
        assert.match(broker, /class="connection-card-eyebrow"/);
        assert.match(broker, /class="btn-primary" disabled/);
        assert.doesNotMatch(broker, /<input|<select/);
        assert.match(styles, /\.connection-card \{ width: min\(100%, 572px\); max-width: 572px;/);
        assert.match(demo, /class="device-connect-card connection-card demo-connect-card empty-state"/);
        assert.match(demo, /class="demo-connect-list"[\s\S]*class="btn-primary js-demo"/);
        assert.match(styles, /\.demo-connect-summary \{[\s\S]*?background: var\(--surface2\);/);
        assert.match(app, /function applyConfigureMqttDefaults/);
        assert.match(app, /const MQTT_PRESETS = Object\.freeze/);
        assert.match(app, /home_assistant:[\s\S]*?host: 'homeassistant\.local', port: '1883'/);
        assert.match(app, /lan_broker:[\s\S]*?configure:[\s\S]*?host: '', port: '1883'/);
        assert.match(app, /emqx_cloud:[\s\S]*?host: 'deployment-id\.ala\.region\.emqxsl\.com', port: '8883'/);
        assert.match(app, /hivemq_cloud:[\s\S]*?host: 'cluster-id\.s1\.region\.hivemq\.cloud', port: '8883'/);
        assert.match(app, /flespi:[\s\S]*?host: 'mqtt\.flespi\.io', port: '8883'/);
        assert.match(app, /cloud_broker:[\s\S]*?configure:[\s\S]*?host: 'cluster\.example\.com', port: ''/);
        assert.match(app, /topicPrefix: 'espectre\/v1\/devices'/);
        assert.match(app, /function applyConfigureMqttPreset/);
        assert.match(app, /function applyMqttPresetFieldLocks/);
        assert.match(app, /function applyConfigureMqttCredentialPolicy/);
        assert.match(app, /password\.disabled = clear \|\| isFlespi/);
        assert.match(app, /if \(isFlespi\) password\.value = ''/);
        assert.match(app, /locked: Object\.freeze\(\['port'\]\)/);
        assert.match(app, /locked: Object\.freeze\(\['host', 'port'\]\)/);
        assert.match(app, /input\.readOnly = isLocked/);
        assert.match(styles, /\.field input\[data-preset-locked\][\s\S]*?cursor: not-allowed/);
        assert.match(styles, /\.broker-host-control \{[\s\S]*?grid-template-columns: 170px minmax\(0, 1fr\);[\s\S]*?\.broker-host-control select[\s\S]*?\.broker-host-control input/);
        assert.match(styles, /\.mqtt-host-port-row \{ grid-template-columns: minmax\(0, 1fr\) 96px; \}/);
        assert.match(app, /const SECURE_CLOUD_MQTT_PRESETS = new Set/);
        assert.match(app, /SECURE_CLOUD_MQTT_PRESETS\.has\(presetName\)[\s\S]*?'mqtts:\/\/' \+ enteredHost/);
        assert.match(app, /function startDetection/);
        assert.match(app, /selectMonitorTransport\('direct'\);[\s\S]*?navigateToRoute\('tool-monitor'\)/);
        assert.match(configurePage, /js-start-detection/);
        assert.match(index, /js-connect-direct/);
        assert.match(index, /class="conn-pill conn-disconnected js-header-connect"/);
        assert.match(
            app,
            /\$\('\.js-header-connect'\)\.addEventListener\('click',[\s\S]*?window\.selectMonitorTransport\('direct'\);[\s\S]*?if \(route === 'tool-monitor'\)[\s\S]*?navigateToRoute\('tool-monitor'\);/
        );
        assert.match(toolFragments, /js-has-live/);
        assert.match(app, /input_mode: connectionInputMode\(\)/);
    });

    it('preserves write-only MQTT credentials and confirms destructive MQTT removal', () => {
        assert.doesNotMatch(toolContent.configure, /id="cfg-wifi-pass"|id="cfg-wifi-pass-clear"/);
        assert.match(toolContent.configure, /id="cfg-mqtt-credentials-clear"/);
        assert.ok((toolContent.configure.match(/class="config-advanced"/g) || []).length >= 1);
        assert.match(styles, /\[data-page="tool-configure"\] \.field-row \{ grid-template-columns: minmax\(0, 1fr\); \}/);
        assert.match(app, /function syncConfigureMqttCredentialMode\(\) \{[\s\S]*?username\.disabled = clear;[\s\S]*?password\.disabled = clear \|\| isFlespi;[\s\S]*?username\.value = '';[\s\S]*?password\.value = '';/);
        assert.match(app, /const mqttParams = \{ host, port, topic_prefix: topicPrefix \};[\s\S]*?if \(username \|\| clearCredentials\)[\s\S]*?if \(password \|\| clearCredentials\)/);
        assert.doesNotMatch(app, /'set_mqtt_config', \{[\s\S]*?username,\s*password,/);
        assert.match(index, /class="modal-backdrop js-config-clear-modal" hidden/);
        assert.match(index, /class="btn-danger js-config-clear-confirm"/);
        assert.match(app, /function openConfigClearDialog\(kind, returnFocus\)/);
        assert.match(app, /if \(!await openConfigClearDialog\('mqtt', document\.activeElement\)\) return/);
        assert.match(app, /closeConfigClearDialog\(true\)/);
    });

    it('keeps Game and Theremin demo sessions on the current tool', () => {
        assert.equal((toolFragments.match(/data-open-view="live"/g) || []).length, 3);
        assert.match(app, /function connectDemo\(openView = ''\)[\s\S]*?if \(openView === 'live'\) rememberLiveDestination\(\)/);
        assert.match(app, /if \(openView === 'live'\) completeLiveConnectionNavigation\(\)/);
        assert.match(app, /const selectedMode = \['direct', 'demo', 'relay'\]\.includes\(mode\) \? mode : 'direct'/);
        assert.match(app, /if \(previousMode === 'demo'\)[\s\S]*?espectre-connection-picker[\s\S]*?picker\.select\('direct'\)/);
    });

    it('offers the shared connection picker from every connected browser tool', () => {
        for (const tool of ['configure', 'monitor', 'raw-csi', 'theremin', 'game']) {
            assert.match(toolContent[tool], new RegExp(`<espectre-connection-picker[^>]*data-surface="${tool}"`));
        }
        assert.match(app, /openView: connectButton\.closest\('espectre-direct-connect'\)\?\.dataset\.openView/);
        assert.match(app, /else if \(!LIVE_EXPERIENCE_ROUTES\.has\(route\)\)/);
    });

    it('returns live connection flows to their requesting experience', () => {
        assert.match(app, /const LIVE_EXPERIENCE_ROUTES = new Set\(\['tool-game', 'tool-theremin'\]\)/);
        assert.match(app, /function rememberLiveDestination/);
        assert.match(app, /function completeLiveConnectionNavigation/);
        assert.match(app, /const destination = pendingLiveDestination;[\s\S]*?pendingLiveDestination = ''/);
        assert.match(app, /function startDetection\(preferredTransport = ''\) \{\s*rememberLiveDestination\(\)/);
        assert.match(app, /if \(pendingLiveDestination\) completeLiveConnectionNavigation\(\)/);
        assert.match(
            app,
            /\$\('\.js-header-connect'\)\.addEventListener\('click',[\s\S]*?pendingLiveDestination = '';[\s\S]*?navigateToRoute\('tool-monitor'\)/
        );
    });

    it('reuses active Direct HTTP and Demo sessions for Raw CSI', () => {
        const rawPage = toolContent['raw-csi'];
        const rawClient = app.match(/\/\* =+ raw CSI \*\/[\s\S]*?function gameInit/)?.[0] || '';
        assert.match(rawPage, /class="js-raw-csi-onboarding"[\s\S]*?<espectre-connection-picker data-surface="raw-csi"/);
        assert.match(rawPage, /js-raw-csi-unavailable/);
        assert.match(rawPage, /js-raw-csi-choose-device/);
        assert.match(rawPage, /js-raw-pps/);
        assert.match(rawPage, /raw-csi-stats[\s\S]*js-raw-pps[\s\S]*js-raw-fresh/);
        for (const metric of ['snr', 'capture-interval']) {
            assert.match(rawPage, new RegExp(`js-raw-${metric}`));
        }
        assert.equal((rawPage.match(/js-raw-csi-toggle/g) || []).length, 1);
        assert.ok(rawPage.indexOf('js-raw-csi-toggle') < rawPage.indexOf('js-raw-visualization-select'));
        assert.ok(rawPage.indexOf('raw-csi-visualizer') < rawPage.indexOf('raw-csi-diagnostics'));
        assert.match(rawPage, /<details class="device-live-diagnostics raw-csi-diagnostics">[\s\S]*raw-csi-stats/);
        assert.match(app, /function rawCsiDirectReady\(\) \{\s*return conn\.mode === 'direct' && conn\.status === 'connected' && Boolean\(directClient\?\.connected\)/);
        assert.match(rawClient, /conn\.status !== 'connected' \|\| !\['direct', 'demo'\]\.includes\(conn\.mode\)[\s\S]*onboarding\.hidden = false/);
        assert.match(rawClient, /if \(conn\.mode === 'demo'\) \{[\s\S]*rawCsiSetAvailable\(true\)/);
        assert.match(rawClient, /function rawCsiStartDemo\(targetPps\)/);
        assert.match(rawClient, /function rawCsiCollectRadioMetrics\(view\)/);
        assert.match(rawClient, /function rawCsiCollectCaptureInterval\(captureTicksUs\)/);
        assert.match(rawClient, /function rawCsiFlushMetrics\(\)/);
        assert.match(rawClient, /setInterval\(rawCsiFlushMetrics, 1000\)/);
        assert.match(rawClient, /if \(conn\.mode === 'demo'\) \{\s*rawCsiStartDemo\(100\);\s*return;/);
        assert.match(rawClient, /const client = directClient;[\s\S]*client\.request\('start_raw_stream'/);
        assert.doesNotMatch(rawClient, /makeDirectClient|client\.connect\(|client\.handshake\(|client\.close\(/);
        assert.match(rawClient, /new window\.ESPectreRawCsiParser\(session\.session_id\)/);
        assert.match(rawClient, /rawCsi\.parser\.append\(chunk\)\.forEach/);
        assert.match(rawClient, /state: 'idle'/);
        assert.match(rawClient, /if \(rawCsi\.state === 'stopping'\) return rawCsi\.stopPromise/);
        assert.match(rawClient, /const pendingStart = rawCsi\.startRequest[\s\S]*await pendingStart/);
        assert.match(rawClient, /rawCsi\.generation !== generation \|\| rawCsi\.state !== 'starting'/);
        assert.match(rawClient, /function rawCsiToggle\(\) \{[\s\S]*rawCsiStart\(\)[\s\S]*rawCsiStop\(\)/);
        assert.match(app, /previousRoute === 'tool-raw-csi'[\s\S]*void window\.rawCsiStop\(\)/);
        assert.match(app, /rawCapability\?\.protocol_version === 1[\s\S]*rawCapability\?\.marker === '👻'/);
    });

    it('shows one selectable Raw CSI visualization at a time', () => {
        const rawPage = toolContent['raw-csi'];
        const rawClient = app.match(/\/\* =+ raw CSI \*\/[\s\S]*?function gameInit/)?.[0] || '';
        const visualizationValues = [
            'subcarrier-amplitudes',
            'csi-amplitude-surface',
            'channel-profile-deviation',
            'iq-constellation',
            'relative-phase-trails'
        ];
        assert.equal((rawPage.match(/class="js-raw-visualization"/g) || []).length, 1);
        assert.equal((rawPage.match(/<option value=/g) || []).length, visualizationValues.length);
        assert.match(rawPage, /<select id="raw-csi-visualization" class="js-raw-visualization-select" aria-label=/);
        for (const value of visualizationValues) {
            assert.match(rawPage, new RegExp(`<option value="${value}">`));
            assert.match(rawClient, new RegExp(`'${value}'`));
        }
        assert.match(rawClient, /function rawCsiSelectVisualization\(value\)/);
        assert.match(rawClient, /canvas\.setAttribute\('aria-label', metadata\.ariaLabel\)/);
        assert.match(rawClient, /rawCsiNormalizeProfile\(amplitudes\)/);
        assert.match(rawClient, /function rawCsiVisibleSubcarriers\(amplitudes\)/);
        assert.match(rawClient, /if \(amplitudes\.length === 64\) return RAW_CSI_LIVE_SUBCARRIERS/);
        assert.match(rawClient, /Array\.from\(\{ length: 57 \},[\s\S]*?index \+ 4\)\.filter\(\(index\) => index !== 32\)/);
        assert.match(rawClient, /while \(first < amplitudes\.length && amplitudes\[first\] <= 0\)/);
        assert.match(rawClient, /while \(last >= first && amplitudes\[last\] <= 0\)/);
        assert.match(rawClient, /\.filter\(\(index\) => amplitudes\[index\] > 0\)/);
        assert.match(rawClient, /function rawCsiUpdateAmplitudeMaximum\(amplitudes\)/);
        assert.match(rawClient, /if \(rawCsi\.amplitudeMaximum > 0\) return/);
        assert.match(rawClient, /if \(peak <= 0\) return/);
        assert.match(rawClient, /peak \* RAW_CSI_AMPLITUDE_SCALE_HEADROOM \/ RAW_CSI_AMPLITUDE_SCALE_STEP/);
        assert.match(rawClient, /rawCsi\.amplitudeMaximum = 0/);
        assert.match(rawClient, /rawCsiUpdateAmplitudeMaximum\(amplitudes\)/);
        assert.match(rawClient, /rawCsiPushBounded\(rawCsi\.amplitudeFrames, amplitudes\.slice\(\), RAW_CSI_VISUAL_HISTORY\)/);
        assert.match(rawClient, /function rawCsiDrawSubcarrierAmplitudes\(context, canvas\)/);
        assert.match(rawClient, /const firstHistorySlot = RAW_CSI_VISUAL_HISTORY - frames\.length;[\s\S]*?\(firstHistorySlot \+ index\) \* width \/ \(RAW_CSI_VISUAL_HISTORY - 1\)/);
        assert.match(rawClient, /activeCount} SUBCARRIER AMPLITUDES/);
        assert.equal((rawClient.match(
            /const maximum = Math\.max\(RAW_CSI_AMPLITUDE_SCALE_STEP, rawCsi\.amplitudeMaximum\)/g
        ) || []).length, 2);
        assert.match(rawPage, /<option value="csi-amplitude-surface">CSI amplitude surface<\/option>/);
        assert.match(rawClient, /const RAW_CSI_AMPLITUDE_SURFACE_PACKETS = 96;/);
        assert.match(rawClient, /function rawCsiAmplitudeSurfaceColor\(value, minimum, maximum\)/);
        assert.match(rawClient, /function rawCsiDrawAmplitudeSurface\(context, canvas\)/);
        assert.match(rawClient, /rawCsiPushBounded\([\s\S]*?rawCsi\.amplitudePackets,[\s\S]*?RAW_CSI_AMPLITUDE_SURFACE_PACKETS/);
        assert.match(rawClient, /const subcarriers = rawCsiVisibleSubcarriers\(latest\)/);
        assert.match(rawClient, /const frequency = \(lastSubcarrier - subcarrier\) \/ subcarrierSpan/);
        assert.match(rawClient, /String\(Math\.round\(subcarrier - firstSubcarrier\)\)/);
        assert.match(rawClient, /for \(let tick = 1; tick <= 3; tick \+= 1\) \{[\s\S]*?const packetPosition = tick \/ 3/);
        assert.match(rawClient, /const amplitudeTop = project\(firstSubcarrier, 0, maximum\)/);
        assert.match(rawClient, /const point = project\(firstSubcarrier, 0, amplitude\)/);
        assert.match(rawClient, /context\.fillStyle = rawCsiAmplitudeSurfaceColor\(amplitude, floor, peak\)/);
        assert.match(rawClient, /context\.fillText\('Amplitude', 0, 0\)/);
        assert.match(rawClient, /'Subcarrier',[\s\S]*?'Packets',/);
        assert.match(rawPage, /<option value="channel-profile-deviation">Channel profile deviation<\/option>/);
        assert.match(rawClient, /title: 'Channel profile deviation'/);
        assert.match(rawClient, /Plots raw I\/Q samples collected during the last second\./);
        assert.match(rawClient, /Trail spread is amplified 5×\./);
        assert.match(rawClient, /Math\.log\(\(profile\[index\] \+ 0\.05\) \/ \(baseline \+ 0\.05\)\)/);
        assert.match(rawClient, /function rawCsiRelativePhase\(iValues, qValues, profile\)/);
        assert.match(rawClient, /const RAW_CSI_CHANNEL_PROFILE_DEVIATION_GAIN = 5;/);
        assert.match(rawClient, /function rawCsiDrawChannelProfileDeviation\(context, canvas\)/);
        assert.match(rawClient, /RAW_CSI_RELATIVE_PHASE_TRAIL_GAIN/);
        assert.match(rawClient, /function rawCsiDrawRelativePhaseTrails\(context, canvas\)/);
        assert.doesNotMatch(rawClient, /function rawCsiUpdatePacketRate\(received\)/);
        assert.match(rawClient, /function rawCsiDrawIqConstellation\(context, canvas\)/);
        assert.match(rawClient, /const RAW_CSI_IQ_WINDOW_US = 1000000;/);
        assert.match(rawClient, /const RAW_CSI_IQ_EXTENT = 128;/);
        assert.match(rawClient, /captureTicksUs - rawCsi\.iqTimestampsUs\[0\] > RAW_CSI_IQ_WINDOW_US/);
        assert.match(rawClient, /context\.fillText\('1 SECOND WINDOW', centerX, top - 10\)/);
        assert.match(rawClient, /const activeSubcarriers = rawCsiVisibleSubcarriers\(amplitudes\)/);
        assert.doesNotMatch(rawClient, /const selectedSubcarriers = RAW_CSI_SELECTED_SUBCARRIERS/);
        assert.doesNotMatch(rawClient, /context\.fillText\(`SC \$\{subcarrier\}`/);
        assert.match(rawClient, /context\.fillStyle = `hsl\(\$\{hue\} 94% 68%\)`;/);
        assert.match(rawClient, /qValues\[index\] = view\.getInt8\(offset\)/);
        assert.match(rawClient, /iValues\[index\] = view\.getInt8\(offset \+ 1\)/);
        assert.match(rawClient, /new ResizeObserver\(rawCsiResizeVisualization\)/);
        assert.match(rawClient, /requestAnimationFrame\(rawCsiRender\)/);
        assert.match(rawClient, /const RAW_CSI_RENDER_INTERVAL_MS = 1000 \/ 30;/);
        assert.doesNotMatch(rawClient, /function rawCsiDrawHeatmap\(context, canvas\)/);
        assert.match(rawClient, /const colors = \[\[255, 66, 92\], \[52, 211, 109\], \[30, 211, 238\]\]/);
    });

    it('calibrates Game and Theremin to the detector evaluation cadence', () => {
        assert.match(app, /const EVALUATION_INTERVAL_MS_DEFAULT = 250/);
        assert.match(app, /function applySensingCadence/);
        assert.match(app, /function evaluationIntervalMs/);
        assert.match(app, /snapshot\.evaluation_interval_ms/);
        assert.match(app, /snapshot\.csi_target_pps/);
        assert.match(app, /demoTimer = setInterval\(\(\) => \{[\s\S]*?\}, evaluationIntervalMs\(\)\)/);
        assert.match(app, /function gameSensingActive/);
        assert.match(app, /return conn\.movement >= gameThreshold\(\)/);
        assert.match(app, /const tau = evaluationIntervalMs\(\) \/ 2000/);
        assert.match(app, /function monitorChartMaxPoints/);
        assert.match(app, /const DIAGNOSTICS_POLL_INTERVAL_MS = 1000/);
        assert.match(app, /setInterval\(monitorRequestStats, interval\)/);
        assert.match(styles, /transition: width \.25s linear/);
    });

    it('runs Game as a binary motion-flight endless runner', () => {
        const gameScreen = toolContent.game.match(/<div class="game-screen">[\s\S]*?<\/div>\s*<div class="game-msg/)?.[0] || '';
        const gameFinish = app.slice(app.indexOf('function gameFinish'), app.indexOf('function gameSetFlight'));
        const gameUpdate = app.slice(app.indexOf('function gameUpdate(dt)'), app.indexOf('function gameSensingActive'));
        assert.match(toolContent.game, /class="game-canvas js-game-canvas"/);
        assert.match(styles, /\.game-stage \{[\s\S]*?width: 100%;[\s\S]*?max-width: none;/);
        assert.match(styles, /\.game-canvas \{[\s\S]*?height: clamp\(250px, 40vw, 440px\);/);
        assert.match(gameScreen, /class="game-status"[\s\S]*js-game-score[\s\S]*js-game-orbs[\s\S]*js-game-distance[\s\S]*js-game-best/);
        assert.match(gameScreen, /class="game-play js-game-start"/);
        assert.match(gameScreen, /class="game-sound js-game-sound"[\s\S]*?aria-pressed="true"/);
        assert.equal((toolContent.game.match(/js-game-start/g) || []).length, 1);
        assert.match(gameScreen, /js-game-motion-fill[\s\S]*js-game-motion-threshold/);
        assert.match(app, /function renderGameMotionGauge/);
        assert.match(app, /fill\.style\.height = Math\.round\(energyFraction\(\) \* 100\) \+ '%'/);
        assert.match(app, /play\.hidden = phase === 'ready' \|\| phase === 'running'/);
        assert.match(app, /const GAME_ORB_POINTS = 100/);
        assert.match(app, /function gameFlightY/);
        assert.match(app, /function gameOrbY\(lane\)/);
        assert.match(app, /y: gameOrbY\(lane\),\s*lane,/);
        assert.match(app, /entity\.y = gameOrbY\(entity\.lane\)/);
        assert.match(app, /Math\.min\(maxAir, Math\.max\(0, air \* scaleY\)\)/);
        assert.match(app, /function gameSpawnCourse/);
        assert.match(app, /gameAddOrb\([^;]+, 'high'\)/);
        assert.match(app, /gameAddOrb\([^;]+, 'low'\)/);
        assert.match(app, /gameAddObstacle\('aerial_spikes'/);
        assert.match(app, /function gameRectsOverlap/);
        assert.match(app, /function gameOrbTouchesPlayer/);
        assert.match(app, /game\.raf = requestAnimationFrame\(gameFrame\)/);
        assert.match(app, /const targetY = game\.flightActive \? gameFlightY\(\)/);
        assert.match(app, /const responseSeconds = game\.flightActive \? 0\.15 : 0\.18/);
        assert.match(app, /function gameUpdatePlayer\(dt\)/);
        assert.match(app, /function gamePreviewFrame\(now\)/);
        assert.match(app, /game\.phase === 'idle' \|\| game\.phase === 'ready'/);
        assert.match(app, /function gameStartPreview\(\)/);
        assert.match(app, /gameStartPreview\(\);/);
        assert.match(app, /const canFloat = game\.phase === 'idle' \|\| game\.phase === 'ready' \|\| game\.phase === 'running'/);
        assert.match(app, /const bobAmplitude = game\.flightActive \? 2\.6/);
        assert.match(app, /gameSetFlight\(gameSensingActive\(\)\)/);
        assert.match(app, /function gameDemoFlight/);
        assert.match(app, /\['idle', 'ready', 'running'\]\.includes\(game\.phase\)/);
        assert.match(gameUpdate, /const player = game\.player/);
        assert.match(app, /function gameScore\(\)/);
        assert.match(app, /const GAME_MUSIC_NOTES = \[/);
        assert.match(app, /function gameStartMusic\(\)/);
        assert.match(app, /function gameStopMusic\(\)/);
        assert.match(app, /function gameStartMotionSound\(\)/);
        assert.match(app, /function gameUpdateMotionSound\(dt\)/);
        assert.match(app, /const frequency = 96 \* Math\.pow\(2, gameAudio\.motionSmoothed \* 1\.8\);/);
        assert.match(gameUpdate, /gameUpdateMotionSound\(dt\)/);
        assert.match(app, /function gamePlaySound\(kind\)/);
        assert.match(app, /gamePlaySound\('start'\)/);
        assert.match(app, /gamePlaySound\('orb'\)/);
        assert.match(gameFinish, /gamePlaySound\('hit'\)/);
        assert.match(app, /function gameToggleSound\(\)/);
        assert.match(app, /js-game-sound'\)\.addEventListener\('click', gameToggleSound\)/);
        assert.match(styles, /\.game-sound\[aria-pressed="false"\]/);
        assert.match(app, /Math\.floor\(game\.distance\) \+ game\.orbs \* GAME_ORB_POINTS/);
        assert.match(app, /game\.score = gameScore\(\)/);
        assert.match(app, /game\.scrollX \+= travel/);
        assert.match(app, /entity\.x -= travel/);
        assert.match(app, /game\.scrollX \* 0\.18/);
        assert.match(app, /- game\.scrollX\) % width/);
        assert.match(app, /const GAME_FACTORY_IMAGE_SOURCES = Object\.freeze\(\[[\s\S]*hardware-factory\.avif[\s\S]*hardware-factory\.webp/);
        assert.match(app, /function gameLoadFactoryImage\(\)/);
        assert.match(app, /if \(routeAtStart === 'tool-game'\) \{\s*void window\.gameLoadFactoryImage\(\)/);
        assert.match(app, /function gameDrawFactoryBackdrop/);
        assert.match(app, /function gameDrawFactoryParallax/);
        assert.match(app, /game\.scrollX \* 0\.12/);
        assert.match(app, /game\.scrollX \* 0\.24/);
        assert.match(app, /function gameDrawChip/);
        const factoryWebp = readFileSync(new URL('../../docs/web/assets/images/game/hardware-factory.webp', import.meta.url));
        const factoryAvif = readFileSync(new URL('../../docs/web/assets/images/game/hardware-factory.avif', import.meta.url));
        assert.equal(factoryWebp.subarray(0, 4).toString('ascii'), 'RIFF');
        assert.equal(factoryWebp.subarray(8, 12).toString('ascii'), 'WEBP');
        assert.ok(factoryWebp.length < 100000);
        assert.ok(factoryAvif.length < factoryWebp.length);
        assert.match(app, /if \(obstacleHit\) gameFinish\(\)/);
    });
});
