/*
 * ESPectre - Unit Test Application Main
 * 
 * This is the main entry point for the unit test application.
 * 
 * Author: Francesco Pace <francesco.pace@gmail.com>
 * License: GPLv3
 */

#include <stdio.h>
#include "unity.h"
#include "unity_test_runner.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

// Declare test descriptor structures (generated by TEST_CASE macro)
// Filter tests
extern test_desc_t test_desc_17;   // Adaptive normalizer respects enabled flag
extern test_desc_t test_desc_63;   // Butterworth filter initialization
extern test_desc_t test_desc_73;   // Hampel filter removes outliers
extern test_desc_t test_desc_83;   // Filter buffer operations
extern test_desc_t test_desc_107;  // Adaptive normalizer update (from test_filters.c)
// Wavelet tests
extern test_desc_t test_desc_16;   // Wavelet filter initialization
extern test_desc_t test_desc_29;   // Wavelet soft thresholding
extern test_desc_t test_desc_47;   // Wavelet hard thresholding
extern test_desc_t test_desc_65;   // Wavelet denoising reduces noise
extern test_desc_t test_desc_108;  // Wavelet streaming mode
extern test_desc_t test_desc_130;  // Wavelet handles invalid parameters
extern test_desc_t test_desc_148;  // Wavelet level clamping
extern test_desc_t test_desc_166;  // Wavelet db4 coefficients sum correctly
extern test_desc_t test_desc_184;  // Wavelet preserves DC component
// Feature tests
extern test_desc_t test_desc_18;   // CSI variance calculation
extern test_desc_t test_desc_28;   // Skewness calculation
extern test_desc_t test_desc_38;   // Kurtosis calculation
extern test_desc_t test_desc_48;   // Entropy calculation
extern test_desc_t test_desc_58;   // IQR calculation
extern test_desc_t test_desc_68;   // Spatial variance calculation
extern test_desc_t test_desc_78;   // Spatial correlation calculation
extern test_desc_t test_desc_89;   // Spatial gradient calculation
extern test_desc_t test_desc_98;   // Mock CSI data generation
// Calibration tests
extern test_desc_t test_desc_26;   // Calibration end-to-end with mock data
extern test_desc_t test_desc_172;  // Features differ between baseline and movement
extern test_desc_t test_desc_23;   // Calibration with real CSI data
// Detection approaches comparison
extern test_desc_t test_desc_55;   // Compare detection approaches on real data

void app_main(void)
{
    printf("\n");
    printf("╔═════════════════════════════════════╗\n");
    printf("║       🛜  E S P e c t r e 👻         ║\n");
    printf("║              Unit Tests             ║\n");
    printf("╚═════════════════════════════════════╝\n");
    printf("\n");
    
    // Manually register all tests (constructor attribute doesn't work in ESP-IDF)
    // Filter tests
    unity_testcase_register(&test_desc_17);
    unity_testcase_register(&test_desc_63);
    unity_testcase_register(&test_desc_73);
    unity_testcase_register(&test_desc_83);
    unity_testcase_register(&test_desc_107);
    // Wavelet tests
    unity_testcase_register(&test_desc_16);
    unity_testcase_register(&test_desc_29);
    unity_testcase_register(&test_desc_47);
    unity_testcase_register(&test_desc_65);
    unity_testcase_register(&test_desc_108);
    unity_testcase_register(&test_desc_130);
    unity_testcase_register(&test_desc_148);
    unity_testcase_register(&test_desc_166);
    unity_testcase_register(&test_desc_184);
    // Feature tests
    unity_testcase_register(&test_desc_18);
    unity_testcase_register(&test_desc_28);
    unity_testcase_register(&test_desc_38);
    unity_testcase_register(&test_desc_48);
    unity_testcase_register(&test_desc_58);
    unity_testcase_register(&test_desc_68);
    unity_testcase_register(&test_desc_78);
    unity_testcase_register(&test_desc_89);
    unity_testcase_register(&test_desc_98);
    // Calibration tests
    unity_testcase_register(&test_desc_26);
    unity_testcase_register(&test_desc_172);
    unity_testcase_register(&test_desc_23);
    // Detection approaches comparison
    unity_testcase_register(&test_desc_55);
    
    // Run all tests automatically
    printf("Running all tests automatically...\n\n");
    unity_run_all_tests();
    
    // Check test results and display appropriate message
    if (Unity.TestFailures == 0) {
        printf("\n✅ All tests passed!\n");
    } else {
        printf("\n❌ Tests failed: %d failure(s)\n", Unity.TestFailures);
    }
    printf("Press Ctrl+] to exit monitor\n");
    
    // Prevent reboot loop - just wait here
    while(1) {
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}
