/*
 * ESPectre - Unit Test Application Main
 * 
 * ⚠️  AUTO-GENERATED FILE
 * Generated by: convert_tests.py
 * 
 * To regenerate: python3 convert_tests.py
 * 
 * Author: Francesco Pace <francesco.pace@gmail.com>
 * License: GPLv3
 */

#include <stdio.h>
#include "unity.h"
#include "unity_test_runner.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

// Test descriptors (using symbolic names)
// test_calibration.c
extern test_desc_t test_desc_calibration_end_to_end_with_mock_data;
extern test_desc_t test_desc_features_differ_between_baseline_and_movement;
// test_detection_approaches.c
extern test_desc_t test_desc_compare_detection_approaches_on_real_data;
// test_doppler_features.c
extern test_desc_t test_desc_doppler_features_classification_performance;
// test_feature_classification_performance.c
extern test_desc_t test_desc_feature_classification_performance_on_real_data;
// test_features.c
extern test_desc_t test_desc_csi_variance_calculation;
extern test_desc_t test_desc_skewness_calculation;
extern test_desc_t test_desc_kurtosis_calculation;
extern test_desc_t test_desc_entropy_calculation;
extern test_desc_t test_desc_iqr_calculation;
extern test_desc_t test_desc_spatial_variance_calculation;
extern test_desc_t test_desc_spatial_correlation_calculation;
extern test_desc_t test_desc_spatial_gradient_calculation;
extern test_desc_t test_desc_mock_csi_data_generation;
// test_filters.c
extern test_desc_t test_desc_adaptive_normalizer_respects_enabled_flag;
extern test_desc_t test_desc_butterworth_filter_initialization;
extern test_desc_t test_desc_hampel_filter_removes_outliers;
extern test_desc_t test_desc_filter_buffer_operations;
extern test_desc_t test_desc_adaptive_normalizer_update;
extern test_desc_t test_desc_filter_pipeline_with_wavelet_integration;
extern test_desc_t test_desc_filter_pipeline_with_wavelet_disabled;
// test_pca_subcarrier.c
extern test_desc_t test_desc_pca_subcarrier_analysis_on_real_data;
// test_real_calibration.c
extern test_desc_t test_desc_calibration_with_real_csi_data;
// test_wavelet.c
extern test_desc_t test_desc_wavelet_filter_initialization;
extern test_desc_t test_desc_wavelet_soft_thresholding;
extern test_desc_t test_desc_wavelet_hard_thresholding;
extern test_desc_t test_desc_wavelet_denoising_reduces_noise;
extern test_desc_t test_desc_wavelet_streaming_mode;
extern test_desc_t test_desc_wavelet_handles_invalid_parameters;
extern test_desc_t test_desc_wavelet_level_clamping;
extern test_desc_t test_desc_wavelet_db4_coefficients_sum_correctly;
extern test_desc_t test_desc_wavelet_preserves_dc_component;

void app_main(void)
{
    printf("\n");
    printf("╔═════════════════════════════════════╗\n");
    printf("║       🛜  E S P e c t r e 👻         ║\n");
    printf("║              Unit Tests             ║\n");
    printf("╚═════════════════════════════════════╝\n");
    printf("\n");
    
    // Register all tests
    /*
    unity_testcase_register(&test_desc_mock_csi_data_generation);
    unity_testcase_register(&test_desc_features_differ_between_baseline_and_movement);
    unity_testcase_register(&test_desc_csi_variance_calculation);
    unity_testcase_register(&test_desc_skewness_calculation);
    unity_testcase_register(&test_desc_kurtosis_calculation);
    unity_testcase_register(&test_desc_entropy_calculation);
    unity_testcase_register(&test_desc_iqr_calculation);
    unity_testcase_register(&test_desc_spatial_variance_calculation);
    unity_testcase_register(&test_desc_spatial_correlation_calculation);
    unity_testcase_register(&test_desc_spatial_gradient_calculation);
    unity_testcase_register(&test_desc_butterworth_filter_initialization);
    unity_testcase_register(&test_desc_hampel_filter_removes_outliers);
    unity_testcase_register(&test_desc_filter_buffer_operations);
    unity_testcase_register(&test_desc_filter_pipeline_with_wavelet_integration);
    unity_testcase_register(&test_desc_filter_pipeline_with_wavelet_disabled);
    unity_testcase_register(&test_desc_adaptive_normalizer_update);
    unity_testcase_register(&test_desc_adaptive_normalizer_respects_enabled_flag);
    unity_testcase_register(&test_desc_wavelet_filter_initialization);
    unity_testcase_register(&test_desc_wavelet_soft_thresholding);
    unity_testcase_register(&test_desc_wavelet_hard_thresholding);
    unity_testcase_register(&test_desc_wavelet_denoising_reduces_noise);
    unity_testcase_register(&test_desc_wavelet_streaming_mode);
    unity_testcase_register(&test_desc_wavelet_handles_invalid_parameters);
    unity_testcase_register(&test_desc_wavelet_level_clamping);
    unity_testcase_register(&test_desc_wavelet_db4_coefficients_sum_correctly);
    unity_testcase_register(&test_desc_wavelet_preserves_dc_component);
    unity_testcase_register(&test_desc_calibration_end_to_end_with_mock_data);
    unity_testcase_register(&test_desc_pca_subcarrier_analysis_on_real_data);
    unity_testcase_register(&test_desc_compare_detection_approaches_on_real_data);
    */
   
    unity_testcase_register(&test_desc_calibration_with_real_csi_data);
    unity_testcase_register(&test_desc_doppler_features_classification_performance);
    unity_testcase_register(&test_desc_feature_classification_performance_on_real_data);
    
    // Run all tests
    printf("Running all tests automatically...\n\n");
    unity_run_all_tests();
    
    // Check results
    if (Unity.TestFailures == 0) {
        printf("\n✅ All tests passed!\n");
    } else {
        printf("\n❌ Tests failed: %d failure(s)\n", Unity.TestFailures);
    }
    printf("Press Ctrl+] to exit monitor\n");
    
    // Prevent reboot loop
    while(1) {
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}
