/*
 * ESPectre - HighAccuracyDetector Unit Tests
 *
 * Tests the HighAccuracyDetector class implementing BaseDetector interface.
 * Validates MLP inference accuracy against reference model outputs.
 * Test data is loaded from ml_test_data.npz (auto-generated by training script).
 *
 * Author: Francesco Pace <francesco.pace@gmail.com>
 * SPDX-License-Identifier: GPL-3.0-only
 * Commercial licensing available under separate agreement; see LICENSING.md.
 */
#include "test_harness.h"
#include <cstdint>
#include <cstring>
#include <cmath>
#include <algorithm>
#include <vector>
#define private public
#define protected public
#include "high_accuracy_detector.h"
#undef protected
#undef private
#include "csi_features.h"
#include "ml_weights.h"
#include "detector_state_contract.h"
#include "esphome/core/log.h"
#include "cnpy.h"

using namespace espectre;

static const char *TEST_TAG = "test_high_accuracy_detector";

// ============================================================================
// TEST DATA (loaded from ml_test_data.npz at runtime)
// ============================================================================

#define ML_TEST_DATA_PATH "../../data/auto_generated/ml_test_data.npz"

// Sample indices to test (spread across the dataset)
static const int SAMPLE_INDICES[] = {0, 100, 500, 1000, 2000, 2500};
static const int NUM_SAMPLE_INDICES = sizeof(SAMPLE_INDICES) / sizeof(SAMPLE_INDICES[0]);

// Loaded test data
static std::vector<std::vector<float>> test_features;
static std::vector<float> test_expected;
static std::vector<int> test_labels;
static int num_test_samples = 0;
static bool data_loaded = false;

static void load_test_data() {
    if (data_loaded) return;
    
    cnpy::npz_t npz = cnpy::npz_load(ML_TEST_DATA_PATH);
    
    // Load features: shape [N, num_features]
    cnpy::NpyArray& feat_arr = npz["features"];
    int total_samples = static_cast<int>(feat_arr.shape[0]);
    int num_features = static_cast<int>(feat_arr.shape[1]);
    const float* feat_data = feat_arr.data<float>();
    TEST_ASSERT_EQUAL_INT_MESSAGE(ML_MODEL_INPUT_SIZE, num_features,
                                  "ml_test_data feature count must match exported model input size");
    
    // Load expected outputs: shape [N]
    cnpy::NpyArray& exp_arr = npz["expected_outputs"];
    const float* exp_data = exp_arr.data<float>();
    
    // Load labels: shape [N]
    cnpy::NpyArray& label_arr = npz["labels"];
    const int32_t* label_data = label_arr.data<int32_t>();
    
    // Extract samples at specified indices
    for (int i = 0; i < NUM_SAMPLE_INDICES; i++) {
        int idx = SAMPLE_INDICES[i];
        if (idx >= total_samples) break;
        
        std::vector<float> features(num_features);
        for (int j = 0; j < num_features; j++) {
            features[j] = feat_data[idx * num_features + j];
        }
        test_features.push_back(features);
        test_expected.push_back(exp_data[idx]);
        test_labels.push_back(static_cast<int>(label_data[idx]));
        num_test_samples++;
    }
    
    ESP_LOGI(TEST_TAG, "Loaded %d test samples from %s (total: %d)", 
             num_test_samples, ML_TEST_DATA_PATH, total_samples);
    data_loaded = true;
}

void setUp(void) { load_test_data(); }
void tearDown(void) {}

// ============================================================================
// INITIALIZATION TESTS
// ============================================================================

void test_high_accuracy_detector_default_constructor(void) {
    HighAccuracyDetector detector;
    
    TEST_ASSERT_EQUAL(DETECTOR_DEFAULT_WINDOW_SIZE, detector.get_window_size());
    TEST_ASSERT_EQUAL_FLOAT(HIGH_ACCURACY_DEFAULT_THRESHOLD, detector.get_threshold());
    TEST_ASSERT_EQUAL(MotionState::IDLE, detector.get_state());
    TEST_ASSERT_EQUAL(0, detector.get_total_packets());
}

void test_high_accuracy_detector_custom_constructor(void) {
    HighAccuracyDetector detector(100, 0.7f);
    
    TEST_ASSERT_EQUAL(100, detector.get_window_size());
    TEST_ASSERT_EQUAL_FLOAT(0.7f, detector.get_threshold());
}

void test_high_accuracy_detector_get_name(void) {
    HighAccuracyDetector detector;
    
    TEST_ASSERT_EQUAL_STRING("High Accuracy", detector.get_name());
}

void test_ml_production_feature_schema(void) {
    const uint8_t expected[] = {
        ML_FEAT_TURB_IQR_OVER_MEAN_AGGR,
        ML_FEAT_TURB_AUTOCORR,
        ML_FEAT_TURB_ZCR,
        ML_FEAT_L1_DELTA_LAG_RATIO,
        ML_FEAT_CHAN_SHAPE_SPREAD_SUBBAND,
        ML_FEAT_CHAN_SHAPE_COHERENT_INNOVATION_ENERGY,
        ML_FEAT_CHAN_SHAPE_EXCESS_PATH,
        ML_FEAT_CHAN_SHAPE_SUBBAND_KENDALL_LAG_EXCESS,
    };
    TEST_ASSERT_EQUAL_UINT8(sizeof(expected), ML_MODEL_INPUT_SIZE);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(
        expected, ML_FEATURE_IDS, ML_MODEL_INPUT_SIZE);

    HighAccuracyDetector detector;
    TEST_ASSERT_TRUE(detector.uses_shape_trajectory_tracker_);
}

void test_high_accuracy_detector_hampel_master_switch_controls_both_streams(void) {
    HighAccuracyDetector detector;
    detector.configure_hampel(true, 5U, 3.0f);
    TEST_ASSERT_TRUE(detector.hampel_state_.enabled);
    TEST_ASSERT_TRUE(detector.aggregated_turbulence_.hampel_enabled());
    TEST_ASSERT_TRUE(detector.l1_tracker_.hampel_state_.enabled);

    detector.configure_hampel(false, 5U, 3.0f);
    TEST_ASSERT_FALSE(detector.hampel_state_.enabled);
    TEST_ASSERT_FALSE(detector.aggregated_turbulence_.hampel_enabled());
    TEST_ASSERT_FALSE(detector.l1_tracker_.hampel_state_.enabled);
}

// ============================================================================
// THRESHOLD TESTS
// ============================================================================

void test_high_accuracy_detector_set_threshold_valid(void) {
    HighAccuracyDetector detector;
    
    TEST_ASSERT_TRUE(detector.set_threshold(0.7f));
    TEST_ASSERT_EQUAL_FLOAT(0.7f, detector.get_threshold());
}

void test_high_accuracy_detector_set_threshold_min(void) {
    HighAccuracyDetector detector;
    
    TEST_ASSERT_TRUE(detector.set_threshold(HIGH_ACCURACY_MIN_THRESHOLD));
    TEST_ASSERT_EQUAL_FLOAT(HIGH_ACCURACY_MIN_THRESHOLD, detector.get_threshold());
}

void test_high_accuracy_detector_set_threshold_max(void) {
    HighAccuracyDetector detector;
    
    TEST_ASSERT_TRUE(detector.set_threshold(HIGH_ACCURACY_MAX_THRESHOLD));
    TEST_ASSERT_EQUAL_FLOAT(HIGH_ACCURACY_MAX_THRESHOLD, detector.get_threshold());
}

void test_high_accuracy_detector_set_threshold_below_min(void) {
    HighAccuracyDetector detector;
    float original = detector.get_threshold();
    
    TEST_ASSERT_FALSE(detector.set_threshold(-0.1f));
    TEST_ASSERT_EQUAL_FLOAT(original, detector.get_threshold());
}

void test_high_accuracy_detector_set_threshold_above_max(void) {
    HighAccuracyDetector detector;
    float original = detector.get_threshold();
    
    TEST_ASSERT_FALSE(detector.set_threshold(1.1f));
    TEST_ASSERT_EQUAL_FLOAT(original, detector.get_threshold());
}

// ============================================================================
// MLP INFERENCE TESTS
// ============================================================================

void test_ml_inference_matches_reference(void) {
    const float TOLERANCE = 2e-3f;  // Match Python export-regression tolerance
    TEST_ASSERT_TRUE_MESSAGE(num_test_samples > 0, "No test data loaded");
    HighAccuracyDetector detector;
    
    for (int i = 0; i < num_test_samples; i++) {
        float result = detector.predict(test_features[i].data());
        float expected = test_expected[i] * HIGH_ACCURACY_METRIC_SCALE;
        float error = std::abs(result - expected);
        
        ESP_LOGD(TEST_TAG, "Sample %d (idx=%d): expected=%.6f, got=%.6f, error=%.2e",
                 i, SAMPLE_INDICES[i], expected, result, error);
        
        TEST_ASSERT_FLOAT_WITHIN(TOLERANCE, expected, result);
    }
}

void test_ml_inference_output_range(void) {
    TEST_ASSERT_TRUE_MESSAGE(num_test_samples > 0, "No test data loaded");
    HighAccuracyDetector detector;
    
    for (int i = 0; i < num_test_samples; i++) {
        float result = detector.predict(test_features[i].data());
        
        TEST_ASSERT_TRUE(result >= 0.0f);
        TEST_ASSERT_TRUE(result <= HIGH_ACCURACY_METRIC_SCALE);
    }
}

void test_ml_inference_classification(void) {
    // Test that motion/idle classification is correct
    const float THRESHOLD = HIGH_ACCURACY_DEFAULT_THRESHOLD;
    TEST_ASSERT_TRUE_MESSAGE(num_test_samples > 0, "No test data loaded");
    HighAccuracyDetector detector;
    
    for (int i = 0; i < num_test_samples; i++) {
        float result = detector.predict(test_features[i].data());
        float expected = test_expected[i] * HIGH_ACCURACY_METRIC_SCALE;
        
        bool result_motion = (result > THRESHOLD);
        bool expected_motion = (expected > THRESHOLD);
        
        TEST_ASSERT_EQUAL(expected_motion, result_motion);
    }
}

// ============================================================================
// FEATURE EXTRACTION TESTS
// ============================================================================

void test_feature_extraction_basic(void) {
    float turb_buffer[50];
    float features[ML_MODEL_INPUT_SIZE];
    float sorted_scratch[50];
    const MLSeriesScratch scratch{sorted_scratch, 50U};

    // Fill both series with synthetic data.
    for (int i = 0; i < 50; i++) {
        turb_buffer[i] = 10.0f + (i % 5) * 0.5f;
    }

    // Extract exactly the exported feature set (turbulence and/or L1-delta).
    extract_ml_features_by_id(turb_buffer, 50, turb_buffer, 50,
                              ML_FEATURE_IDS, ML_MODEL_INPUT_SIZE, features,
                              scratch, 1.75f, 0.0f, 0.0f, 0.0f, 0.0f);

    // Every exported feature must be a finite number.
    for (int i = 0; i < ML_MODEL_INPUT_SIZE; i++) {
        TEST_ASSERT_TRUE(features[i] == features[i]);  // not NaN
        TEST_ASSERT_TRUE(features[i] < 1e30f && features[i] > -1e30f);
    }
}

void test_feature_extraction_empty_buffer(void) {
    float turb_buffer[50] = {0};
    float features[ML_MODEL_INPUT_SIZE];
    float sorted_scratch[50];
    const MLSeriesScratch scratch{sorted_scratch, 50U};

    // The tracker reports 1.0 when it holds no deltas, which is what the
    // detector would pass here, so the lag ratio is the one exported feature
    // whose empty-buffer value is not zero.
    extract_ml_features_by_id(turb_buffer, 0, nullptr, 0,
                              ML_FEATURE_IDS, ML_MODEL_INPUT_SIZE, features,
                              scratch, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f);

    // Every series-derived feature should be 0 for an empty buffer.
    for (int i = 0; i < ML_MODEL_INPUT_SIZE; i++) {
        if (ML_FEATURE_IDS[i] == ML_FEAT_L1_DELTA_LAG_RATIO) {
            TEST_ASSERT_EQUAL_FLOAT(1.0f, features[i]);
            continue;
        }
        TEST_ASSERT_EQUAL_FLOAT(0.0f, features[i]);
    }
}

void test_candidate_feature_python_parity(void) {
    // Same deterministic series as the Python reference:
    // turb[i] = 10.0 + (i % 5) * 0.5, delta[i] = 0.01 + (i % 7) * 0.002.
    float turb_buffer[50];
    for (int i = 0; i < 50; i++) {
        turb_buffer[i] = 10.0f + (i % 5) * 0.5f;
    }

    const uint8_t selected_ids[2] = {
        ML_FEAT_TURB_ZCR,
        ML_FEAT_L1_DELTA_LAG_RATIO,
    };
    float features[2];
    float sorted_scratch[50];
    const MLSeriesScratch scratch{sorted_scratch, 50U};
    extract_ml_features_by_id(turb_buffer, 50, nullptr, 0,
                              selected_ids, 2, features, scratch, 1.75f,
                              0.0f, 0.0f, 0.0f, 0.0f);

    // Expected values computed by src/python/micro_espectre/csi_features.py.
    TEST_ASSERT_FLOAT_WITHIN(1e-4f, 0.3877551f, features[0]);
    TEST_ASSERT_FLOAT_WITHIN(1e-6f, 1.75f, features[1]);
}

void test_zero_crossing_rate_alternating_signal(void) {
    float values[50];
    for (int i = 0; i < 50; i++) {
        values[i] = (i % 2 == 0) ? 1.0f : -1.0f;
    }
    TEST_ASSERT_EQUAL_FLOAT(1.0f, calc_zero_crossing_rate(values, 50, 0.0f));
    TEST_ASSERT_EQUAL_FLOAT(0.0f, calc_zero_crossing_rate(values, 1, 0.0f));
    TEST_ASSERT_EQUAL_FLOAT(0.0f, calc_zero_crossing_rate(nullptr, 50, 0.0f));
}

void test_ml_series_needs_tracks_only_referenced_stats(void) {
    // Production ids: normal turb {autocorr, zcr}, aggregated turb {iqr}, plus
    // the tracker-sourced lag ratio.
    const uint8_t production[4] = {
        ML_FEAT_TURB_IQR_OVER_MEAN_AGGR, ML_FEAT_TURB_AUTOCORR,
        ML_FEAT_TURB_ZCR, ML_FEAT_L1_DELTA_LAG_RATIO,
    };

    const MLStatNeeds turb = ml_series_needs(
        production, 4, MLFeatureSource::TURBULENCE_SERIES);
    TEST_ASSERT_TRUE(turb.sorted);       // zcr
    TEST_ASSERT_TRUE(turb.zcr);
    TEST_ASSERT_FALSE(turb.iqr);
    TEST_ASSERT_TRUE(turb.autocorr);

    const MLStatNeeds aggregated = ml_series_needs(
        production, 4, MLFeatureSource::AGGREGATED_TURBULENCE_SERIES);
    TEST_ASSERT_TRUE(aggregated.sorted);
    TEST_ASSERT_TRUE(aggregated.iqr);
    TEST_ASSERT_FALSE(aggregated.zcr);

}

void test_ml_feature_source_separates_tracker_from_series(void) {
    // The lag ratio needs the profile rings but not the rebuilt delta series;
    // classifying it by id magnitude would reserve a buffer it never reads.
    TEST_ASSERT_TRUE(ml_feature_needs_l1_tracker(ML_FEAT_L1_DELTA_LAG_RATIO));

    TEST_ASSERT_FALSE(ml_feature_needs_l1_tracker(ML_FEAT_TURB_ZCR));
    TEST_ASSERT_TRUE(
        ml_feature_needs_aggregated_turbulence(
            ML_FEAT_TURB_IQR_OVER_MEAN_AGGR));
    TEST_ASSERT_FALSE(
        ml_feature_needs_l1_tracker(ML_FEAT_TURB_IQR_OVER_MEAN_AGGR));
    TEST_ASSERT_TRUE(ml_feature_needs_channel_shape_trajectory_tracker(
        ML_FEAT_CHAN_SHAPE_SPREAD_SUBBAND));

    // A tracker-sourced id contributes no series statistics on either side.
    const uint8_t ratio_only[1] = {ML_FEAT_L1_DELTA_LAG_RATIO};
    for (MLFeatureSource source : {
            MLFeatureSource::TURBULENCE_SERIES,
            MLFeatureSource::AGGREGATED_TURBULENCE_SERIES}) {
        const MLStatNeeds needs = ml_series_needs(ratio_only, 1, source);
        TEST_ASSERT_FALSE(needs.sorted);
        TEST_ASSERT_FALSE(needs.autocorr);
    }
}

void test_aggregated_iqr_feature_matches_python_percentiles(void) {
    const float turb[4] = {5.0f, 5.0f, 5.0f, 5.0f};
    const float aggregated[4] = {1.0f, 2.0f, 4.0f, 8.0f};
    const uint8_t ids[1] = {ML_FEAT_TURB_IQR_OVER_MEAN_AGGR};
    float features[1];
    float sorted_scratch[4];
    const MLSeriesScratch scratch{sorted_scratch, 4U};
    extract_ml_features_by_id(
        turb, 4, aggregated, 4, ids, 1, features,
        scratch, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f);
    TEST_ASSERT_FLOAT_WITHIN(1e-6f, 0.8666667f, features[0]);
}

void test_w5_aggregation_averages_live_bin_magnitudes(void) {
    int8_t csi[HT20_CSI_LEN] = {0};
    for (uint8_t bin = 0U; bin < HT20_NUM_SUBCARRIERS; ++bin) {
        csi[bin * 2U + 1U] = static_cast<int8_t>(bin);
    }
    const uint8_t selected[4] = {4U, 28U, 36U, 60U};
    float amplitudes[4] = {0.0f};
    const uint8_t count = extract_adjacent_aggregated_subcarrier_amplitudes(
        csi, sizeof(csi), selected, 4U, TURB_IQR_AGGREGATION_WIDTH,
        amplitudes, 4U);
    TEST_ASSERT_EQUAL_UINT8(4U, count);
    TEST_ASSERT_FLOAT_WITHIN(1e-6f, 6.0f, amplitudes[0]);
    TEST_ASSERT_FLOAT_WITHIN(1e-6f, 28.0f, amplitudes[1]);
    TEST_ASSERT_FLOAT_WITHIN(1e-6f, 36.0f, amplitudes[2]);
    TEST_ASSERT_FLOAT_WITHIN(1e-6f, 58.0f, amplitudes[3]);
}

void test_l1_precomputed_mean_matches_default_normalization(void) {
    L1DeltaTracker direct;
    L1DeltaTracker shared_mean;
    direct.configure(32U);
    shared_mean.configure(32U);

    for (uint8_t packet = 0U; packet < 24U; ++packet) {
        float amplitudes[HT20_SELECTED_BAND_SIZE];
        for (uint8_t tone = 0U; tone < HT20_SELECTED_BAND_SIZE; ++tone) {
            amplitudes[tone] =
                1.0f + static_cast<float>((packet + 3U * tone) % 11U);
        }
        direct.process(amplitudes, HT20_SELECTED_BAND_SIZE);
        const MeanVariance stats = calculate_mean_variance_two_pass(
            amplitudes, HT20_SELECTED_BAND_SIZE);
        shared_mean.process(
            amplitudes, HT20_SELECTED_BAND_SIZE, stats.mean);
    }

    float direct_series[32]{};
    float shared_series[32]{};
    const uint16_t direct_count = direct.build_series(direct_series);
    const uint16_t shared_count = shared_mean.build_series(shared_series);
    TEST_ASSERT_EQUAL(direct_count, shared_count);
    for (uint16_t i = 0U; i < direct_count; ++i) {
        TEST_ASSERT_EQUAL_FLOAT(direct_series[i], shared_series[i]);
    }
    TEST_ASSERT_EQUAL_FLOAT(
        direct.delta_lag_ratio(), shared_mean.delta_lag_ratio());
}

// ============================================================================
// ML SUBCARRIERS TESTS
// ============================================================================

void test_ml_subcarriers_count(void) {
    TEST_ASSERT_EQUAL(12, sizeof(DEFAULT_SUBCARRIERS) / sizeof(DEFAULT_SUBCARRIERS[0]));
}

void test_ml_subcarriers_range(void) {
    for (int i = 0; i < 12; i++) {
        TEST_ASSERT_TRUE(DEFAULT_SUBCARRIERS[i] >= 0);
        TEST_ASSERT_TRUE(DEFAULT_SUBCARRIERS[i] < 64);  // HT20 has 64 subcarriers
    }
}

void test_ml_subcarriers_sorted(void) {
    for (int i = 1; i < 12; i++) {
        TEST_ASSERT_TRUE(DEFAULT_SUBCARRIERS[i] > DEFAULT_SUBCARRIERS[i-1]);
    }
}

// ============================================================================
// MAIN
// ============================================================================

// Shared across every detector; see detector_state_contract.h for why the
// metric is set directly rather than driven through synthetic traffic. This is
// the regression guard for ML publishing a stale probability after a clear.
void test_high_accuracy_detector_honours_shared_state_contract(void) {
    HighAccuracyDetector clear_target;
    test_support::assert_clear_buffer_drops_evaluation_state(clear_target);

    HighAccuracyDetector reset_target;
    test_support::assert_reset_drops_evaluation_state(reset_target);

    HighAccuracyDetector idle_target;
    test_support::assert_not_ready_evaluation_stays_idle(idle_target);
}

int main(int argc, char **argv) {
    UNITY_BEGIN();
    
    // Initialization tests
    RUN_TEST(test_high_accuracy_detector_default_constructor);
    RUN_TEST(test_high_accuracy_detector_custom_constructor);
    RUN_TEST(test_high_accuracy_detector_get_name);
    RUN_TEST(test_ml_production_feature_schema);
    RUN_TEST(test_high_accuracy_detector_honours_shared_state_contract);
    RUN_TEST(test_high_accuracy_detector_hampel_master_switch_controls_both_streams);
    
    // Threshold tests
    RUN_TEST(test_high_accuracy_detector_set_threshold_valid);
    RUN_TEST(test_high_accuracy_detector_set_threshold_min);
    RUN_TEST(test_high_accuracy_detector_set_threshold_max);
    RUN_TEST(test_high_accuracy_detector_set_threshold_below_min);
    RUN_TEST(test_high_accuracy_detector_set_threshold_above_max);
    
    // MLP inference tests
    RUN_TEST(test_ml_inference_matches_reference);
    RUN_TEST(test_ml_inference_output_range);
    RUN_TEST(test_ml_inference_classification);
    
    // Feature extraction tests
    RUN_TEST(test_feature_extraction_basic);
    RUN_TEST(test_feature_extraction_empty_buffer);
    RUN_TEST(test_candidate_feature_python_parity);
    RUN_TEST(test_zero_crossing_rate_alternating_signal);
    RUN_TEST(test_ml_series_needs_tracks_only_referenced_stats);
    RUN_TEST(test_ml_feature_source_separates_tracker_from_series);
    RUN_TEST(test_aggregated_iqr_feature_matches_python_percentiles);
    RUN_TEST(test_w5_aggregation_averages_live_bin_magnitudes);
    RUN_TEST(test_l1_precomputed_mean_matches_default_normalization);
    
    // Subcarriers tests
    RUN_TEST(test_ml_subcarriers_count);
    RUN_TEST(test_ml_subcarriers_range);
    RUN_TEST(test_ml_subcarriers_sorted);
    
    return UNITY_END();
}
