# ESPectre - ESP32-C6 UART Dev (local components)
# Usage: esphome run examples/uart/espectre-c6-dev.yaml

packages:
  base: !include espectre-c6.yaml

# Local component for development (overrides GitHub source)
external_components:
  - source:
      type: local
      path: ../../components
    components: [ espectre ]

# ESPectre - WiFi CSI Motion Detection
# All parameters shown with defaults
espectre:
  id: espectre_csi
  # Traffic Generator
  traffic_generator_rate: 100   # Packets/sec for CSI generation (0-1000)
  traffic_generator_mode: dns   # dns (default) or ping
  # Gain Lock Mode
  gain_lock: auto               # auto (default), enabled, disabled
  # Detection Algorithm
  detection_algorithm: mvs      # mvs (default) or ml (neural network)
  # Segmentation parameters
  segmentation_window_size: 75  # Analysis window size in packets (10-200)
  segmentation_threshold: auto  # auto/min (mvs: 0.1-10.0, ml: 0.0-1.0)
  # Filters (optional)
  hampel_enabled: false         # Outlier removal (default: false)
  hampel_window: 9              # Filter window size (3-11, odd numbers)
  hampel_threshold: 4.0         # Outlier detection threshold (1.0-10.0)
  lowpass_enabled: false        # Noise reduction (default: false)
  lowpass_cutoff: 11.0          # Cutoff frequency in Hz (5.0-20.0)
  # Manual subcarrier override (leave commented for auto-calibration)
  #selected_subcarriers: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      #bssid: !secret wifi_bssid  # Lock to specific Access Point (useful for mesh networks)

logger:
  level: DEBUG
  logs:
    sensor: INFO
    binary_sensor: INFO

debug:
  update_interval: 5s

sensor:
  - platform: debug
    free:
      name: "Free Heap"
    block:
      name: "Max Free Block"
    loop_time:
      name: "Loop Time"

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
