# ESPectre - ESP32-S3 Development Configuration with UART0 Logging
# LOCAL DEVELOPMENT VERSION for CI/QEMU testing
#
# This file uses local components for development and UART0 for QEMU compatibility.
# For production use, see espectre-s3.yaml (uses GitHub source).
#
# Tested boards:
# - ESP32-S3-DevKitC-1 (WROOM-1-N16R8)

esphome:
  name: espectre_uart
  friendly_name: ESPectre UART Dev
  min_version: 2025.11.0

esp32:
  variant: ESP32S3
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

# PSRAM support (8MB on most S3 boards)
psram:
  mode: octal
  speed: 80MHz

# Load ESPectre component from local source (for CI/QEMU testing)
external_components:
  - source:
      type: local
      path: ../../components
    components: [ espectre ]

# ESPectre - WiFi CSI Motion Detection
espectre:
  id: espectre_csi

# WiFi with fallback AP (no secrets needed for CI)
wifi:
  ap:
    ssid: "ESPectre Fallback"

captive_portal:

# Improv provisioning via BLE
esp32_improv:
  authorizer: none

# Improv provisioning via USB
improv_serial:

# Logging - UART0 for QEMU compatibility
logger:
  hardware_uart: UART0

# Home Assistant API
api:

# OTA updates
ota:
  - platform: esphome
