# ESPectre - ESP32-C3 Configuration (UART0 Logging)
# For boards with external USB-UART bridges (CH343, CP2102, etc.)
#
# Use this config if your C3 board has a separate USB-UART chip.
# Use espectre-c3.yaml for boards with native USB (no bridge).
#
# This config is also used for QEMU boot testing in CI.

esphome:
  name: espectre
  friendly_name: ESPectre
  min_version: 2025.11.0
  project:
    name: francescopace.espectre
    version: "2.2.0"

esp32:
  variant: ESP32C3
  framework:
    type: esp-idf

# Load ESPectre component from GitHub
external_components:
  - source:
      type: git
      url: https://github.com/francescopace/espectre
      ref: main
    components: [ espectre ]
    refresh: always

# ESPectre - WiFi CSI Motion Detection
espectre:
  id: espectre_csi
  traffic_generator_rate: 94

# Dashboard import
dashboard_import:
  package_import_url: github://francescopace/espectre/examples/uart/espectre-c3.yaml@main
  import_full_config: true

# WiFi with fallback AP for provisioning
wifi:
  ap:
    ssid: "ESPectre Fallback"

captive_portal:

# Improv provisioning via BLE
esp32_improv:
  authorizer: none

# Improv provisioning via USB
improv_serial:

# Logging via UART0 (for boards with USB-UART bridges)
logger:
  hardware_uart: UART0

# Home Assistant API
api:

# OTA updates
ota:
  - platform: esphome

