"""
Micro-ESPectre - Gesture Detector

Event-driven gesture classifier. Maintains a circular look-back buffer that
is always updated with incoming CSI packets.

Architecture:
  - Circular ring buffer (300 packets, ~3s look-back) always active
  - start_detection(): snapshots ring buffer as pre-roll for the event buffer
  - process_packet() accumulates turbulence+phases into ring buffer;
    when active, also appends to event buffer
  - finalize_detection(): extracts gesture features from event buffer, runs
    MLP inference, returns gesture name

Inference requires gesture_weights.py (auto-generated by 12_train_gesture_model.py).
When weights are not yet available, finalize_detection() returns None.

Author: Francesco Pace <francesco.pace@gmail.com>
License: GPLv3
"""

import math

try:
    from src.segmentation import SegmentationContext
    from src.utils import extract_phases
    from src.gesture_features import extract_gesture_features, GESTURE_FEATURES
except ImportError:
    from segmentation import SegmentationContext
    from utils import extract_phases
    from gesture_features import extract_gesture_features, GESTURE_FEATURES

# Gesture weights are optional (not available until model is trained)
_weights_available = False
try:
    try:
        import src.gesture_weights as _gw
    except ImportError:
        import gesture_weights as _gw
    _weights_available = True
except ImportError:
    _gw = None

__all__ = ['GestureDetector']

# Fixed classification window length in packets (2 seconds at 100 pps)
GESTURE_WINDOW_LEN = 200

# Pre-roll copied at motion start (0.75 seconds at 100 pps)
GESTURE_PREROLL_LEN = 75

# Live inference cadence while MOTION is active (in packets)
GESTURE_LIVE_STRIDE = 25

# Maximum event duration equals fixed classification window.
MAX_EVENT_LEN = GESTURE_WINDOW_LEN

# Ring buffer size for look-back pre-roll (3 seconds at 100 pps)
RING_BUFFER_LEN = 300

# Runtime gating to reduce false positives on live stream.
# Thresholds are auto-calibrated during training and exported in gesture_weights.
_export_conf = float(getattr(_gw, 'GESTURE_REJECT_CONFIDENCE', 0.55)) if _weights_available else 0.55
_export_margin = float(getattr(_gw, 'GESTURE_REJECT_MARGIN', 0.05)) if _weights_available else 0.05
# Streaming-oriented caps: keep reject behavior but avoid over-suppressing gestures.
GESTURE_MIN_CONFIDENCE = min(_export_conf, 0.15)
GESTURE_MIN_MARGIN = min(_export_margin, 0.00)
GESTURE_MIN_CONSECUTIVE = 1
GESTURE_SELECTED_FEATURES = list(getattr(_gw, 'GESTURE_FEATURE_NAMES', GESTURE_FEATURES)) if _weights_available else list(GESTURE_FEATURES)

# Fixed subcarriers for turbulence/phase calculation (same as MLDetector)
GESTURE_SUBCARRIERS = [12, 14, 16, 18, 20, 24, 28, 36, 40, 44, 48, 52]


# ============================================================================
# Tiny-MLP inference for gesture classes
# ============================================================================

def _softmax(logits):
    max_val = max(logits)
    exp_vals = [math.exp(v - max_val) for v in logits]
    total = sum(exp_vals)
    return [e / total for e in exp_vals]


def _normalize(features, mean, scale):
    return [(features[i] - mean[i]) / scale[i] for i in range(len(features))]


def _predict_mlp(features):
    """Run tiny MLP forward pass on normalized features."""
    x = _normalize(features, _gw.GESTURE_FEATURE_MEAN, _gw.GESTURE_FEATURE_SCALE)
    layer = x
    num_layers = int(getattr(_gw, 'GESTURE_MLP_NUM_LAYERS', 0))
    layer_sizes = list(getattr(_gw, 'GESTURE_MLP_LAYER_SIZES', []))
    w_off = list(getattr(_gw, 'GESTURE_MLP_WEIGHT_OFFSETS', []))
    b_off = list(getattr(_gw, 'GESTURE_MLP_BIAS_OFFSETS', []))
    weights = list(getattr(_gw, 'GESTURE_MLP_WEIGHTS', []))
    biases = list(getattr(_gw, 'GESTURE_MLP_BIASES', []))

    if num_layers < 2 or not layer_sizes or not w_off or not b_off:
        return 0, 0.0, 0.0

    for li in range(num_layers - 1):
        in_size = layer_sizes[li]
        out_size = layer_sizes[li + 1]
        w_start = w_off[li]
        b_start = b_off[li]
        out = [0.0] * out_size
        for o in range(out_size):
            s = biases[b_start + o]
            row_base = w_start + o * in_size
            for i in range(in_size):
                s += weights[row_base + i] * layer[i]
            # ReLU on hidden layers only
            if li < (num_layers - 2):
                s = s if s > 0.0 else 0.0
            out[o] = s
        layer = out

    probs = _softmax(layer)
    ranked = sorted(enumerate(probs), key=lambda x: x[1], reverse=True)
    class_id, top_prob = ranked[0]
    second_prob = ranked[1][1] if len(ranked) > 1 else 0.0
    return class_id, top_prob, top_prob - second_prob


def predict_gesture(features):
    """
    Predict gesture class from feature vector.

    Args:
        features: List of NUM_GESTURE_FEATURES floats

    Returns:
        tuple: (class_id, class_name, confidence, margin) or
               (0, 'unknown', 0.0, 0.0) if
               weights not available.
    """
    if not _weights_available or _gw is None:
        return 0, 'unknown', 0.0, 0.0

    class_id, top_prob, margin = _predict_mlp(features)
    class_name = _gw.GESTURE_CLASS_LABELS[class_id] if class_id < len(_gw.GESTURE_CLASS_LABELS) else 'unknown'
    return class_id, class_name, top_prob, margin


# ============================================================================
# GestureDetector
# ============================================================================

class GestureDetector:
    """
    Continuous gesture classifier.

    Maintains a circular look-back ring buffer that is always updated with
    each CSI packet. start_detection()
    snapshots the ring buffer as pre-roll. Packets are accumulated until
    finalize_detection() is called, at which point the full event is classified.

    Usage:
        gd = GestureDetector()

        # In packet loop (runs for every CSI packet):
        gd.process_packet(csi_data, selected_subcarriers)

        gd.start_detection()

        gesture = gd.finalize_detection()  # Returns gesture name or None
    """

    def __init__(self, ring_size=RING_BUFFER_LEN, max_event_len=MAX_EVENT_LEN,
                 use_cv_normalization=False):
        """
        Initialize GestureDetector.

        Args:
            ring_size: Number of packets in the circular look-back buffer (default: 300)
            max_event_len: Maximum event duration in packets (default: 200)
            use_cv_normalization: Use CV normalization for turbulence (default: False)
        """
        self._ring_size = ring_size
        self._max_event_len = max_event_len
        self._use_cv_norm = use_cv_normalization

        # Circular ring buffer: always holds the last ring_size packets
        self._ring = []       # list of {'turbulence': float, 'phases': list}
        self._ring_head = 0   # index of oldest element (when full)
        self._ring_count = 0  # number of valid elements

        # Event buffer: populated during an active event
        self._event = []
        self._active = False
        self._pending_live_gesture = None
        self._last_live_gesture = None
        self._live_packets_since_start = 0
        self._candidate_label = None
        self._candidate_count = 0

        # SegmentationContext for turbulence calculation (shared with motion algorithm)
        self._ctx = SegmentationContext(
            window_size=1,   # We only need compute_spatial_turbulence, not the buffer
            threshold=1.0,
        )
        self._ctx.use_cv_normalization = use_cv_normalization

        self._last_gesture = None

    # ------------------------------------------------------------------
    # Packet processing
    # ------------------------------------------------------------------

    def process_packet(self, csi_data, selected_subcarriers=None):
        """
        Process a CSI packet, updating the ring buffer and (if active) event buffer.

        Args:
            csi_data: Raw CSI bytes (I/Q interleaved int8)
            selected_subcarriers: List of subcarrier indices to use
        """
        sc = selected_subcarriers or GESTURE_SUBCARRIERS

        # Compute turbulence and phases for this packet
        turbulence, _ = self._ctx.compute_spatial_turbulence(
            csi_data, sc, use_cv_normalization=self._use_cv_norm
        )
        phases = extract_phases(csi_data, sc)

        entry = {'turbulence': turbulence, 'phases': phases}

        # Always update ring buffer (fixed-size circular)
        if self._ring_count < self._ring_size:
            self._ring.append(entry)
            self._ring_count += 1
        else:
            self._ring[self._ring_head] = entry
            self._ring_head = (self._ring_head + 1) % self._ring_size

        # Accumulate into event buffer when active
        if self._active:
            if len(self._event) < self._max_event_len:
                self._event.append(entry)
            else:
                # Sliding window: drop oldest and append newest packet.
                self._event.pop(0)
                self._event.append(entry)

            self._live_packets_since_start += 1

            # Continuous live inference at fixed cadence on the sliding window.
            if (_weights_available and
                    len(self._event) >= GESTURE_WINDOW_LEN and
                    self._live_packets_since_start % GESTURE_LIVE_STRIDE == 0):
                features = extract_gesture_features(self._event, feature_names=GESTURE_SELECTED_FEATURES)
                _, name, conf, margin = predict_gesture(features)
                self._last_gesture = name
                if (name is not None and
                        conf >= GESTURE_MIN_CONFIDENCE and
                        margin >= GESTURE_MIN_MARGIN):
                    if name == self._candidate_label:
                        self._candidate_count += 1
                    else:
                        self._candidate_label = name
                        self._candidate_count = 1
                    if self._candidate_count >= GESTURE_MIN_CONSECUTIVE:
                        self._pending_live_gesture = name
                else:
                    # Low-confidence samples are explicitly rejected as no_gesture.
                    self._pending_live_gesture = 'no_gesture'

    # ------------------------------------------------------------------
    # Event lifecycle
    # ------------------------------------------------------------------

    def start_detection(self):
        """
        Snapshots the ring buffer as pre-roll for the event buffer, so that
        the beginning of the gesture is included in the classification window.
        """
        # Reconstruct ring buffer in chronological order.
        if self._ring_count < self._ring_size:
            pre_roll = list(self._ring[:self._ring_count])
        else:
            # Oldest element is at _ring_head
            pre_roll = (self._ring[self._ring_head:] +
                        self._ring[:self._ring_head])

        # Keep only the latest fixed pre-roll to align with training windowing.
        pre_len = min(GESTURE_PREROLL_LEN, len(pre_roll))
        self._event = list(pre_roll[-pre_len:])
        self._active = True
        self._pending_live_gesture = None
        self._last_live_gesture = None
        self._live_packets_since_start = 0
        self._candidate_label = None
        self._candidate_count = 0

    def finalize_detection(self):
        """
        Classifies the accumulated event and returns the gesture name.

        Returns:
            str or None: Gesture name (e.g. 'wave'), or None if:
                - Event is too short (< 200 packets) to classify reliably
                - gesture_weights.py not yet available (untrained)
        """
        self._active = False

        event = self._event
        self._event = []  # Always clear event buffer, regardless of outcome

        if len(event) < GESTURE_WINDOW_LEN:
            self._pending_live_gesture = None
            self._last_live_gesture = None
            self._live_packets_since_start = 0
            self._candidate_label = None
            self._candidate_count = 0
            return None

        if not _weights_available:
            return None

        features = extract_gesture_features(event, feature_names=GESTURE_SELECTED_FEATURES)
        _, name, conf, margin = predict_gesture(features)
        if conf < GESTURE_MIN_CONFIDENCE or margin < GESTURE_MIN_MARGIN:
            name = 'no_gesture'
        self._last_gesture = name
        self._live_packets_since_start = 0
        self._last_live_gesture = None
        self._candidate_label = None
        self._candidate_count = 0
        return name

    def get_last_gesture(self):
        """Return the last classified gesture name."""
        return self._last_gesture

    def consume_live_prediction(self):
        """Return and clear pending live prediction, if available."""
        out = self._pending_live_gesture
        self._pending_live_gesture = None
        return out

    def reset(self):
        """Reset detector state (ring buffer preserved for continuity)."""
        self._event = []
        self._active = False
        self._last_gesture = None
        self._pending_live_gesture = None
        self._last_live_gesture = None
        self._live_packets_since_start = 0
        self._candidate_label = None
        self._candidate_count = 0

    def clear_ring(self):
        """Clear the ring buffer (call after a WiFi channel change)."""
        self._ring = []
        self._ring_head = 0
        self._ring_count = 0
        self._event = []
        self._active = False
        self._pending_live_gesture = None
        self._last_live_gesture = None
        self._live_packets_since_start = 0
        self._candidate_label = None
        self._candidate_count = 0

    @property
    def is_active(self):
        """True if currently accumulating an event."""
        return self._active

    @property
    def event_len(self):
        """Current event buffer length in packets."""
        return len(self._event)

    @property
    def weights_available(self):
        """True if gesture_weights.py is loaded and inference is possible."""
        return _weights_available
