"""
Micro-ESPectre - Gesture LogReg Weights

Auto-generated logistic regression weights for gesture classification.
Architecture: LogReg (9 -> 3)
Trained: 2026-03-15 14:03:40
Seed: 805649460

This file is auto-generated by 12_train_gesture_model.py.
DO NOT EDIT - your changes will be overwritten!

Author: Francesco Pace <francesco.pace@gmail.com>
License: GPLv3
"""

GESTURE_CLASS_LABELS = ['wave', 'circle_cw', 'no_gesture']
GESTURE_NUM_CLASSES = 3
GESTURE_NUM_FEATURES = 9
GESTURE_FEATURE_NAMES = ['phase_entropy', 'turb_iqr', 'event_duration', 'turb_diff_abs_mean', 'turb_mid_mean', 'phase_diff_var', 'phase_inter_sc_coherence', 'turb_range', 'turb_delta_energy']
GESTURE_FEATURE_IDS = [14, 8, 0, 12, 9, 13, 16, 17, 18]
GESTURE_REJECT_CONFIDENCE = 0.200000
GESTURE_REJECT_MARGIN = 0.120000

GESTURE_FEATURE_MEAN = [1.941369, 4.537810, 0.991250, 2.620043, 11.591100, 0.439949, 0.991854, 11.734378, 17.874845]
GESTURE_FEATURE_SCALE = [0.035748, 2.868591, 0.028257, 1.144627, 1.184703, 0.119878, 0.002728, 2.135945, 9.892751]

GESTURE_LOGREG_COEFS = [0.81680858, -0.33563226, 0.49421686, -0.08004459, 0.43787879, 0.51113933, -0.75912726, -0.77271628, -0.50285667, 0.19678301, 1.25197899, 0.21821442, 0.48135719, -0.41722095, -0.05569398, -1.03612220, 0.11377960, 1.12331378, -1.01359165, -0.91634679, -0.71243125, -0.40131262, -0.02065782, -0.45544535, 1.79524946, 0.65893668, -0.62045711]
GESTURE_LOGREG_INTERCEPTS = [0.61247689, -0.75919163, 0.14671473]
