"""
Micro-ESPectre - Gesture LogReg Weights

Auto-generated logistic regression weights for gesture classification.
Architecture: 12 -> 3 (softmax)
Classes: 3
Trained: 2026-03-03 23:58:14
Seed: 1917586999

This file is auto-generated by 11_train_gesture_model.py.
DO NOT EDIT - your changes will be overwritten!

Author: Francesco Pace <francesco.pace@gmail.com>
License: GPLv3
"""

GESTURE_FEATURE_MEAN = [1.097500, 0.453553, 1.534071, -0.092895, 1.027901, 1.914167, 0.066745, 1.022496, 3.206552, 1.145237, 1.544903, 0.216352]
GESTURE_FEATURE_SCALE = [0.103652, 0.278116, 0.341206, 0.556232, 0.270671, 1.912298, 0.132426, 0.939867, 3.300558, 0.730325, 0.282965, 0.165910]
GESTURE_CLASS_LABELS = ['wave', 'circle_cw', 'no_gesture']
GESTURE_NUM_CLASSES = 3

# Single affine layer logits = x_norm @ W1 + B1
W1 = [
    [1.317486, 0.949319, -2.266806],
    [-0.300656, 0.203831, 0.096825],
    [-0.816334, 0.901441, -0.085107],
    [-0.300656, 0.203831, 0.096825],
    [0.020436, 0.029963, -0.050399],
    [-1.075285, 1.320863, -0.245578],
    [0.065980, -0.121140, 0.055160],
    [-0.496184, 0.357534, 0.138649],
    [-0.393282, -0.005184, 0.398466],
    [-0.101682, -0.360097, 0.461778],
    [-0.073356, 0.205634, -0.132278],
    [0.092267, -0.458826, 0.366559],
]
B1 = [-0.589033, -0.758690, 1.347723]
